Repository OCA/server-ux, pull requests merged in 2019-02, with the labels that each got.

#48 [11.0][IMP] base_tier_validation:
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONFIGURE.rst
  base_tier_validation/readme/CONTRIBUTORS.rst
  base_tier_validation/readme/DESCRIPTION.rst
  base_tier_validation/readme/ROADMAP.rst
  base_tier_validation/static/description/index.html
  base_tier_validation/views/tier_definition_view.xml
  base_tier_validation/views/tier_review_view.xml
Labels: approved, ready to merge

#53 [11.0][FIX] base_tier_validation
  base_tier_validation/models/tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: approved

#50 [FIX] don't break when we have a nonexisting model
  base_optional_quick_create/models/ir_model.py
Labels: approved, needs review
