Repository OCA/server-ux, pull requests merged in 2020-10, with the labels that each got.

#200 [Update] mass_editing icon
  mass_editing/static/description/icon.png
  mass_editing/static/description/icon.svg
Labels: bot is merging ⏳

#213 [FIX] mass_editing migration V12
  mass_editing/migrations/12.0.2.0.1/post-migration.py
  mass_editing/migrations/12.0.2.0.1/pre-migration.py
Labels: approved, bot is merging ⏳

#218 [12.0][UPD] Brainbean Apps => CorporateHub
  base_user_locale/__manifest__.py
  base_user_locale/readme/CONTRIBUTORS.rst
  multi_step_wizard/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#214 [FIX] mass_editing: Add company field in wizard to avoid error for fields with attribute check_company
  mass_editing/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#215 [12.0][MIG+FIX] mass_editing: Complete migration scripts
  mass_editing/migrations/12.0.2.0.2/post-migration.py
  mass_editing/migrations/12.0.2.0.2/pre-migration.py
Labels: bot is merging ⏳, needs review

#222 [14.0][FIX] date_range: typo in date_start field name
  date_range/wizard/date_range_generator.py
Labels: approved, bot is merging ⏳

#224 [13.0][FIX] default_multi_user: multi company issue
  default_multi_user/models/ir_default.py
  default_multi_user/tests/test_default_multi_user.py
Labels: approved, bot is merging ⏳
