Repository OCA/server-ux, pull requests merged in 2020-07, with the labels that each got.

#176 [13.0][MIG] sequence_reset_period
  sequence_reset_period/README.rst
  sequence_reset_period/__init__.py
  sequence_reset_period/__manifest__.py
  sequence_reset_period/i18n/es.po
  sequence_reset_period/i18n/hr.po
  sequence_reset_period/i18n/sequence_reset_period.pot
  sequence_reset_period/models/__init__.py
  sequence_reset_period/models/ir_sequence.py
  sequence_reset_period/readme/CONTRIBUTORS.rst
  sequence_reset_period/readme/DESCRIPTION.rst
  sequence_reset_period/readme/USAGE.rst
  sequence_reset_period/static/description/icon.png
  sequence_reset_period/static/description/index.html
  sequence_reset_period/tests/__init__.py
  sequence_reset_period/tests/test_period.py
  sequence_reset_period/views/sequence_views.xml
  setup/sequence_reset_period/odoo/addons/sequence_reset_period
  setup/sequence_reset_period/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#174 [IMP] base_tier_validation: notification hook
  base_tier_validation/__manifest__.py
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#180 [IMP] base_tier_validation: notification hook
  base_tier_validation/__manifest__.py
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#178 [11.0][ADD] filter_multi_user
  filter_multi_user/README.rst
  filter_multi_user/__init__.py
  filter_multi_user/__manifest__.py
  filter_multi_user/models/__init__.py
  filter_multi_user/models/ir_filters.py
  filter_multi_user/readme/CONFIGURE.rst
  filter_multi_user/readme/CONTRIBUTORS.rst
  filter_multi_user/readme/DESCRIPTION.rst
  filter_multi_user/security/ir_filters_security.xml
  filter_multi_user/static/description/index.html
  filter_multi_user/tests/__init__.py
  filter_multi_user/tests/test_filter_multi_user.py
  filter_multi_user/views/ir_filters_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#184 [12.0][MIG] filter_multi_user
  filter_multi_user/README.rst
  filter_multi_user/__init__.py
  filter_multi_user/__manifest__.py
  filter_multi_user/i18n/filter_multi_user.pot
  filter_multi_user/models/__init__.py
  filter_multi_user/models/ir_filters.py
  filter_multi_user/readme/CONFIGURE.rst
  filter_multi_user/readme/CONTRIBUTORS.rst
  filter_multi_user/readme/DESCRIPTION.rst
  filter_multi_user/security/ir_filters_security.xml
  filter_multi_user/static/description/icon.png
  filter_multi_user/static/description/index.html
  filter_multi_user/tests/__init__.py
  filter_multi_user/tests/test_filter_multi_user.py
  filter_multi_user/views/ir_filters_view.xml
Labels: approved, bot is merging ⏳

#183 [11.0][ADD] default_multi_user
  default_multi_user/README.rst
  default_multi_user/__init__.py
  default_multi_user/__manifest__.py
  default_multi_user/hooks.py
  default_multi_user/models/__init__.py
  default_multi_user/models/ir_default.py
  default_multi_user/readme/CONFIGURE.rst
  default_multi_user/readme/CONTRIBUTORS.rst
  default_multi_user/readme/DESCRIPTION.rst
  default_multi_user/static/description/index.html
  default_multi_user/tests/__init__.py
  default_multi_user/tests/test_default_multi_user.py
  default_multi_user/views/ir_default_view.xml
Labels: approved, bot is merging ⏳

#181 [IMP] base_tier_validation: Make test more resilient with sales and purchase modules installed
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#188 [12.0][MIG] default_multi_user
  default_multi_user/README.rst
  default_multi_user/__init__.py
  default_multi_user/__manifest__.py
  default_multi_user/hooks.py
  default_multi_user/i18n/default_multi_user.pot
  default_multi_user/models/__init__.py
  default_multi_user/models/ir_default.py
  default_multi_user/readme/CONFIGURE.rst
  default_multi_user/readme/CONTRIBUTORS.rst
  default_multi_user/readme/DESCRIPTION.rst
  default_multi_user/static/description/icon.png
  default_multi_user/static/description/index.html
  default_multi_user/tests/__init__.py
  default_multi_user/tests/test_default_multi_user.py
  default_multi_user/views/ir_default_view.xml
Labels: approved, bot is merging ⏳
