Repository OCA/server-ux, pull requests merged in 2020-04, with the labels that each got.

#78 [11.0][IMP] mass_editing Fix label disappearing
  mass_editing/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#150 [12.0][FIX] tier validation
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#153 [12.0][ADD] base_search_custom_field_filter: Add custom filters for fields via UI
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/readme/CONFIGURE.rst
  base_search_custom_field_filter/readme/CONTRIBUTORS.rst
  base_search_custom_field_filter/readme/DESCRIPTION.rst
  base_search_custom_field_filter/readme/USAGE.rst
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/static/src/js/search_input.js
  base_search_custom_field_filter/templates/assets.xml
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
Labels: bot is merging ⏳

#151 [13.0][FWPORT] base_tier_validation: can_review fixes and secuiry
  .isort.cfg
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳
