Repository OCA/server-ux, pull requests merged in 2020-09, with the labels that each got.

#204 [FIX] mass_editing: Reference to unexisting view type
  mass_editing/models/mass_object.py
Labels: bot is merging ⏳

#198 [13.0][FIX] base_tier_validation, fix approve by sequence problem
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONTRIBUTORS.rst
  base_tier_validation/readme/HISTORY.rst
  base_tier_validation/static/src/js/systray.js
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/wizard/comment_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#145 [12.0][FIX] base_tier_validation : convert datetime timezone
  base_tier_validation/models/res_users.py
  base_tier_validation/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#206 [13.0][FIX] base_tier_validation : convert datetime timezone
  base_tier_validation/models/res_users.py
  base_tier_validation/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#194 [12.0][FIX] improve perf and solve compatibility with base_jsonify
  base_export_manager/models/ir_exports_line.py
Labels: approved, bot is merging ⏳, ready to merge

#189 [13.0][MIG] default_multi_user
  default_multi_user/README.rst
  default_multi_user/__init__.py
  default_multi_user/__manifest__.py
  default_multi_user/hooks.py
  default_multi_user/i18n/default_multi_user.pot
  default_multi_user/models/__init__.py
  default_multi_user/models/ir_default.py
  default_multi_user/readme/CONFIGURE.rst
  default_multi_user/readme/CONTRIBUTORS.rst
  default_multi_user/readme/DESCRIPTION.rst
  default_multi_user/static/description/icon.png
  default_multi_user/static/description/index.html
  default_multi_user/tests/__init__.py
  default_multi_user/tests/test_default_multi_user.py
  default_multi_user/views/ir_default_view.xml
  setup/default_multi_user/odoo/addons/default_multi_user
  setup/default_multi_user/setup.py
Labels: approved, bot is merging ⏳
