Repository OCA/server-ux, pull requests merged in 2020-05, with the labels that each got.

#152 12.0 mig base import security group
  base_import_security_group/__init__.py
  base_import_security_group/__manifest__.py
  base_import_security_group/i18n/ca.po
  base_import_security_group/i18n/de.po
  base_import_security_group/i18n/es.po
  base_import_security_group/i18n/fr.po
  base_import_security_group/i18n/gl.po
  base_import_security_group/i18n/hr.po
  base_import_security_group/i18n/it.po
  base_import_security_group/i18n/pt.po
  base_import_security_group/i18n/sk.po
  base_import_security_group/models/__init__.py
  base_import_security_group/models/models.py
  base_import_security_group/readme/CONTRIBUTORS.rst
  base_import_security_group/readme/DESCRIPTION.rst
  base_import_security_group/security/base_import_security_group_security.xml
  base_import_security_group/static/description/icon.png
  base_import_security_group/static/description/icon.svg
  base_import_security_group/static/description/index.html
  base_import_security_group/static/src/js/import.js
  base_import_security_group/tests/__init__.py
  base_import_security_group/tests/test_base_import_security_group.py
  base_import_security_group/views/base_import.xml
Labels: approved, bot is merging ⏳, ready to merge

#162 [FIX] Give travis some more time to determine if user is allowed to import
  base_import_security_group/tests/test_base_import_security_group.py
Labels: bot is merging ⏳

#163 [13.0][FIX] base_tier_validation: All models are visible when create a new definition
  base_tier_validation/models/tier_definition.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#159 [13.0][MIG]base search custom field filter
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/i18n/base_search_custom_field_filter.pot
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/readme/CONFIGURE.rst
  base_search_custom_field_filter/readme/CONTRIBUTORS.rst
  base_search_custom_field_filter/readme/DESCRIPTION.rst
  base_search_custom_field_filter/readme/USAGE.rst
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/icon.png
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/static/src/js/search_bar_autocomplete_sources.js
  base_search_custom_field_filter/templates/assets.xml
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
  setup/base_search_custom_field_filter/setup.py
Labels: approved, bot is merging ⏳
