Repository OCA/server-ux, pull requests merged in 2020-11, with the labels that each got.

#232 [UPD] Brainbean Apps => CorporateHub
  multi_step_wizard/README.rst
  multi_step_wizard/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#230 [12.0][IMP] base_tier_validation: state check
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳, ready to merge

#235 [13.0][IMP] base_tier_validation: state check
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#233 [13.0][IMP] base_tier_validation: make module multi-company compatible.
  base_tier_validation/__manifest__.py
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/security/tier_validation_security.xml
Labels: approved, bot is merging ⏳, ready to merge

#240 [13.0][FIX] multi_step_wizard: allow_back
  multi_step_wizard/models/multi_step_wizard.py
Labels: approved, bot is merging ⏳

#226 [14.0][MIG] base_tier_validation
  base_tier_validation/README.rst
  base_tier_validation/__init__.py
  base_tier_validation/__manifest__.py
  base_tier_validation/data/mail_data.xml
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/i18n/nl_NL.po
  base_tier_validation/i18n/zh_CN.po
  base_tier_validation/models/__init__.py
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONFIGURE.rst
  base_tier_validation/readme/CONTRIBUTORS.rst
  base_tier_validation/readme/DESCRIPTION.rst
  base_tier_validation/readme/HISTORY.rst
  base_tier_validation/readme/ROADMAP.rst
  base_tier_validation/security/ir.model.access.csv
  base_tier_validation/security/tier_validation_security.xml
  base_tier_validation/static/description/icon.png
  base_tier_validation/static/description/index.html
  base_tier_validation/static/src/js/systray.js
  base_tier_validation/static/src/js/tier_review_widget.js
  base_tier_validation/static/src/scss/review.scss
  base_tier_validation/static/src/scss/systray.scss
  base_tier_validation/static/src/xml/systray.xml
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/tests/__init__.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation/views/assets_backend.xml
  base_tier_validation/views/tier_definition_view.xml
  base_tier_validation/views/tier_review_view.xml
  base_tier_validation/wizard/__init__.py
  base_tier_validation/wizard/comment_wizard.py
  base_tier_validation/wizard/comment_wizard_view.xml
  setup/base_tier_validation/odoo/addons/base_tier_validation
  setup/base_tier_validation/setup.py
Labels: approved, bot is merging ⏳

#242 [14.0][UPD] base_tier_validation: update readme
  base_tier_validation/README.rst
  base_tier_validation/readme/CONFIGURE.rst
  base_tier_validation/readme/DESCRIPTION.rst
  base_tier_validation/readme/HISTORY.rst
  base_tier_validation/static/description/index.html
Labels: bot is merging ⏳

#229 [MIG] base_technical_features: Migration to 14.0
  base_technical_features/README.rst
  base_technical_features/__init__.py
  base_technical_features/__manifest__.py
  base_technical_features/data/res_users.xml
  base_technical_features/i18n/am.po
  base_technical_features/i18n/ar.po
  base_technical_features/i18n/base_technical_features.pot
  base_technical_features/i18n/ca.po
  base_technical_features/i18n/da.po
  base_technical_features/i18n/de.po
  base_technical_features/i18n/el_GR.po
  base_technical_features/i18n/es.po
  base_technical_features/i18n/es_ES.po
  base_technical_features/i18n/es_MX.po
  base_technical_features/i18n/fi.po
  base_technical_features/i18n/fr.po
  base_technical_features/i18n/fr_CA.po
  base_technical_features/i18n/fr_CH.po
  base_technical_features/i18n/fr_FR.po
  base_technical_features/i18n/gl.po
  base_technical_features/i18n/hr.po
  base_technical_features/i18n/hr_HR.po
  base_technical_features/i18n/it.po
  base_technical_features/i18n/ja.po
  base_technical_features/i18n/nl.po
  base_technical_features/i18n/nl_NL.po
  base_technical_features/i18n/pt.po
  base_technical_features/i18n/pt_BR.po
  base_technical_features/i18n/pt_PT.po
  base_technical_features/i18n/ro.po
  base_technical_features/i18n/sl.po
  base_technical_features/i18n/tr.po
  base_technical_features/i18n/tr_TR.po
  base_technical_features/i18n/zh_CN.po
  base_technical_features/models/__init__.py
  base_technical_features/models/base.py
  base_technical_features/models/ir_ui_menu.py
  base_technical_features/models/res_users.py
  base_technical_features/readme/CONTRIBUTORS.rst
  base_technical_features/readme/DESCRIPTION.rst
  base_technical_features/readme/USAGE.rst
  base_technical_features/security/res_groups.xml
  base_technical_features/static/description/icon.png
  base_technical_features/static/description/index.html
  base_technical_features/static/description/user_preferences.png
  base_technical_features/tests/__init__.py
  base_technical_features/tests/test_base_technical_features.py
  base_technical_features/views/res_users.xml
Labels: approved, bot is merging ⏳, ready to merge

#220 [13.0][ADD] base_tier_validation_forward
  base_tier_validation_forward/__init__.py
  base_tier_validation_forward/__manifest__.py
  base_tier_validation_forward/data/mail_data.xml
  base_tier_validation_forward/hooks.py
  base_tier_validation_forward/models/__init__.py
  base_tier_validation_forward/models/tier_definition.py
  base_tier_validation_forward/models/tier_review.py
  base_tier_validation_forward/models/tier_validation.py
  base_tier_validation_forward/readme/CONFIGURE.rst
  base_tier_validation_forward/readme/CONTRIBUTORS.rst
  base_tier_validation_forward/readme/DESCRIPTION.rst
  base_tier_validation_forward/static/description/icon.png
  base_tier_validation_forward/static/description/index.html
  base_tier_validation_forward/static/src/xml/tier_review_template.xml
  base_tier_validation_forward/tests/__init__.py
  base_tier_validation_forward/tests/test_tier_validation.py
  base_tier_validation_forward/tests/tier_validation_tester.py
  base_tier_validation_forward/views/tier_definition_view.xml
  base_tier_validation_forward/wizard/__init__.py
  base_tier_validation_forward/wizard/comment_wizard.py
  base_tier_validation_forward/wizard/forward_wizard.py
  base_tier_validation_forward/wizard/forward_wizard_view.xml
  setup/base_tier_validation_forward/odoo/addons/base_tier_validation_forward
  setup/base_tier_validation_forward/setup.py
Labels: approved, bot is merging ⏳

#237 [12.0][MIG] mass_editing: Add apply domain option in lines
  mass_editing/models/mass_editing.py
  mass_editing/models/mass_editing_line.py
  mass_editing/readme/CONTRIBUTORS.rst
  mass_editing/readme/ROADMAP.rst
  mass_editing/views/mass_editing_view.xml
  mass_editing/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳

#244 [13.0][FIX] mass_editing: Add apply domain option in lines
  mass_editing/models/mass_editing.py
  mass_editing/models/mass_editing_line.py
  mass_editing/readme/CONTRIBUTORS.rst
  mass_editing/readme/ROADMAP.rst
  mass_editing/views/mass_editing_view.xml
  mass_editing/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳

#241 [14.0][MIG] base_tier_validation_formula
  base_tier_validation_formula/__init__.py
  base_tier_validation_formula/__manifest__.py
  base_tier_validation_formula/i18n/base_tier_validation_formula.pot
  base_tier_validation_formula/i18n/es.po
  base_tier_validation_formula/i18n/it.po
  base_tier_validation_formula/i18n/zh_CN.po
  base_tier_validation_formula/models/__init__.py
  base_tier_validation_formula/models/tier_definition.py
  base_tier_validation_formula/models/tier_review.py
  base_tier_validation_formula/models/tier_validation.py
  base_tier_validation_formula/readme/CONTRIBUTORS.rst
  base_tier_validation_formula/readme/DESCRIPTION.rst
  base_tier_validation_formula/readme/USAGE.rst
  base_tier_validation_formula/static/description/icon.png
  base_tier_validation_formula/static/description/index.html
  base_tier_validation_formula/tests/__init__.py
  base_tier_validation_formula/tests/common.py
  base_tier_validation_formula/tests/test_tier_validation.py
  base_tier_validation_formula/tests/tier_validation_tester.py
  base_tier_validation_formula/views/tier_definition_view.xml
  setup/base_tier_validation_formula/odoo/addons/base_tier_validation_formula
  setup/base_tier_validation_formula/setup.py
Labels: approved, bot is merging ⏳, ready to merge
