Repository OCA/server-ux, pull requests merged in 2020-03, with the labels that each got.

#131 [12.0][MIG] document_quick_access
  document_quick_access/README.rst
  document_quick_access/__init__.py
  document_quick_access/__manifest__.py
  document_quick_access/i18n/document_quick_access.pot
  document_quick_access/i18n/es.po
  document_quick_access/models/__init__.py
  document_quick_access/models/base.py
  document_quick_access/models/document_quick_access_rule.py
  document_quick_access/readme/CONFIGURE.rst
  document_quick_access/readme/CONTRIBUTORS.rst
  document_quick_access/readme/DESCRIPTION.rst
  document_quick_access/readme/ROADMAP.rst
  document_quick_access/readme/USAGE.rst
  document_quick_access/security/ir.model.access.csv
  document_quick_access/static/description/icon.png
  document_quick_access/static/description/index.html
  document_quick_access/static/src/js/document_quick_access_launcher.js
  document_quick_access/static/src/xml/document_quick_access_launcher.xml
  document_quick_access/tests/__init__.py
  document_quick_access/tests/test_document_quick_access.py
  document_quick_access/views/assets_backend.xml
  document_quick_access/views/document_quick_access_rule.xml
Labels: approved

#132 [13.0][IMP] base_tier_validation_formula
  base_tier_validation_formula/README.rst
  base_tier_validation_formula/models/tier_definition.py
  base_tier_validation_formula/models/tier_validation.py
  base_tier_validation_formula/readme/CONTRIBUTORS.rst
  base_tier_validation_formula/readme/USAGE.rst
  base_tier_validation_formula/static/description/index.html
  base_tier_validation_formula/tests/test_tier_validation.py
  base_tier_validation_formula/views/tier_definition_view.xml
Labels: approved, needs fixing, ready to merge

#133 [12.0][MIG] document_quick_access_folder_auto_classification
  .travis.yml
  document_quick_access/__manifest__.py
  document_quick_access_folder_auto_classification/README.rst
  document_quick_access_folder_auto_classification/__init__.py
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/data/config_parameter.xml
  document_quick_access_folder_auto_classification/data/cron_data.xml
  document_quick_access_folder_auto_classification/i18n/document_quick_access_folder_auto_classification.pot
  document_quick_access_folder_auto_classification/models/__init__.py
  document_quick_access_folder_auto_classification/models/document_quick_access_missing.py
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/models/ir_attachment.py
  document_quick_access_folder_auto_classification/readme/CONFIGURE.rst
  document_quick_access_folder_auto_classification/readme/CONTRIBUTORS.rst
  document_quick_access_folder_auto_classification/readme/DESCRIPTION.rst
  document_quick_access_folder_auto_classification/readme/USAGE.rst
  document_quick_access_folder_auto_classification/security/ir.model.access.csv
  document_quick_access_folder_auto_classification/security/security.xml
  document_quick_access_folder_auto_classification/static/description/icon.png
  document_quick_access_folder_auto_classification/static/description/icon.svg
  document_quick_access_folder_auto_classification/static/description/index.html
  document_quick_access_folder_auto_classification/tests/__init__.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
  document_quick_access_folder_auto_classification/tests/test_file.pdf
  document_quick_access_folder_auto_classification/views/document_quick_access_missing.xml
  document_quick_access_folder_auto_classification/wizards/__init__.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.xml
  oca_dependencies.txt
  requirements.txt
Labels: approved, ready to merge

#134 [13.0][MIG] barcode_action
  barcode_action/README.rst
  barcode_action/__init__.py
  barcode_action/__manifest__.py
  barcode_action/demo/barcode_action_demo.xml
  barcode_action/i18n/barcode_action.pot
  barcode_action/i18n/es.po
  barcode_action/i18n/hr.po
  barcode_action/i18n/pt.po
  barcode_action/i18n/zh_CN.po
  barcode_action/models/__init__.py
  barcode_action/models/res_partner.py
  barcode_action/readme/CONTRIBUTORS.rst
  barcode_action/readme/DESCRIPTION.rst
  barcode_action/readme/USAGE.rst
  barcode_action/static/description/icon.png
  barcode_action/static/description/index.html
  barcode_action/static/src/js/action_barcode_form.js
  barcode_action/static/src/js/action_barcode_widget.js
  barcode_action/tests/__init__.py
  barcode_action/tests/test_partner_find.py
  barcode_action/views/barcode_templates.xml
  barcode_action/wizard/__init__.py
  barcode_action/wizard/barcode_action.py
  barcode_action/wizard/barcode_action_view.xml
Labels: approved

#135 [13.0][MIG] document_quick_access
  document_quick_access/README.rst
  document_quick_access/__init__.py
  document_quick_access/__manifest__.py
  document_quick_access/i18n/document_quick_access.pot
  document_quick_access/i18n/es.po
  document_quick_access/models/__init__.py
  document_quick_access/models/base.py
  document_quick_access/models/document_quick_access_rule.py
  document_quick_access/readme/CONFIGURE.rst
  document_quick_access/readme/CONTRIBUTORS.rst
  document_quick_access/readme/DESCRIPTION.rst
  document_quick_access/readme/ROADMAP.rst
  document_quick_access/readme/USAGE.rst
  document_quick_access/security/ir.model.access.csv
  document_quick_access/static/description/icon.png
  document_quick_access/static/description/index.html
  document_quick_access/static/src/js/document_quick_access_launcher.js
  document_quick_access/static/src/xml/document_quick_access_launcher.xml
  document_quick_access/tests/__init__.py
  document_quick_access/tests/test_document_quick_access.py
  document_quick_access/views/assets_backend.xml
  document_quick_access/views/document_quick_access_rule.xml
  requirements.txt
Labels: approved

#138 [12.0][fix] base_tier_validation_formula: Add default
  base_tier_validation_formula/models/tier_definition.py
Labels: approved

#136 [13.0][MIG] document_quick_access_folder_auto_classification
  .isort.cfg
  .travis.yml
  document_quick_access_folder_auto_classification/README.rst
  document_quick_access_folder_auto_classification/__init__.py
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/data/config_parameter.xml
  document_quick_access_folder_auto_classification/data/cron_data.xml
  document_quick_access_folder_auto_classification/i18n/document_quick_access_folder_auto_classification.pot
  document_quick_access_folder_auto_classification/models/__init__.py
  document_quick_access_folder_auto_classification/models/document_quick_access_missing.py
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/models/ir_attachment.py
  document_quick_access_folder_auto_classification/readme/CONFIGURE.rst
  document_quick_access_folder_auto_classification/readme/CONTRIBUTORS.rst
  document_quick_access_folder_auto_classification/readme/DESCRIPTION.rst
  document_quick_access_folder_auto_classification/readme/USAGE.rst
  document_quick_access_folder_auto_classification/security/ir.model.access.csv
  document_quick_access_folder_auto_classification/security/security.xml
  document_quick_access_folder_auto_classification/static/description/icon.png
  document_quick_access_folder_auto_classification/static/description/icon.svg
  document_quick_access_folder_auto_classification/static/description/index.html
  document_quick_access_folder_auto_classification/tests/__init__.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
  document_quick_access_folder_auto_classification/tests/test_file.pdf
  document_quick_access_folder_auto_classification/views/document_quick_access_missing.xml
  document_quick_access_folder_auto_classification/wizards/__init__.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.xml
  oca_dependencies.txt
Labels: approved, ready to merge

#139 [12.0][FIX] base_tier_validation: Unlink reviews when unlink a record
  base_tier_validation/__manifest__.py
  base_tier_validation/models/tier_validation.py
Labels: approved

#144 [13.0][FIX] mass_editing: allow change readonly fields.
  mass_editing/models/mass_editing_line.py
Labels: approved

#141 [13.0][FIX] base_tier_validation: Unlink reviews when unlink a validation record
  base_tier_validation/models/tier_validation.py
Labels: approved, ready to merge

#149 [IMP] add security groups to mass editing action
  mass_editing/models/mass_object.py
  mass_editing/views/mass_editing_view.xml
Labels: bot is merging ⏳
