Repository OCA/server-ux, pull requests merged in 2021-11, with the labels that each got.

#391 [MIG] 15.0 base_technical_features
  base_technical_features/README.rst
  base_technical_features/__init__.py
  base_technical_features/__manifest__.py
  base_technical_features/data/res_users.xml
  base_technical_features/i18n/am.po
  base_technical_features/i18n/ar.po
  base_technical_features/i18n/base_technical_features.pot
  base_technical_features/i18n/ca.po
  base_technical_features/i18n/da.po
  base_technical_features/i18n/de.po
  base_technical_features/i18n/el_GR.po
  base_technical_features/i18n/es.po
  base_technical_features/i18n/es_ES.po
  base_technical_features/i18n/es_MX.po
  base_technical_features/i18n/fi.po
  base_technical_features/i18n/fr.po
  base_technical_features/i18n/fr_CA.po
  base_technical_features/i18n/fr_CH.po
  base_technical_features/i18n/fr_FR.po
  base_technical_features/i18n/gl.po
  base_technical_features/i18n/hr.po
  base_technical_features/i18n/hr_HR.po
  base_technical_features/i18n/it.po
  base_technical_features/i18n/ja.po
  base_technical_features/i18n/nl.po
  base_technical_features/i18n/nl_NL.po
  base_technical_features/i18n/pt.po
  base_technical_features/i18n/pt_BR.po
  base_technical_features/i18n/pt_PT.po
  base_technical_features/i18n/ro.po
  base_technical_features/i18n/sl.po
  base_technical_features/i18n/tr.po
  base_technical_features/i18n/tr_TR.po
  base_technical_features/i18n/zh_CN.po
  base_technical_features/models/__init__.py
  base_technical_features/models/base.py
  base_technical_features/models/ir_ui_menu.py
  base_technical_features/models/res_users.py
  base_technical_features/readme/CONTRIBUTORS.rst
  base_technical_features/readme/DESCRIPTION.rst
  base_technical_features/readme/USAGE.rst
  base_technical_features/security/res_groups.xml
  base_technical_features/static/description/icon.png
  base_technical_features/static/description/index.html
  base_technical_features/static/description/user_preferences.png
  base_technical_features/tests/__init__.py
  base_technical_features/tests/test_base_technical_features.py
  base_technical_features/views/res_users.xml
  setup/base_technical_features/odoo/addons/base_technical_features
  setup/base_technical_features/setup.py
Labels: bot is merging ⏳

#398 [12.0][FIX] base_tier_validation: External users receive internal mails
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#378 [14.0][IMP] base_tier_validation, add tier description on stripe
  base_tier_validation/models/tier_validation.py
  base_tier_validation/templates/tier_validation_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#323 [REF] document_quick_access_folder_auto_classification:
  document_quick_access_folder_auto_classification/__init__.py
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/components/__init__.py
  document_quick_access_folder_auto_classification/components/document_quick_access_process.py
  document_quick_access_folder_auto_classification/data/config_parameter.xml
  document_quick_access_folder_auto_classification/data/edi_data.xml
  document_quick_access_folder_auto_classification/migrations/13.0.1.0.1/post-migration.py
  document_quick_access_folder_auto_classification/migrations/13.0.1.0.1/pre-migration.py
  document_quick_access_folder_auto_classification/models/__init__.py
  document_quick_access_folder_auto_classification/models/document_quick_access_missing.py
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/models/ir_attachment.py
  document_quick_access_folder_auto_classification/readme/CONFIGURE.rst
  document_quick_access_folder_auto_classification/readme/DESCRIPTION.rst
  document_quick_access_folder_auto_classification/security/ir.model.access.csv
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
  document_quick_access_folder_auto_classification/views/edi_exchange_record.xml
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.xml
  oca_dependencies.txt
Labels: approved, work in progress, ready to merge, bot is merging ⏳

#405 [14.0][ENH] base_tier_validation, add configuration
  base_tier_validation/__manifest__.py
  base_tier_validation/models/__init__.py
  base_tier_validation/models/res_config_settings.py
  base_tier_validation/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#408 [13.0][FIX] document_quick_access_folder_auto_classification: fix tests, create base_dir if not existing.
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
Labels: bot is merging ⏳

#403 [13.0][IMP] base_tier_validation*: Backport of commits from version 14.0 to 13.0
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONFIGURE.rst
  base_tier_validation/readme/DESCRIPTION.rst
  base_tier_validation/readme/HISTORY.rst
  base_tier_validation/readme/ROADMAP.rst
  base_tier_validation/static/description/index.html
  base_tier_validation/templates/tier_validation_templates.xml
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation/views/tier_definition_view.xml
  base_tier_validation_formula/tests/__init__.py
  base_tier_validation_formula/tests/common.py
  base_tier_validation_formula/tests/test_tier_validation.py
  base_tier_validation_formula/tests/tier_validation_tester.py
  base_tier_validation_forward/tests/test_tier_validation.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#349 [14.0][IMP] date_range: fully automatic generation from date range types
  date_range/README.rst
  date_range/__manifest__.py
  date_range/data/ir_cron_data.xml
  date_range/models/date_range_type.py
  date_range/readme/CONTRIBUTORS.rst
  date_range/readme/USAGE.rst
  date_range/static/description/date_range_create.png
  date_range/static/description/date_range_type_autogeneration.png
  date_range/static/description/date_range_type_create.png
  date_range/static/description/date_range_wizard.png
  date_range/static/description/date_range_wizard_result.png
  date_range/static/description/index.html
  date_range/tests/test_date_range_generator.py
  date_range/tests/test_date_range_type.py
  date_range/views/date_range_view.xml
  date_range/wizard/date_range_generator.py
  date_range/wizard/date_range_generator.xml
Labels: approved, ready to merge, bot is merging ⏳

#361 [14.0][ADD] sequence_range_end
  sequence_range_end/__init__.py
  sequence_range_end/__manifest__.py
  sequence_range_end/models/__init__.py
  sequence_range_end/models/ir_sequence.py
  sequence_range_end/readme/CONTRIBUTORS.rst
  sequence_range_end/readme/DESCRIPTION.rst
  sequence_range_end/static/description/icon.png
  sequence_range_end/tests/__init__.py
  sequence_range_end/tests/test_sequence_range_end.py
  sequence_range_end/views/sequence_views.xml
  setup/sequence_range_end/odoo/addons/sequence_range_end
  setup/sequence_range_end/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#411 [14.0][FWD] base_technical_features: Forward updates from 13.0
  base_technical_features/models/res_users.py
Labels: bot is merging ⏳

#406 [13.0][FIX] mass_operation_abstract: change translations variables formatting
  mass_operation_abstract/i18n/de.po
  mass_operation_abstract/models/mass_operation_mixin.py
  mass_operation_abstract/wizard/mass_operation_wizard_mixin.py
Labels: approved, bot is merging ⏳
