Repository OCA/server-ux, pull requests merged in 2021-03, with the labels that each got.

#296 [13.0][IMP] base_tier_validation: improve error message.
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#295 [14.0][mig] barcode_action
  barcode_action/README.rst
  barcode_action/__init__.py
  barcode_action/__manifest__.py
  barcode_action/demo/barcode_action_demo.xml
  barcode_action/i18n/barcode_action.pot
  barcode_action/i18n/es.po
  barcode_action/i18n/hr.po
  barcode_action/i18n/pt.po
  barcode_action/i18n/zh_CN.po
  barcode_action/models/__init__.py
  barcode_action/models/res_partner.py
  barcode_action/readme/CONTRIBUTORS.rst
  barcode_action/readme/DESCRIPTION.rst
  barcode_action/readme/USAGE.rst
  barcode_action/security/ir.model.access.csv
  barcode_action/static/description/icon.png
  barcode_action/static/description/index.html
  barcode_action/static/src/js/action_barcode_form.js
  barcode_action/static/src/js/action_barcode_widget.js
  barcode_action/tests/__init__.py
  barcode_action/tests/test_partner_find.py
  barcode_action/views/barcode_templates.xml
  barcode_action/wizard/__init__.py
  barcode_action/wizard/barcode_action.py
  barcode_action/wizard/barcode_action_view.xml
  setup/barcode_action/odoo/addons/barcode_action
  setup/barcode_action/setup.py
Labels: approved, bot is merging ⏳

#246 [14.0][ADD] base_revision
  base_revision/__init__.py
  base_revision/__manifest__.py
  base_revision/models/__init__.py
  base_revision/models/base_revision.py
  base_revision/readme/CONTRIBUTORS.rst
  base_revision/readme/DESCRIPTION.rst
  base_revision/static/description/icon.png
  base_revision/static/description/index.html
  base_revision/tests/__init__.py
  base_revision/tests/base_revision_tester.py
  base_revision/tests/test_base_revision.py
  setup/base_revision/odoo/addons/base_revision
  setup/base_revision/setup.py
Labels: approved, bot is merging ⏳

#299 [14.0][mig] default_multi_user
  default_multi_user/README.rst
  default_multi_user/__init__.py
  default_multi_user/__manifest__.py
  default_multi_user/hooks.py
  default_multi_user/i18n/default_multi_user.pot
  default_multi_user/models/__init__.py
  default_multi_user/models/ir_default.py
  default_multi_user/readme/CONFIGURE.rst
  default_multi_user/readme/CONTRIBUTORS.rst
  default_multi_user/readme/DESCRIPTION.rst
  default_multi_user/static/description/icon.png
  default_multi_user/static/description/index.html
  default_multi_user/tests/__init__.py
  default_multi_user/tests/test_default_multi_user.py
  default_multi_user/views/ir_default_view.xml
  setup/default_multi_user/odoo/addons/default_multi_user
  setup/default_multi_user/setup.py
Labels: approved, bot is merging ⏳

#301 [14.0] [mig] document_quick_access
  document_quick_access/README.rst
  document_quick_access/__init__.py
  document_quick_access/__manifest__.py
  document_quick_access/i18n/document_quick_access.pot
  document_quick_access/i18n/es.po
  document_quick_access/models/__init__.py
  document_quick_access/models/base.py
  document_quick_access/models/document_quick_access_rule.py
  document_quick_access/readme/CONFIGURE.rst
  document_quick_access/readme/CONTRIBUTORS.rst
  document_quick_access/readme/DESCRIPTION.rst
  document_quick_access/readme/ROADMAP.rst
  document_quick_access/readme/USAGE.rst
  document_quick_access/security/ir.model.access.csv
  document_quick_access/static/description/icon.png
  document_quick_access/static/description/index.html
  document_quick_access/static/src/js/document_quick_access_launcher.js
  document_quick_access/static/src/xml/document_quick_access_launcher.xml
  document_quick_access/tests/__init__.py
  document_quick_access/tests/test_document_quick_access.py
  document_quick_access/views/assets_backend.xml
  document_quick_access/views/document_quick_access_rule.xml
  requirements.txt
  setup/document_quick_access/odoo/addons/document_quick_access
  setup/document_quick_access/setup.py
Labels: approved, bot is merging ⏳

#309 [13.0][FIX] base_tier_validation: correct fusion of domains
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#311 [FW] 14.0 mass_editing: Allow to override field options
  mass_editing/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳

#304 [14.0] [mig] sequence_reset_period
  sequence_reset_period/README.rst
  sequence_reset_period/__init__.py
  sequence_reset_period/__manifest__.py
  sequence_reset_period/i18n/es.po
  sequence_reset_period/i18n/hr.po
  sequence_reset_period/i18n/sequence_reset_period.pot
  sequence_reset_period/i18n/zh_CN.po
  sequence_reset_period/models/__init__.py
  sequence_reset_period/models/ir_sequence.py
  sequence_reset_period/readme/CONTRIBUTORS.rst
  sequence_reset_period/readme/DESCRIPTION.rst
  sequence_reset_period/readme/USAGE.rst
  sequence_reset_period/static/description/icon.png
  sequence_reset_period/static/description/index.html
  sequence_reset_period/tests/__init__.py
  sequence_reset_period/tests/test_period.py
  sequence_reset_period/views/sequence_views.xml
  setup/sequence_reset_period/odoo/addons/sequence_reset_period
  setup/sequence_reset_period/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#314 [14.0][FIX] date_range: Refactor component with Owl framework
  date_range/static/src/js/date_range.js
  date_range/static/src/xml/date_range.xml
Labels: approved, bot is merging ⏳

#297 [14.0][ADD] base_cancel_confirm
  base_cancel_confirm/__init__.py
  base_cancel_confirm/__manifest__.py
  base_cancel_confirm/model/__init__.py
  base_cancel_confirm/model/base_cancel_confirm.py
  base_cancel_confirm/readme/CONTRIBUTORS.rst
  base_cancel_confirm/readme/DESCRIPTION.rst
  base_cancel_confirm/security/ir.model.access.csv
  base_cancel_confirm/static/description/icon.png
  base_cancel_confirm/static/description/index.html
  base_cancel_confirm/templates/cancel_confirm_template.xml
  base_cancel_confirm/tests/__init__.py
  base_cancel_confirm/tests/cancel_confirm_tester.py
  base_cancel_confirm/tests/test_cancel_confirm.py
  base_cancel_confirm/wizard/__init__.py
  base_cancel_confirm/wizard/cancel_confirm.py
  base_cancel_confirm/wizard/cancel_confirm.xml
  setup/base_cancel_confirm/odoo/addons/base_cancel_confirm
  setup/base_cancel_confirm/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#321 [14.0][FIX] base_export_manager: fix _compute_label not setting a value
  base_export_manager/models/ir_exports_line.py
Labels: bot is merging ⏳
