Repository OCA/server-ux, pull requests merged in 2021-07, with the labels that each got.

#354 [12.0] FIX date_range Expected singleton while using advanced filter
  date_range/static/src/js/date_range.js
Labels: approved, bot is merging ⏳, ready to merge

#351 [14.0][MIG] base_import_security_group
  base_import_security_group/README.rst
  base_import_security_group/__init__.py
  base_import_security_group/__manifest__.py
  base_import_security_group/demo/assets.xml
  base_import_security_group/i18n/base_import_security_group.pot
  base_import_security_group/i18n/ca.po
  base_import_security_group/i18n/de.po
  base_import_security_group/i18n/es.po
  base_import_security_group/i18n/fr.po
  base_import_security_group/i18n/gl.po
  base_import_security_group/i18n/hr.po
  base_import_security_group/i18n/it.po
  base_import_security_group/i18n/pt.po
  base_import_security_group/i18n/sk.po
  base_import_security_group/models/__init__.py
  base_import_security_group/models/base.py
  base_import_security_group/models/ir_http.py
  base_import_security_group/readme/CONTRIBUTORS.rst
  base_import_security_group/readme/DESCRIPTION.rst
  base_import_security_group/security/base_import_security_group_security.xml
  base_import_security_group/static/description/icon.png
  base_import_security_group/static/description/icon.svg
  base_import_security_group/static/description/index.html
  base_import_security_group/static/src/js/import.js
  base_import_security_group/static/src/js/tour_import.js
  base_import_security_group/tests/__init__.py
  base_import_security_group/tests/test_base_import_security_group.py
  base_import_security_group/views/base_import.xml
  setup/base_import_security_group/odoo/addons/base_import_security_group
  setup/base_import_security_group/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#335 [12.0][IMP] date_range: add a search mixin class
  date_range/README.rst
  date_range/models/__init__.py
  date_range/models/date_range_search_mixin.py
  date_range/readme/CONFIGURE.rst
  date_range/readme/CONTRIBUTORS.rst
  date_range/readme/DESCRIPTION.rst
  date_range/static/description/date_range_many2one_search_field.png
  date_range/static/description/index.html
  date_range/tests/__init__.py
  date_range/tests/models.py
  date_range/tests/test_date_range_search_mixin.py
  test-requirements.txt
Labels: approved, bot is merging ⏳, question, ready to merge

#362 [13.0][base_tier_validation][fix] avoid singleton error
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#363 [12.0][FIX] date_range: fix super calls on fields_view_get()
  date_range/models/date_range_search_mixin.py
Labels: approved, bot is merging ⏳

#365 [12.0][FIX] date_range: Add comment to missing dependency for odoo_test_helper
  date_range/__manifest__.py
Labels: approved, bot is merging ⏳, ready to merge

#325 [12.0][IMP] base_tier_validation: add details to error message
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#293 [14.0] [mig] chained_swapper
  chained_swapper/README.rst
  chained_swapper/__init__.py
  chained_swapper/__manifest__.py
  chained_swapper/demo/chained_swapper_demo.xml
  chained_swapper/hooks.py
  chained_swapper/i18n/chained_swapper.pot
  chained_swapper/i18n/es.po
  chained_swapper/models/__init__.py
  chained_swapper/models/chained_swapper.py
  chained_swapper/readme/CONFIGURE.rst
  chained_swapper/readme/CONTRIBUTORS.rst
  chained_swapper/readme/DESCRIPTION.rst
  chained_swapper/readme/USAGE.rst
  chained_swapper/security/ir.model.access.csv
  chained_swapper/static/description/icon.png
  chained_swapper/static/description/index.html
  chained_swapper/tests/__init__.py
  chained_swapper/tests/test_chained_swapper.py
  chained_swapper/views/chained_swapper_views.xml
  chained_swapper/wizard/__init__.py
  chained_swapper/wizard/chained_swapper_wizard.py
  chained_swapper/wizard/chained_swapper_wizard_views.xml
  setup/chained_swapper/odoo/addons/chained_swapper
  setup/chained_swapper/setup.py
Labels: approved, bot is merging ⏳

#370 [14.0][FIX] base_tier_validation: avoid singleton error
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#359 [14.0][IMP] base_tier_validation, use sudo to post message
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#358 [14.0][IMP] base_tier_validation_server_action, use write to trigger action
  base_tier_validation_server_action/models/tier_review.py
Labels: approved, bot is merging ⏳, ready to merge

#367 [14.0][ENH] Add Notification message on restart tier
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#372 [12.0][IMP] base_tier_validation: add new review type
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: bot is merging ⏳

#371 [13.0][IMP] base_tier_validation: add new review type
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: bot is merging ⏳

#373 [14.0][IMP] base_tier_validation: add new review type
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: bot is merging ⏳
