Repository OCA/server-ux, pull requests merged in 2021-01, with the labels that each got.

#186 [13.0][MIG] sequence_check_digit
  sequence_check_digit/README.rst
  sequence_check_digit/__init__.py
  sequence_check_digit/__manifest__.py
  sequence_check_digit/i18n/es.po
  sequence_check_digit/i18n/sequence_check_digit.pot
  sequence_check_digit/models/__init__.py
  sequence_check_digit/models/ir_sequence.py
  sequence_check_digit/readme/CONTRIBUTORS.rst
  sequence_check_digit/readme/DESCRIPTION.rst
  sequence_check_digit/readme/USAGE.rst
  sequence_check_digit/static/description/icon.png
  sequence_check_digit/static/description/index.html
  sequence_check_digit/tests/__init__.py
  sequence_check_digit/tests/test_check_digit.py
  sequence_check_digit/views/sequence_views.xml
  setup/sequence_check_digit/odoo/addons/sequence_check_digit
  setup/sequence_check_digit/setup.py
Labels: approved, bot is merging ⏳

#259 [13.0][MIG] chained_swapper: Migration to 13.0
  chained_swapper/README.rst
  chained_swapper/__init__.py
  chained_swapper/__manifest__.py
  chained_swapper/demo/chained_swapper_demo.xml
  chained_swapper/hooks.py
  chained_swapper/i18n/chained_swapper.pot
  chained_swapper/i18n/es.po
  chained_swapper/models/__init__.py
  chained_swapper/models/chained_swapper.py
  chained_swapper/readme/CONFIGURE.rst
  chained_swapper/readme/CONTRIBUTORS.rst
  chained_swapper/readme/DESCRIPTION.rst
  chained_swapper/readme/USAGE.rst
  chained_swapper/security/ir.model.access.csv
  chained_swapper/static/description/icon.png
  chained_swapper/static/description/index.html
  chained_swapper/tests/__init__.py
  chained_swapper/tests/test_chained_swapper.py
  chained_swapper/views/chained_swapper_views.xml
  chained_swapper/wizard/__init__.py
  chained_swapper/wizard/chained_swapper_wizard.py
  chained_swapper/wizard/chained_swapper_wizard_views.xml
  setup/chained_swapper/odoo/addons/chained_swapper
  setup/chained_swapper/setup.py
Labels: bot is merging ⏳

#247 [12.0] base_tier_validation - Add security rule for multi-company environments
  base_tier_validation/__manifest__.py
  base_tier_validation/security/tier_validation_security.xml
Labels: approved, bot is merging ⏳, ready to merge

#267 [14.0][FIX] tier_validation: Fix views from template as state was not used
  base_tier_validation/models/tier_validation.py
  base_tier_validation/templates/tier_validation_templates.xml
Labels: approved, bot is merging ⏳
