Repository OCA/server-ux, pull requests merged in 2021-02, with the labels that each got.

#271 [14.0][FIX] base_tier_validation_forward, inverse value of related field cause wrong desc in tier.review.
  base_tier_validation_forward/models/tier_review.py
  base_tier_validation_forward/wizard/forward_wizard.py
Labels: bot is merging ⏳

#278 [13.0][FIX] base_search_custom_field_filter: Don't work if search view don't have a field filter
  base_search_custom_field_filter/models/base.py
Labels: approved, bot is merging ⏳

#277 [12.0][FIX] base_search_custom_field_filter: Don't work if search view don't have a field filter
  base_search_custom_field_filter/models/base.py
Labels: approved, bot is merging ⏳

#228 [14.0][ADD] base_tier_validation_server_action
  base_tier_validation_server_action/__init__.py
  base_tier_validation_server_action/__manifest__.py
  base_tier_validation_server_action/data/cron_data.xml
  base_tier_validation_server_action/models/__init__.py
  base_tier_validation_server_action/models/tier_definition.py
  base_tier_validation_server_action/models/tier_review.py
  base_tier_validation_server_action/readme/CONFIGURE.rst
  base_tier_validation_server_action/readme/CONTRIBUTORS.rst
  base_tier_validation_server_action/readme/DESCRIPTION.rst
  base_tier_validation_server_action/static/description/icon.png
  base_tier_validation_server_action/tests/__init__.py
  base_tier_validation_server_action/tests/test_tier_validation.py
  base_tier_validation_server_action/tests/tier_validation_tester.py
  base_tier_validation_server_action/views/tier_definition_view.xml
  setup/base_tier_validation_server_action/odoo/addons/base_tier_validation_server_action
  setup/base_tier_validation_server_action/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#258 [MIG] 14.0 base search custom field filter
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/i18n/base_search_custom_field_filter.pot
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/readme/CONFIGURE.rst
  base_search_custom_field_filter/readme/CONTRIBUTORS.rst
  base_search_custom_field_filter/readme/DESCRIPTION.rst
  base_search_custom_field_filter/readme/USAGE.rst
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/icon.png
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/static/src/js/search_bar_autocomplete_sources.js
  base_search_custom_field_filter/templates/assets.xml
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
  setup/base_search_custom_field_filter/odoo/addons/base_search_custom_field_filter
  setup/base_search_custom_field_filter/setup.py
Labels: approved, bot is merging ⏳

#283 [14.0][FIX] base_tier_validation, access_token as exception field
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#281 [12.0][FIX] base_tier_validation, access_token as exception field
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#282 [13.0][FIX] base_tier_validation, access_token as exception field
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#274 [14.0][MIG] filter_multi_user: Migration to 14.0
  filter_multi_user/README.rst
  filter_multi_user/__init__.py
  filter_multi_user/__manifest__.py
  filter_multi_user/i18n/filter_multi_user.pot
  filter_multi_user/models/__init__.py
  filter_multi_user/models/ir_filters.py
  filter_multi_user/readme/CONFIGURE.rst
  filter_multi_user/readme/CONTRIBUTORS.rst
  filter_multi_user/readme/DESCRIPTION.rst
  filter_multi_user/security/ir_filters_security.xml
  filter_multi_user/static/description/icon.png
  filter_multi_user/static/description/index.html
  filter_multi_user/tests/__init__.py
  filter_multi_user/tests/test_filter_multi_user.py
  filter_multi_user/views/ir_filters_view.xml
  setup/filter_multi_user/odoo/addons/filter_multi_user
  setup/filter_multi_user/setup.py
Labels: bot is merging ⏳

#280 [14.0][IMP] base_tier_validation_server_action, add server action on rejection
  base_tier_validation_server_action/models/tier_definition.py
  base_tier_validation_server_action/models/tier_review.py
  base_tier_validation_server_action/readme/CONFIGURE.rst
  base_tier_validation_server_action/readme/DESCRIPTION.rst
  base_tier_validation_server_action/tests/test_tier_validation.py
  base_tier_validation_server_action/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#275 [14.0][IMP] base_tier_validation, add 'Todo by' column in review table
  base_tier_validation/models/tier_review.py
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/views/tier_review_view.xml
Labels: approved, bot is merging ⏳

#273 [14.0][FIX] base_tier_validation, improve accuracy of systray on case approve_sequence
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
Labels: approved, bot is merging ⏳

#285 [13.0] [IMP] base_technical_features: use has_group instead of loading all users
  base_technical_features/models/res_users.py
Labels: approved, bot is merging ⏳

#287 [13.0][FIX] base_tier_validation, improve accuracy of systray on case approve_sequence
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
Labels: bot is merging ⏳

#286 [12.0][FIX] base_tier_validation, improve accuracy of systray on case approve_sequence
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
Labels: bot is merging ⏳

#291 [13.0][IMP] base_tier_validation, add 'Todo by' column in review table
  base_tier_validation/models/tier_review.py
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/views/tier_review_view.xml
Labels: bot is merging ⏳

#170 [10.0][BCK] base_search_custom_field_filter
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/i18n/base_search_custom_field_filter.pot
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/readme/CONFIGURE.rst
  base_search_custom_field_filter/readme/CONTRIBUTORS.rst
  base_search_custom_field_filter/readme/DESCRIPTION.rst
  base_search_custom_field_filter/readme/USAGE.rst
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/icon.png
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/static/src/js/search_input.js
  base_search_custom_field_filter/templates/assets.xml
  base_search_custom_field_filter/tests/__init__.py
  base_search_custom_field_filter/tests/test_search_custom_field.py
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
  setup/base_search_custom_field_filter/odoo/__init__.py
  setup/base_search_custom_field_filter/odoo/addons/__init__.py
  setup/base_search_custom_field_filter/odoo/addons/base_search_custom_field_filter
  setup/base_search_custom_field_filter/setup.py
Labels: approved, bot is merging ⏳, ready to merge
