Repository OCA/server-ux, pull requests merged in 2021-05, with the labels that each got.

#199 [13.0][MIG] base_substate
  base_substate/__init__.py
  base_substate/__manifest__.py
  base_substate/i18n/base_substate.pot
  base_substate/models/__init__.py
  base_substate/models/base_substate.py
  base_substate/models/base_substate_mixin.py
  base_substate/readme/CONTRIBUTORS.rst
  base_substate/readme/DESCRIPTION.rst
  base_substate/readme/USAGE.rst
  base_substate/security/base_substate_security.xml
  base_substate/security/ir.model.access.csv
  base_substate/static/description/icon.png
  base_substate/static/description/index.html
  base_substate/tests/__init__.py
  base_substate/tests/models_mixin.py
  base_substate/tests/sale_test.py
  base_substate/tests/test_base_substate.py
  base_substate/views/base_substate_type_views.xml
  base_substate/views/base_substate_value_views.xml
  base_substate/views/base_substate_views.xml
  setup/base_substate/odoo/addons/base_substate
  setup/base_substate/setup.py
Labels: approved, bot is merging ⏳

#261 [12.0] Mass editing does not work correctly with one2many fields
  mass_editing/i18n/es.po
  mass_editing/i18n/mass_editing.pot
  mass_editing/tests/test_mass_editing.py
  mass_editing/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳

#315 [14.0] [mig] sequence_check_digit
  requirements.txt
  sequence_check_digit/README.rst
  sequence_check_digit/__init__.py
  sequence_check_digit/__manifest__.py
  sequence_check_digit/i18n/es.po
  sequence_check_digit/i18n/sequence_check_digit.pot
  sequence_check_digit/models/__init__.py
  sequence_check_digit/models/ir_sequence.py
  sequence_check_digit/readme/CONTRIBUTORS.rst
  sequence_check_digit/readme/DESCRIPTION.rst
  sequence_check_digit/readme/USAGE.rst
  sequence_check_digit/static/description/icon.png
  sequence_check_digit/static/description/index.html
  sequence_check_digit/tests/__init__.py
  sequence_check_digit/tests/test_check_digit.py
  sequence_check_digit/views/sequence_views.xml
  setup/sequence_check_digit/odoo/addons/sequence_check_digit
  setup/sequence_check_digit/setup.py
Labels: approved, bot is merging ⏳

#337 [13.0][MIG] base_user_locale
  base_user_locale/README.rst
  base_user_locale/__init__.py
  base_user_locale/__manifest__.py
  base_user_locale/controllers/__init__.py
  base_user_locale/controllers/web_client.py
  base_user_locale/i18n/base_user_locale.pot
  base_user_locale/models/__init__.py
  base_user_locale/models/calendar_event.py
  base_user_locale/models/res_company.py
  base_user_locale/models/res_config_settings.py
  base_user_locale/models/res_users.py
  base_user_locale/readme/CONTRIBUTORS.rst
  base_user_locale/readme/DESCRIPTION.rst
  base_user_locale/readme/USAGE.rst
  base_user_locale/static/description/icon.png
  base_user_locale/static/description/index.html
  base_user_locale/tests/__init__.py
  base_user_locale/tests/test_base_user_locale.py
  base_user_locale/views/res_config_settings.xml
  base_user_locale/views/res_users.xml
  setup/base_user_locale/odoo/addons/base_user_locale
  setup/base_user_locale/setup.py
Labels: approved, bot is merging ⏳

#334 [14.0][FIX] base_cancel_confirm, access window action error
  base_cancel_confirm/model/base_cancel_confirm.py
Labels: bot is merging ⏳

#341 [12.0][FIX] base_import_security_group: test with tour
  base_import_security_group/__manifest__.py
  base_import_security_group/demo/assets.xml
  base_import_security_group/readme/CONTRIBUTORS.rst
  base_import_security_group/static/src/js/import.js
  base_import_security_group/static/src/js/tour_import.js
  base_import_security_group/tests/test_base_import_security_group.py
Labels: approved, bot is merging ⏳, ready to merge

#343 [13.0][IMP] base_tier_validation: Remove tier review when model state goes to cancel
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#340 [13.0][FIX] base_substate: Fix archived button
  base_substate/views/base_substate_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#339 [FIX] base_revision: auto_search and no_destroy are no longer valid attributes
  base_revision/models/base_revision.py
Labels: bot is merging ⏳

#344 [14.0][FIX] base_cancel_confirm: No duplicate cancel confirm and cancel reason
  base_cancel_confirm/model/base_cancel_confirm.py
Labels: bot is merging ⏳
