Repository OCA/server-ux, pull requests merged in 2021-04, with the labels that each got.

#303 [14.0] [mig] multi_step_wizard
  multi_step_wizard/README.rst
  multi_step_wizard/__init__.py
  multi_step_wizard/__manifest__.py
  multi_step_wizard/i18n/hr.po
  multi_step_wizard/i18n/multi_step_wizard.pot
  multi_step_wizard/i18n/nl.po
  multi_step_wizard/i18n/zh_CN.po
  multi_step_wizard/models/__init__.py
  multi_step_wizard/models/multi_step_wizard.py
  multi_step_wizard/readme/CONTRIBUTORS.rst
  multi_step_wizard/readme/DESCRIPTION.rst
  multi_step_wizard/readme/USAGE.rst
  multi_step_wizard/static/description/icon.png
  multi_step_wizard/static/description/index.html
  multi_step_wizard/tests/__init__.py
  multi_step_wizard/tests/common.py
  multi_step_wizard/tests/multi_step_wizard_test.py
  multi_step_wizard/tests/test_multi_step_wizard.py
  multi_step_wizard/views/multi_step_wizard_views.xml
  setup/multi_step_wizard/odoo/addons/multi_step_wizard
  setup/multi_step_wizard/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#322 [12.0][IMP] base_tier_validation: display reviewer in Reviews Table
  base_tier_validation/models/tier_review.py
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/views/tier_review_view.xml
Labels: approved, bot is merging ⏳

#264 [14.0][MIG] base_menu_visibility_restriction
  base_menu_visibility_restriction/README.rst
  base_menu_visibility_restriction/__init__.py
  base_menu_visibility_restriction/__manifest__.py
  base_menu_visibility_restriction/demo/ir_ui_menu.xml
  base_menu_visibility_restriction/demo/res_group.xml
  base_menu_visibility_restriction/i18n/base_menu_visibility_restriction.pot
  base_menu_visibility_restriction/models/__init__.py
  base_menu_visibility_restriction/models/ir_ui_menu.py
  base_menu_visibility_restriction/readme/CONTRIBUTORS.rst
  base_menu_visibility_restriction/readme/DESCRIPTION.rst
  base_menu_visibility_restriction/readme/USAGE.rst
  base_menu_visibility_restriction/static/description/icon.png
  base_menu_visibility_restriction/static/description/index.html
  base_menu_visibility_restriction/tests/__init__.py
  base_menu_visibility_restriction/tests/test_ir_ui_menu.py
  base_menu_visibility_restriction/views/ir_ui_menu.xml
  setup/base_menu_visibility_restriction/odoo/addons/base_menu_visibility_restriction
  setup/base_menu_visibility_restriction/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#326 [FIX] date_range: typo in field keyword argument
  date_range/wizard/date_range_generator.py
Labels: bot is merging ⏳

#327 [FIX] date_range: typo in field keyword argument
  date_range/wizard/date_range_generator.py
Labels: bot is merging ⏳

#329 [FIX] date_range: make the range selector work
  date_range/static/src/js/date_range.js
Labels: bot is merging ⏳

#331 [13.0][IMP] base_tier_validation: support to search for records where validation has not yet started
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#330 [FIX] base_tier_validation: External users receive the internal notifications from requested tier validations
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_validation.py
Labels: approved, merged 🎉

#332 [14.0][IMP] base_tier_validation: support to search for records where valid…
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
Labels: bot is merging ⏳

#333 [14.0][FIX] base_tier_validation: External users receive the internal notifications from requested tier validations
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#312 [14.0][MIG] base_optional_quick_create
  base_optional_quick_create/README.rst
  base_optional_quick_create/__init__.py
  base_optional_quick_create/__manifest__.py
  base_optional_quick_create/i18n/base_optional_quick_create.pot
  base_optional_quick_create/i18n/de.po
  base_optional_quick_create/i18n/es.po
  base_optional_quick_create/i18n/fi.po
  base_optional_quick_create/i18n/fr.po
  base_optional_quick_create/i18n/hr.po
  base_optional_quick_create/i18n/hr_HR.po
  base_optional_quick_create/i18n/it.po
  base_optional_quick_create/i18n/nb_NO.po
  base_optional_quick_create/i18n/pt_BR.po
  base_optional_quick_create/i18n/sl.po
  base_optional_quick_create/i18n/tr.po
  base_optional_quick_create/i18n/tr_TR.po
  base_optional_quick_create/i18n/zh_CN.po
  base_optional_quick_create/models/__init__.py
  base_optional_quick_create/models/ir_model.py
  base_optional_quick_create/readme/CONTRIBUTORS.rst
  base_optional_quick_create/readme/CREDITS.rst
  base_optional_quick_create/readme/DESCRIPTION.rst
  base_optional_quick_create/readme/USAGE.rst
  base_optional_quick_create/static/description/icon.png
  base_optional_quick_create/static/description/index.html
  base_optional_quick_create/tests/__init__.py
  base_optional_quick_create/tests/test_quick_create.py
  base_optional_quick_create/views/model_view.xml
  setup/base_optional_quick_create/odoo/addons/base_optional_quick_create
  setup/base_optional_quick_create/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#317 [IMP] date_range: Improve unit test not raising warning.
  date_range/tests/test_date_range.py
Labels: approved, bot is merging ⏳, ready to merge
