Repository OCA/server-ux, pull requests merged in 2022-10, with the labels that each got.

#432 [14.0][IMP] base_tier_validation_server_action: Promote to Beta
  base_tier_validation_server_action/__manifest__.py
Labels: bot is merging ⏳, stale

#399 [14.0][IMP] base_tier_validation, approve by sequence with option to bypass for same reviewer
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#501 [15.0][MIG] base_optional_quick_create
  base_optional_quick_create/README.rst
  base_optional_quick_create/__init__.py
  base_optional_quick_create/__manifest__.py
  base_optional_quick_create/i18n/base_optional_quick_create.pot
  base_optional_quick_create/i18n/de.po
  base_optional_quick_create/i18n/es.po
  base_optional_quick_create/i18n/fi.po
  base_optional_quick_create/i18n/fr.po
  base_optional_quick_create/i18n/hr.po
  base_optional_quick_create/i18n/hr_HR.po
  base_optional_quick_create/i18n/it.po
  base_optional_quick_create/i18n/nb_NO.po
  base_optional_quick_create/i18n/pt_BR.po
  base_optional_quick_create/i18n/sl.po
  base_optional_quick_create/i18n/tr.po
  base_optional_quick_create/i18n/tr_TR.po
  base_optional_quick_create/i18n/zh_CN.po
  base_optional_quick_create/models/__init__.py
  base_optional_quick_create/models/ir_model.py
  base_optional_quick_create/readme/CONTRIBUTORS.rst
  base_optional_quick_create/readme/CREDITS.rst
  base_optional_quick_create/readme/DESCRIPTION.rst
  base_optional_quick_create/readme/USAGE.rst
  base_optional_quick_create/static/description/icon.png
  base_optional_quick_create/static/description/index.html
  base_optional_quick_create/tests/__init__.py
  base_optional_quick_create/tests/test_quick_create.py
  base_optional_quick_create/views/model_view.xml
  setup/base_optional_quick_create/odoo/addons/base_optional_quick_create
  setup/base_optional_quick_create/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
