Repository OCA/server-ux, pull requests merged in 2022-11, with the labels that each got.

#547 [12.0][BP] base_tier_validation: correct fusion of domains
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#548 [12.0][FIX] base_tier_validation: Ignore active_test coming from upstream methods
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#543 [12.0][FIX] base_tier_validation: port from #273
  base_tier_validation/static/src/js/systray.js
Labels: approved, ready to merge, bot is merging ⏳

#302 [13.0][MIG] base_optional_quick_create
  base_optional_quick_create/README.rst
  base_optional_quick_create/__init__.py
  base_optional_quick_create/__manifest__.py
  base_optional_quick_create/i18n/base_optional_quick_create.pot
  base_optional_quick_create/i18n/de.po
  base_optional_quick_create/i18n/es.po
  base_optional_quick_create/i18n/fi.po
  base_optional_quick_create/i18n/fr.po
  base_optional_quick_create/i18n/hr.po
  base_optional_quick_create/i18n/hr_HR.po
  base_optional_quick_create/i18n/it.po
  base_optional_quick_create/i18n/nb_NO.po
  base_optional_quick_create/i18n/pt_BR.po
  base_optional_quick_create/i18n/sl.po
  base_optional_quick_create/i18n/tr.po
  base_optional_quick_create/i18n/tr_TR.po
  base_optional_quick_create/i18n/zh_CN.po
  base_optional_quick_create/models/__init__.py
  base_optional_quick_create/models/ir_model.py
  base_optional_quick_create/readme/CONTRIBUTORS.rst
  base_optional_quick_create/readme/CREDITS.rst
  base_optional_quick_create/readme/DESCRIPTION.rst
  base_optional_quick_create/readme/USAGE.rst
  base_optional_quick_create/static/description/icon.png
  base_optional_quick_create/static/description/index.html
  base_optional_quick_create/tests/__init__.py
  base_optional_quick_create/tests/test_quick_create.py
  base_optional_quick_create/views/model_view.xml
  setup/base_optional_quick_create/odoo/addons/base_optional_quick_create
  setup/base_optional_quick_create/setup.py
Labels: bot is merging ⏳, stale

#536 [MIG] base_technical_features: Migration to 16.0
  base_technical_features/README.rst
  base_technical_features/__init__.py
  base_technical_features/__manifest__.py
  base_technical_features/data/res_users.xml
  base_technical_features/i18n/am.po
  base_technical_features/i18n/ar.po
  base_technical_features/i18n/base_technical_features.pot
  base_technical_features/i18n/ca.po
  base_technical_features/i18n/da.po
  base_technical_features/i18n/de.po
  base_technical_features/i18n/el_GR.po
  base_technical_features/i18n/es.po
  base_technical_features/i18n/es_ES.po
  base_technical_features/i18n/es_MX.po
  base_technical_features/i18n/fi.po
  base_technical_features/i18n/fr.po
  base_technical_features/i18n/fr_CA.po
  base_technical_features/i18n/fr_CH.po
  base_technical_features/i18n/fr_FR.po
  base_technical_features/i18n/gl.po
  base_technical_features/i18n/hr.po
  base_technical_features/i18n/hr_HR.po
  base_technical_features/i18n/it.po
  base_technical_features/i18n/ja.po
  base_technical_features/i18n/nl.po
  base_technical_features/i18n/nl_NL.po
  base_technical_features/i18n/pt.po
  base_technical_features/i18n/pt_BR.po
  base_technical_features/i18n/pt_PT.po
  base_technical_features/i18n/ro.po
  base_technical_features/i18n/sl.po
  base_technical_features/i18n/tr.po
  base_technical_features/i18n/tr_TR.po
  base_technical_features/i18n/zh_CN.po
  base_technical_features/models/__init__.py
  base_technical_features/models/base.py
  base_technical_features/models/ir_ui_menu.py
  base_technical_features/models/res_users.py
  base_technical_features/readme/CONTRIBUTORS.rst
  base_technical_features/readme/DESCRIPTION.rst
  base_technical_features/readme/USAGE.rst
  base_technical_features/security/res_groups.xml
  base_technical_features/static/description/icon.png
  base_technical_features/static/description/index.html
  base_technical_features/static/description/user_preferences.png
  base_technical_features/tests/__init__.py
  base_technical_features/tests/test_base_technical_features.py
  base_technical_features/views/res_users.xml
  setup/base_technical_features/odoo/addons/base_technical_features
  setup/base_technical_features/setup.py
Labels: approved, migration, bot is merging ⏳

#553 [15.0][UPD] repo template
  .copier-answers.yml
  .pre-commit-config.yaml
  README.md
Labels: bot is merging ⏳

#552 [14.0][UPD] repo template and switch to github actions.
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  document_quick_access_folder_auto_classification/__manifest__.py
Labels: bot is merging ⏳

#554 [15.0][MIG] announcement: Migration to 15.0
  announcement/README.rst
  announcement/__init__.py
  announcement/__manifest__.py
  announcement/i18n/announcement.pot
  announcement/i18n/es.po
  announcement/models/__init__.py
  announcement/models/announcement.py
  announcement/models/ir_config_parameter.py
  announcement/models/res_users.py
  announcement/readme/CONFIGURE.rst
  announcement/readme/CONTRIBUTORS.rst
  announcement/readme/DESCRIPTION.rst
  announcement/readme/ROADMAP.rst
  announcement/readme/USAGE.rst
  announcement/security/announcement_security.xml
  announcement/security/ir.model.access.csv
  announcement/static/description/icon.png
  announcement/static/description/index.html
  announcement/static/src/js/announcement_dialog.esm.js
  announcement/static/src/js/announcement_systray.esm.js
  announcement/static/src/xml/announcement_dialog.xml
  announcement/static/src/xml/announcement_systray.xml
  announcement/views/announcement_views.xml
  announcement/wizards/__init__.py
  announcement/wizards/read_announcement_wizard.py
  announcement/wizards/read_announcement_wizard.xml
  setup/announcement/odoo/addons/announcement
  setup/announcement/setup.py
Labels: approved, bot is merging ⏳

#276 [14.0][ADD] base_tier_validation_correction
  base_tier_validation_correction/__init__.py
  base_tier_validation_correction/__manifest__.py
  base_tier_validation_correction/data/cron_data.xml
  base_tier_validation_correction/data/mail_data.xml
  base_tier_validation_correction/models/__init__.py
  base_tier_validation_correction/models/tier_correction.py
  base_tier_validation_correction/models/tier_validation.py
  base_tier_validation_correction/readme/CONFIGURE.rst
  base_tier_validation_correction/readme/CONTRIBUTORS.rst
  base_tier_validation_correction/readme/DESCRIPTION.rst
  base_tier_validation_correction/readme/USAGE.rst
  base_tier_validation_correction/security/correction_groups.xml
  base_tier_validation_correction/security/ir.model.access.csv
  base_tier_validation_correction/static/description/icon.png
  base_tier_validation_correction/static/description/index.html
  base_tier_validation_correction/templates/tier_validation_templates.xml
  base_tier_validation_correction/tests/__init__.py
  base_tier_validation_correction/tests/test_tier_validation.py
  base_tier_validation_correction/views/tier_correction_view.xml
  base_tier_validation_correction/wizards/__init__.py
  base_tier_validation_correction/wizards/affected_tier_reviews.py
  base_tier_validation_correction/wizards/affected_tier_reviews.xml
  filter_multi_user/tests/test_filter_multi_user.py
  setup/base_tier_validation_correction/odoo/addons/base_tier_validation_correction
  setup/base_tier_validation_correction/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#556 [15.0][FIX] base_export_manager: Remove default because it is redundant
  base_export_manager/models/ir_exports_line.py
Labels: bot is merging ⏳

#557 [15.0][FIX] chained_swapper: Change SavepointCase to TransactionCase
  chained_swapper/tests/test_chained_swapper.py
Labels: bot is merging ⏳

#560 [15.0][IMP] mass_editing: Do not re-use demo and admin users to avoid incompatibilities with data from those users.
  mass_editing/tests/test_mass_editing.py
Labels: approved, bot is merging ⏳

#561 [16.0][IMP] server_action_mass_edit: Do not re-use demo and admin users to avoid incompatibilities with data from those users.
  server_action_mass_edit/tests/test_mass_editing.py
Labels: approved, bot is merging ⏳
