Repository OCA/server-ux, pull requests merged in 2022-08, with the labels that each got.

#508 [13.0][FIX] base_tier_validation: Icon error when validated
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#520 [15.0][FIX] base_tier_validation: Icon error when validated
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#519 [14.0][FIX] base_tier_validation: Icon error when validated
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#521 [13.0][ADD] announcement: New module
  announcement/README.rst
  announcement/__init__.py
  announcement/__manifest__.py
  announcement/i18n/announcement.pot
  announcement/i18n/es.po
  announcement/models/__init__.py
  announcement/models/announcement.py
  announcement/models/ir_http.py
  announcement/models/res_users.py
  announcement/readme/CONFIGURE.rst
  announcement/readme/CONTRIBUTORS.rst
  announcement/readme/DESCRIPTION.rst
  announcement/readme/ROADMAP.rst
  announcement/readme/USAGE.rst
  announcement/security/announcement_security.xml
  announcement/security/ir.model.access.csv
  announcement/static/description/icon.png
  announcement/static/description/index.html
  announcement/static/src/js/announcement.js
  announcement/static/src/js/announcement_dialog.js
  announcement/static/src/xml/announcement.xml
  announcement/static/src/xml/announcement_dialog.xml
  announcement/templates/assets_backend.xml
  announcement/views/announcement_views.xml
  announcement/wizards/__init__.py
  announcement/wizards/read_announcement_wizard.py
  announcement/wizards/read_announcement_wizard.xml
  setup/announcement/odoo/addons/announcement
  setup/announcement/setup.py
Labels: approved, bot is merging ⏳

#526 [14.0][FIX] base_search_custom_field_filter: Resolve the error when the expression has related fields (dot notation).
  base_search_custom_field_filter/models/base.py
Labels: bot is merging ⏳

#525 [13.0][FIX] announcement: assorted fixes
  announcement/__manifest__.py
  announcement/i18n/announcement.pot
  announcement/i18n/es.po
  announcement/migrations/13.0.2.0.0/noupdate_changes.xml
  announcement/migrations/13.0.2.0.0/post-migration.py
  announcement/models/__init__.py
  announcement/models/announcement.py
  announcement/models/ir_http.py
  announcement/models/res_users.py
  announcement/security/announcement_security.xml
  announcement/static/src/js/announcement.js
  announcement/static/src/js/announcement_dialog.js
  announcement/views/announcement_views.xml
  announcement/wizards/read_announcement_wizard.py
Labels: approved, bot is merging ⏳

#527 [13.0][FIX] announcement: log read just once
  announcement/models/res_users.py
Labels: bot is merging ⏳

#523 [MIG] base_import_security_group: Migration to 15.0
  base_import_security_group/README.rst
  base_import_security_group/__init__.py
  base_import_security_group/__manifest__.py
  base_import_security_group/i18n/base_import_security_group.pot
  base_import_security_group/i18n/ca.po
  base_import_security_group/i18n/de.po
  base_import_security_group/i18n/es.po
  base_import_security_group/i18n/fr.po
  base_import_security_group/i18n/gl.po
  base_import_security_group/i18n/hr.po
  base_import_security_group/i18n/it.po
  base_import_security_group/i18n/pt.po
  base_import_security_group/i18n/sk.po
  base_import_security_group/models/__init__.py
  base_import_security_group/models/base.py
  base_import_security_group/models/ir_http.py
  base_import_security_group/readme/CONTRIBUTORS.rst
  base_import_security_group/readme/DESCRIPTION.rst
  base_import_security_group/security/base_import_security_group_security.xml
  base_import_security_group/static/description/icon.png
  base_import_security_group/static/description/icon.svg
  base_import_security_group/static/description/index.html
  base_import_security_group/static/src/js/import.js
  base_import_security_group/static/src/js/tour_import.js
  base_import_security_group/tests/__init__.py
  base_import_security_group/tests/test_base_import_security_group.py
  setup/base_import_security_group/odoo/addons/base_import_security_group
  setup/base_import_security_group/setup.py
Labels: approved, bot is merging ⏳

#490 [15.0][MIG] sequence_reset_period
  sequence_reset_period/README.rst
  sequence_reset_period/__init__.py
  sequence_reset_period/__manifest__.py
  sequence_reset_period/i18n/es.po
  sequence_reset_period/i18n/fr_FR.po
  sequence_reset_period/i18n/hr.po
  sequence_reset_period/i18n/sequence_reset_period.pot
  sequence_reset_period/i18n/zh_CN.po
  sequence_reset_period/models/__init__.py
  sequence_reset_period/models/ir_sequence.py
  sequence_reset_period/readme/CONTRIBUTORS.rst
  sequence_reset_period/readme/DESCRIPTION.rst
  sequence_reset_period/readme/USAGE.rst
  sequence_reset_period/static/description/icon.png
  sequence_reset_period/static/description/index.html
  sequence_reset_period/tests/__init__.py
  sequence_reset_period/tests/test_period.py
  sequence_reset_period/views/sequence_views.xml
  setup/sequence_reset_period/odoo/addons/sequence_reset_period
  setup/sequence_reset_period/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale
