Repository OCA/server-ux, pull requests merged in 2022-03, with the labels that each got.

#318 Fix avoid_quick_create with multiprocess
  base_optional_quick_create/models/ir_model.py
Labels: question, approved, ready to merge, bot is merging ⏳

#468 [15.0][FIX+IMP] base_tier_validation: Don't mess searches with NewId + non …
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#467 [14.0][FIX+IMP] base_tier_validation: Don't mess searches with NewId + non …
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#457 [14.0][MIG] base_custom_filter
  base_custom_filter/README.rst
  base_custom_filter/__init__.py
  base_custom_filter/__manifest__.py
  base_custom_filter/i18n/base_custom_filter.pot
  base_custom_filter/i18n/it.po
  base_custom_filter/models/__init__.py
  base_custom_filter/models/base.py
  base_custom_filter/models/ir_filters.py
  base_custom_filter/models/ir_filters_group.py
  base_custom_filter/readme/CONFIGURE.rst
  base_custom_filter/readme/CONTRIBUTORS.rst
  base_custom_filter/readme/DESCRIPTION.rst
  base_custom_filter/readme/USAGE.rst
  base_custom_filter/security/ir.model.access.csv
  base_custom_filter/static/description/icon.png
  base_custom_filter/static/description/index.html
  base_custom_filter/tests/__init__.py
  base_custom_filter/tests/test_filters.py
  base_custom_filter/views/ir_filters_group_views.xml
  base_custom_filter/views/ir_filters_views.xml
  setup/base_custom_filter/odoo/addons/base_custom_filter
  setup/base_custom_filter/setup.py
Labels: approved, ready to merge, bot is merging ⏳
