Repository OCA/server-ux, pull requests merged in 2022-12, with the labels that each got.

#497 [14.0][ENH] base_cancel_confirm, allow disable cancel confirm
  base_cancel_confirm/model/base_cancel_confirm.py
  base_cancel_confirm/readme/CONFIGURE.rst
  base_cancel_confirm/tests/test_cancel_confirm.py
Labels: approved, ready to merge, bot is merging ⏳

#562 [MIG] multi step wizard: Migration to 16.0
  multi_step_wizard/README.rst
  multi_step_wizard/__init__.py
  multi_step_wizard/__manifest__.py
  multi_step_wizard/i18n/ca.po
  multi_step_wizard/i18n/hr.po
  multi_step_wizard/i18n/multi_step_wizard.pot
  multi_step_wizard/i18n/nl.po
  multi_step_wizard/i18n/zh_CN.po
  multi_step_wizard/models/__init__.py
  multi_step_wizard/models/multi_step_wizard.py
  multi_step_wizard/readme/CONTRIBUTORS.rst
  multi_step_wizard/readme/DESCRIPTION.rst
  multi_step_wizard/readme/USAGE.rst
  multi_step_wizard/static/description/icon.png
  multi_step_wizard/static/description/index.html
  multi_step_wizard/tests/__init__.py
  multi_step_wizard/tests/common.py
  multi_step_wizard/tests/multi_step_wizard_test.py
  multi_step_wizard/tests/test_multi_step_wizard.py
  multi_step_wizard/views/multi_step_wizard_views.xml
  setup/multi_step_wizard/odoo/addons/multi_step_wizard
  setup/multi_step_wizard/setup.py
Labels: approved, ready to merge

#564 [14.0][IMP] mass_editing: Do not re-use demo and admin users to avoid incompatibilities with data from those users.
  mass_editing/tests/test_mass_editing.py
Labels: bot is merging ⏳

#565 [15.0][FIX] date_range: fix TZ
  date_range/static/src/js/date_range.esm.js
Labels: approved, bot is merging ⏳

#540 [16.0] base_tier_validation: migration to 16
  base_tier_validation/README.rst
  base_tier_validation/__init__.py
  base_tier_validation/__manifest__.py
  base_tier_validation/data/mail_data.xml
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/i18n/es_MX.po
  base_tier_validation/i18n/fr.po
  base_tier_validation/i18n/it.po
  base_tier_validation/i18n/nl_NL.po
  base_tier_validation/i18n/sv.po
  base_tier_validation/i18n/zh_CN.po
  base_tier_validation/models/__init__.py
  base_tier_validation/models/res_config_settings.py
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONFIGURE.rst
  base_tier_validation/readme/CONTRIBUTORS.rst
  base_tier_validation/readme/DESCRIPTION.rst
  base_tier_validation/readme/HISTORY.rst
  base_tier_validation/readme/ROADMAP.rst
  base_tier_validation/security/ir.model.access.csv
  base_tier_validation/security/tier_validation_security.xml
  base_tier_validation/static/description/icon.png
  base_tier_validation/static/description/index.html
  base_tier_validation/static/src/js/ir_model.esm.js
  base_tier_validation/static/src/js/main.esm.js
  base_tier_validation/static/src/js/review_group_view.esm.js
  base_tier_validation/static/src/js/review_groups.esm.js
  base_tier_validation/static/src/js/review_notification_handler.esm.js
  base_tier_validation/static/src/js/reviewer_menu_container.esm.js
  base_tier_validation/static/src/js/reviewer_menu_view.esm.js
  base_tier_validation/static/src/js/systray.esm.js
  base_tier_validation/static/src/js/systray_service.esm.js
  base_tier_validation/static/src/js/tier_review_widget.esm.js
  base_tier_validation/static/src/scss/review.scss
  base_tier_validation/static/src/scss/systray.scss
  base_tier_validation/static/src/xml/reviewer_menu_container.xml
  base_tier_validation/static/src/xml/systray.xml
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/templates/tier_validation_templates.xml
  base_tier_validation/tests/__init__.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation/views/res_config_settings_views.xml
  base_tier_validation/views/tier_definition_view.xml
  base_tier_validation/views/tier_review_view.xml
  base_tier_validation/wizard/__init__.py
  base_tier_validation/wizard/comment_wizard.py
  base_tier_validation/wizard/comment_wizard_view.xml
  setup/base_tier_validation/odoo/addons/base_tier_validation
  setup/base_tier_validation/setup.py
Labels: approved, bot is merging ⏳
