Repository OCA/server-ux, pull requests merged in 2022-02, with the labels that each got.

#438 [14.0][FIX] Fix access right issues when using actions
  barcode_action/models/res_partner.py
  base_cancel_confirm/model/base_cancel_confirm.py
Labels: bug, approved, bot is merging ⏳

#436 [14.0][FIX] mass_operation_abstract: Allow to apply updates to archive records.
  mass_operation_abstract/wizard/mass_operation_wizard_mixin.py
Labels: approved, bot is merging ⏳

#427 [13.0][ADD] base_custom_filter
  base_custom_filter/README.rst
  base_custom_filter/__init__.py
  base_custom_filter/__manifest__.py
  base_custom_filter/models/__init__.py
  base_custom_filter/models/base.py
  base_custom_filter/models/ir_filters.py
  base_custom_filter/models/ir_filters_group.py
  base_custom_filter/readme/CONFIGURE.rst
  base_custom_filter/readme/CONTRIBUTORS.rst
  base_custom_filter/readme/DESCRIPTION.rst
  base_custom_filter/readme/USAGE.rst
  base_custom_filter/security/ir.model.access.csv
  base_custom_filter/static/description/icon.png
  base_custom_filter/static/description/index.html
  base_custom_filter/views/ir_filters_group_views.xml
  base_custom_filter/views/ir_filters_views.xml
  setup/base_custom_filter/odoo/addons/base_custom_filter
  setup/base_custom_filter/setup.py
Labels: approved, bot is merging ⏳

#441 [15.0] [MIG] barcode_action
  barcode_action/README.rst
  barcode_action/__init__.py
  barcode_action/__manifest__.py
  barcode_action/demo/barcode_action_demo.xml
  barcode_action/i18n/barcode_action.pot
  barcode_action/i18n/es.po
  barcode_action/i18n/hr.po
  barcode_action/i18n/pt.po
  barcode_action/i18n/zh_CN.po
  barcode_action/models/__init__.py
  barcode_action/models/res_partner.py
  barcode_action/readme/CONTRIBUTORS.rst
  barcode_action/readme/DESCRIPTION.rst
  barcode_action/readme/USAGE.rst
  barcode_action/security/ir.model.access.csv
  barcode_action/static/description/icon.png
  barcode_action/static/description/index.html
  barcode_action/static/src/js/action_barcode_form.js
  barcode_action/static/src/js/action_barcode_widget.js
  barcode_action/tests/__init__.py
  barcode_action/tests/test_partner_find.py
  barcode_action/wizard/__init__.py
  barcode_action/wizard/barcode_action.py
  barcode_action/wizard/barcode_action_view.xml
  setup/barcode_action/odoo/addons/barcode_action
  setup/barcode_action/setup.py
Labels: approved, bot is merging ⏳

#443 [15.0] [MIG] document_quick_access
  document_quick_access/README.rst
  document_quick_access/__init__.py
  document_quick_access/__manifest__.py
  document_quick_access/i18n/document_quick_access.pot
  document_quick_access/i18n/es.po
  document_quick_access/models/__init__.py
  document_quick_access/models/base.py
  document_quick_access/models/document_quick_access_rule.py
  document_quick_access/readme/CONFIGURE.rst
  document_quick_access/readme/CONTRIBUTORS.rst
  document_quick_access/readme/DESCRIPTION.rst
  document_quick_access/readme/ROADMAP.rst
  document_quick_access/readme/USAGE.rst
  document_quick_access/security/ir.model.access.csv
  document_quick_access/static/description/icon.png
  document_quick_access/static/description/index.html
  document_quick_access/static/src/js/document_quick_access_launcher.js
  document_quick_access/static/src/xml/document_quick_access_launcher.xml
  document_quick_access/tests/__init__.py
  document_quick_access/tests/test_document_quick_access.py
  document_quick_access/views/document_quick_access_rule.xml
  requirements.txt
  setup/document_quick_access/odoo/addons/document_quick_access
  setup/document_quick_access/setup.py
Labels: bot is merging ⏳

#434 [14.0][IMP] base_tier_validation_server_action: Avoid recursive server actions
  base_tier_validation_server_action/models/tier_review.py
Labels: approved, ready to merge, bot is merging ⏳

#420 [15.0][MIG] filter_multi_user
  filter_multi_user/README.rst
  filter_multi_user/__init__.py
  filter_multi_user/__manifest__.py
  filter_multi_user/i18n/es.po
  filter_multi_user/i18n/filter_multi_user.pot
  filter_multi_user/models/__init__.py
  filter_multi_user/models/ir_filters.py
  filter_multi_user/readme/CONFIGURE.rst
  filter_multi_user/readme/CONTRIBUTORS.rst
  filter_multi_user/readme/DESCRIPTION.rst
  filter_multi_user/security/ir_filters_security.xml
  filter_multi_user/static/description/icon.png
  filter_multi_user/static/description/index.html
  filter_multi_user/tests/__init__.py
  filter_multi_user/tests/test_filter_multi_user.py
  filter_multi_user/views/ir_filters_view.xml
  setup/filter_multi_user/odoo/addons/filter_multi_user
  setup/filter_multi_user/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#426 [14.0][IMP] base_tier_validation: Include inactive records in activities
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
Labels: bot is merging ⏳

#442 12.0 FIX mass_edit: make field_id required
  mass_editing/models/mass_editing_line.py
Labels: approved, ready to merge, bot is merging ⏳

#400 [14.0][ADD] base_tier_validation_report
  base_tier_validation_report/__init__.py
  base_tier_validation_report/__manifest__.py
  base_tier_validation_report/models/__init__.py
  base_tier_validation_report/models/tier_review.py
  base_tier_validation_report/readme/CONTRIBUTORS.rst
  base_tier_validation_report/readme/DESCRIPTION.rst
  base_tier_validation_report/reports/tier_review_report.xml
  base_tier_validation_report/static/description/icon.png
  setup/base_tier_validation_report/odoo/addons/base_tier_validation_report
  setup/base_tier_validation_report/setup.py
Labels: needs review, approved, bot is merging ⏳

#417 [14.0][MIG]base_user_locale: Migration to 14.0
  base_user_locale/README.rst
  base_user_locale/__init__.py
  base_user_locale/__manifest__.py
  base_user_locale/controllers/__init__.py
  base_user_locale/controllers/web_client.py
  base_user_locale/i18n/base_user_locale.pot
  base_user_locale/models/__init__.py
  base_user_locale/models/calendar_event.py
  base_user_locale/models/res_company.py
  base_user_locale/models/res_config_settings.py
  base_user_locale/models/res_users.py
  base_user_locale/readme/CONTRIBUTORS.rst
  base_user_locale/readme/DESCRIPTION.rst
  base_user_locale/readme/USAGE.rst
  base_user_locale/static/description/icon.png
  base_user_locale/static/description/index.html
  base_user_locale/tests/__init__.py
  base_user_locale/tests/test_base_user_locale.py
  base_user_locale/views/res_config_settings.xml
  base_user_locale/views/res_users.xml
  setup/base_user_locale/odoo/addons/base_user_locale
  setup/base_user_locale/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#453 [13.0][FIX] base_user_locale: make new fields readable for user
  base_user_locale/models/res_users.py
Labels: approved, bot is merging ⏳

#454 [14.0][FIX] base_user_locale: make new fields readable for user
  base_user_locale/models/res_users.py
Labels: approved, bot is merging ⏳

#459 [14.0] [FIX] external_dependency python-stdnum
  sequence_check_digit/__manifest__.py
Labels: bot is merging ⏳

#460 [FIX] [14.0] Removed external dependencies already defined in Odoo base
  requirements.txt
  sequence_check_digit/__manifest__.py
Labels: bot is merging ⏳
