Repository OCA/server-ux, pull requests merged in 2022-07, with the labels that each got.

#503 [15.0][MIG] chained_swapper: Migration to 15.0
  chained_swapper/README.rst
  chained_swapper/__init__.py
  chained_swapper/__manifest__.py
  chained_swapper/demo/chained_swapper_demo.xml
  chained_swapper/hooks.py
  chained_swapper/i18n/chained_swapper.pot
  chained_swapper/i18n/es.po
  chained_swapper/i18n/it.po
  chained_swapper/models/__init__.py
  chained_swapper/models/chained_swapper.py
  chained_swapper/readme/CONFIGURE.rst
  chained_swapper/readme/CONTRIBUTORS.rst
  chained_swapper/readme/DESCRIPTION.rst
  chained_swapper/readme/USAGE.rst
  chained_swapper/security/ir.model.access.csv
  chained_swapper/static/description/icon.png
  chained_swapper/static/description/index.html
  chained_swapper/tests/__init__.py
  chained_swapper/tests/test_chained_swapper.py
  chained_swapper/views/chained_swapper_views.xml
  chained_swapper/wizard/__init__.py
  chained_swapper/wizard/chained_swapper_wizard.py
  chained_swapper/wizard/chained_swapper_wizard_views.xml
  setup/chained_swapper/odoo/addons/chained_swapper
  setup/chained_swapper/setup.py
Labels: bot is merging ⏳

#492 [MIG] multi_step_wizard: Migration to 15.0
  multi_step_wizard/README.rst
  multi_step_wizard/__init__.py
  multi_step_wizard/__manifest__.py
  multi_step_wizard/i18n/ca.po
  multi_step_wizard/i18n/hr.po
  multi_step_wizard/i18n/multi_step_wizard.pot
  multi_step_wizard/i18n/nl.po
  multi_step_wizard/i18n/zh_CN.po
  multi_step_wizard/models/__init__.py
  multi_step_wizard/models/multi_step_wizard.py
  multi_step_wizard/readme/CONTRIBUTORS.rst
  multi_step_wizard/readme/DESCRIPTION.rst
  multi_step_wizard/readme/USAGE.rst
  multi_step_wizard/static/description/icon.png
  multi_step_wizard/static/description/index.html
  multi_step_wizard/tests/__init__.py
  multi_step_wizard/tests/common.py
  multi_step_wizard/tests/multi_step_wizard_test.py
  multi_step_wizard/tests/test_multi_step_wizard.py
  multi_step_wizard/views/multi_step_wizard_views.xml
  setup/multi_step_wizard/odoo/addons/multi_step_wizard
  setup/multi_step_wizard/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#469 [FIX] chained_swapper - search chain field with correct model
  chained_swapper/models/chained_swapper.py
Labels: bot is merging ⏳, stale

#425 [15.0][MIG] base_tier_validation_formula
  base_tier_validation_formula/README.rst
  base_tier_validation_formula/__init__.py
  base_tier_validation_formula/__manifest__.py
  base_tier_validation_formula/i18n/base_tier_validation_formula.pot
  base_tier_validation_formula/i18n/es.po
  base_tier_validation_formula/i18n/it.po
  base_tier_validation_formula/i18n/zh_CN.po
  base_tier_validation_formula/models/__init__.py
  base_tier_validation_formula/models/tier_definition.py
  base_tier_validation_formula/models/tier_review.py
  base_tier_validation_formula/models/tier_validation.py
  base_tier_validation_formula/readme/CONTRIBUTORS.rst
  base_tier_validation_formula/readme/DESCRIPTION.rst
  base_tier_validation_formula/readme/USAGE.rst
  base_tier_validation_formula/static/description/icon.png
  base_tier_validation_formula/static/description/index.html
  base_tier_validation_formula/tests/__init__.py
  base_tier_validation_formula/tests/test_tier_validation.py
  base_tier_validation_formula/views/tier_definition_view.xml
  setup/base_tier_validation_formula/odoo/addons/base_tier_validation_formula
  setup/base_tier_validation_formula/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#513 [14.0][UPD] Brainbean Apps => CorporateHub
  base_user_locale/__manifest__.py
  base_user_locale/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#514 [13.0][UPD] Repo template
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
Labels: approved, bot is merging ⏳

#512 [13.0][UPD] Brainbean Apps => CorporateHub
  base_user_locale/__manifest__.py
  base_user_locale/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#446 [15.0] [MIG] document_quick_access_folder_auto_classification
  document_quick_access_folder_auto_classification/README.rst
  document_quick_access_folder_auto_classification/__init__.py
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/components/__init__.py
  document_quick_access_folder_auto_classification/components/document_quick_access_process.py
  document_quick_access_folder_auto_classification/data/cron_data.xml
  document_quick_access_folder_auto_classification/data/edi_data.xml
  document_quick_access_folder_auto_classification/i18n/document_quick_access_folder_auto_classification.pot
  document_quick_access_folder_auto_classification/models/__init__.py
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/readme/CONFIGURE.rst
  document_quick_access_folder_auto_classification/readme/CONTRIBUTORS.rst
  document_quick_access_folder_auto_classification/readme/DESCRIPTION.rst
  document_quick_access_folder_auto_classification/readme/USAGE.rst
  document_quick_access_folder_auto_classification/security/ir.model.access.csv
  document_quick_access_folder_auto_classification/security/security.xml
  document_quick_access_folder_auto_classification/static/description/icon.png
  document_quick_access_folder_auto_classification/static/description/icon.svg
  document_quick_access_folder_auto_classification/static/description/index.html
  document_quick_access_folder_auto_classification/tests/__init__.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
  document_quick_access_folder_auto_classification/tests/test_file.pdf
  document_quick_access_folder_auto_classification/views/edi_exchange_record.xml
  document_quick_access_folder_auto_classification/wizards/__init__.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.xml
  setup/document_quick_access_folder_auto_classification/odoo/addons/document_quick_access_folder_auto_classification
  setup/document_quick_access_folder_auto_classification/setup.py
Labels: approved, bot is merging ⏳

#498 [13.0][FIX] document_quick_access_folder_auto_classification: remove dead code
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/data/cron_data.xml
  document_quick_access_folder_auto_classification/data/edi_data.xml
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
Labels: approved, bot is merging ⏳

#515 [14.0][FIX] document_quick_access_folder_auto_classification: remove dead code
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/data/cron_data.xml
  document_quick_access_folder_auto_classification/data/edi_data.xml
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
Labels: approved, bot is merging ⏳

#516 [15.0][FIX] document_quick_access_folder_auto_classification: remove dead code
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/data/cron_data.xml
  document_quick_access_folder_auto_classification/data/edi_data.xml
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
Labels: approved, bot is merging ⏳
