Repository OCA/server-ux, pull requests merged in 2022-09, with the labels that each got.

#529 [FIX] mass_editing: fix migration to 14.0
  mass_editing/migrations/14.0.1.0.0/post-migrate.py
Labels: bug, migration, bot is merging ⏳

#522 [15.0][MIG] base_revision
  base_revision/README.rst
  base_revision/__init__.py
  base_revision/__manifest__.py
  base_revision/i18n/base_revision.pot
  base_revision/i18n/es.po
  base_revision/models/__init__.py
  base_revision/models/base_revision.py
  base_revision/readme/CONTRIBUTORS.rst
  base_revision/readme/DESCRIPTION.rst
  base_revision/static/description/icon.png
  base_revision/static/description/index.html
  base_revision/tests/__init__.py
  base_revision/tests/base_revision_tester.py
  base_revision/tests/test_base_revision.py
  setup/base_revision/odoo/addons/base_revision
  setup/base_revision/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#528 [15.0] [MIG] base_tier_validation_forward
  base_tier_validation_forward/README.rst
  base_tier_validation_forward/__init__.py
  base_tier_validation_forward/__manifest__.py
  base_tier_validation_forward/data/mail_data.xml
  base_tier_validation_forward/hooks.py
  base_tier_validation_forward/i18n/base_tier_validation_forward.pot
  base_tier_validation_forward/i18n/es.po
  base_tier_validation_forward/models/__init__.py
  base_tier_validation_forward/models/tier_definition.py
  base_tier_validation_forward/models/tier_review.py
  base_tier_validation_forward/models/tier_validation.py
  base_tier_validation_forward/readme/CONFIGURE.rst
  base_tier_validation_forward/readme/CONTRIBUTORS.rst
  base_tier_validation_forward/readme/DESCRIPTION.rst
  base_tier_validation_forward/security/ir.model.access.csv
  base_tier_validation_forward/static/description/icon.png
  base_tier_validation_forward/static/description/index.html
  base_tier_validation_forward/static/src/xml/tier_review_template.xml
  base_tier_validation_forward/templates/tier_validation_templates.xml
  base_tier_validation_forward/tests/__init__.py
  base_tier_validation_forward/tests/test_tier_validation.py
  base_tier_validation_forward/views/tier_definition_view.xml
  base_tier_validation_forward/wizard/__init__.py
  base_tier_validation_forward/wizard/comment_wizard.py
  base_tier_validation_forward/wizard/forward_wizard.py
  base_tier_validation_forward/wizard/forward_wizard_view.xml
  setup/base_tier_validation_forward/odoo/addons/base_tier_validation_forward
  setup/base_tier_validation_forward/setup.py
Labels: approved, bot is merging ⏳

#502 [14.0][ENH] base_tier_validation_report, see all reviews group
  base_tier_validation_report/__manifest__.py
  base_tier_validation_report/models/tier_review.py
  base_tier_validation_report/readme/DESCRIPTION.rst
  base_tier_validation_report/reports/tier_review_report.xml
  base_tier_validation_report/security/groups.xml
Labels: approved, bot is merging ⏳

#531 [13.0][IMP] announcement: configurable full width
  announcement/README.rst
  announcement/models/__init__.py
  announcement/models/ir_config_parameter.py
  announcement/readme/CONFIGURE.rst
  announcement/static/description/index.html
  announcement/static/src/js/announcement_dialog.js
Labels: approved, bot is merging ⏳
