Repository OCA/server-ux, pull requests merged in 2023-09, with the labels that each got.

#715 [15.0][FIX] date_range: Allow select date_ranges on custom filters
  date_range/static/src/js/date_range.esm.js
  date_range/static/src/xml/date_range.xml
Labels: approved, bot is merging ⏳

#714 [14.0][IMP] base_tier_validation: Add method for deciding whether the elimination of revisions is necessary.
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#720 [16.0][IMP] base_tier_validation: Add method to allow remove reviews.
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#723 [16.0][FIX] date_range: Avoid redefinition of this.OPERATORS as a new object
  date_range/static/src/js/date_range.esm.js
Labels: bot is merging ⏳

#719 [IMP] base_tier_validation: show in res.config.settings already migra…
  base_tier_validation/models/res_config_settings.py
  base_tier_validation/views/res_config_settings_views.xml
Labels: bot is merging ⏳

#726 [16.0][FIX] date_range: Use FIELD_TYPES from this, as is already set
  date_range/static/src/js/date_range.esm.js
Labels: bot is merging ⏳

#631 [IMP]-15.0-Improve error message when update record in batch
  mass_editing/README.rst
  mass_editing/demo/mass_editing.xml
  mass_editing/readme/CONTRIBUTORS.rst
  mass_editing/tests/test_mass_editing.py
  mass_editing/wizard/mass_editing_wizard.py
  mass_editing/wizard/mass_editing_wizard.xml
Labels: approved, ready to merge, bot is merging ⏳, stale
