Repository OCA/server-ux, pull requests merged in 2023-01, with the labels that each got.

#570 [15.0][MIG] base_search_custom_field_filter: Migration to 15.0
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/i18n/base_search_custom_field_filter.pot
  base_search_custom_field_filter/i18n/es.po
  base_search_custom_field_filter/i18n/it.po
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/readme/CONFIGURE.rst
  base_search_custom_field_filter/readme/CONTRIBUTORS.rst
  base_search_custom_field_filter/readme/DESCRIPTION.rst
  base_search_custom_field_filter/readme/USAGE.rst
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/icon.png
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
  setup/base_search_custom_field_filter/odoo/addons/base_search_custom_field_filter
  setup/base_search_custom_field_filter/setup.py
Labels: approved, bot is merging ⏳

#578 [13.0][IMP]copier update
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  requirements.txt
Labels: bot is merging ⏳

#499 [13.0][ADD]base_rule_visibility_restriction
  base_rule_visibility_restriction/__init__.py
  base_rule_visibility_restriction/__manifest__.py
  base_rule_visibility_restriction/models/__init__.py
  base_rule_visibility_restriction/models/ir_rule.py
  base_rule_visibility_restriction/readme/CONTRIBUTORS.rst
  base_rule_visibility_restriction/readme/DESCRIPTION.rst
  base_rule_visibility_restriction/readme/USAGE.rst
  base_rule_visibility_restriction/views/ir_rule_views.xml
  setup/base_rule_visibility_restriction/odoo/addons/base_rule_visibility_restriction
  setup/base_rule_visibility_restriction/setup.py
Labels: approved, bot is merging ⏳

#572 [16.0][MIG] base_optional_quick_create
  base_optional_quick_create/README.rst
  base_optional_quick_create/__init__.py
  base_optional_quick_create/__manifest__.py
  base_optional_quick_create/i18n/base_optional_quick_create.pot
  base_optional_quick_create/i18n/de.po
  base_optional_quick_create/i18n/es.po
  base_optional_quick_create/i18n/fi.po
  base_optional_quick_create/i18n/fr.po
  base_optional_quick_create/i18n/hr.po
  base_optional_quick_create/i18n/hr_HR.po
  base_optional_quick_create/i18n/it.po
  base_optional_quick_create/i18n/nb_NO.po
  base_optional_quick_create/i18n/pt_BR.po
  base_optional_quick_create/i18n/sl.po
  base_optional_quick_create/i18n/tr.po
  base_optional_quick_create/i18n/tr_TR.po
  base_optional_quick_create/i18n/zh_CN.po
  base_optional_quick_create/models/__init__.py
  base_optional_quick_create/models/ir_model.py
  base_optional_quick_create/readme/CONTRIBUTORS.rst
  base_optional_quick_create/readme/CREDITS.rst
  base_optional_quick_create/readme/DESCRIPTION.rst
  base_optional_quick_create/readme/USAGE.rst
  base_optional_quick_create/static/description/icon.png
  base_optional_quick_create/static/description/index.html
  base_optional_quick_create/tests/__init__.py
  base_optional_quick_create/tests/test_quick_create.py
  base_optional_quick_create/views/model_view.xml
  setup/base_optional_quick_create/odoo/addons/base_optional_quick_create
  setup/base_optional_quick_create/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#583 [IMP] base_tier_validation: group_erp_manager can edit tier definitions.
  base_tier_validation/security/ir.model.access.csv
Labels: approved, bot is merging ⏳
