Repository OCA/server-ux, pull requests merged in 2023-07, with the labels that each got.

#602 [FIX] base_tier_validation_report - replace selection with compute
  base_tier_validation_report/models/tier_review.py
Labels: approved, bot is merging ⏳

#567 [15.0][MIG] base_tier_validation_report
  base_tier_validation_report/README.rst
  base_tier_validation_report/__init__.py
  base_tier_validation_report/__manifest__.py
  base_tier_validation_report/i18n/base_tier_validation_report.pot
  base_tier_validation_report/i18n/it.po
  base_tier_validation_report/models/__init__.py
  base_tier_validation_report/models/tier_review.py
  base_tier_validation_report/readme/CONTRIBUTORS.rst
  base_tier_validation_report/readme/DESCRIPTION.rst
  base_tier_validation_report/reports/tier_review_report.xml
  base_tier_validation_report/security/groups.xml
  base_tier_validation_report/static/description/icon.png
  base_tier_validation_report/static/description/index.html
  setup/base_tier_validation_report/odoo/addons/base_tier_validation_report
  setup/base_tier_validation_report/setup.py
Labels: approved, bot is merging ⏳

#585 [15.0][MIG] base_field_deprecated
  base_field_deprecated/README.rst
  base_field_deprecated/__init__.py
  base_field_deprecated/__manifest__.py
  base_field_deprecated/hooks.py
  base_field_deprecated/models/__init__.py
  base_field_deprecated/models/ir_model_fields.py
  base_field_deprecated/readme/CONTRIBUTORS.rst
  base_field_deprecated/readme/DESCRIPTION.rst
  base_field_deprecated/readme/USAGE.rst
  base_field_deprecated/views/ir_model_fields_views.xml
  setup/base_field_deprecated/odoo/addons/base_field_deprecated
  setup/base_field_deprecated/setup.py
Labels: approved, bot is merging ⏳

#651 [15.0][FIX] base_duplicate_security_group: use a proper hook
  base_duplicate_security_group/static/src/js/duplicate.esm.js
  base_duplicate_security_group/static/src/js/tour_duplicate.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#685 [15.0][MIG] base_archive_date
  base_archive_date/README.rst
  base_archive_date/__init__.py
  base_archive_date/__manifest__.py
  base_archive_date/i18n/base_archive_date.pot
  base_archive_date/models/__init__.py
  base_archive_date/models/base.py
  base_archive_date/readme/CONTRIBUTORS.rst
  base_archive_date/readme/DESCRIPTION.rst
  base_archive_date/readme/USAGE.rst
  base_archive_date/static/description/icon.png
  base_archive_date/static/description/index.html
  base_archive_date/tests/__init__.py
  base_archive_date/tests/test_base_archive_date.py
  setup/base_archive_date/odoo/addons/base_archive_date
  setup/base_archive_date/setup.py
Labels: approved, bot is merging ⏳

#689 [14.0][OU-FIX] mass_editing: magic fields sync + security group
  mass_editing/migrations/14.0.1.0.0/pre-migrate.py
Labels: approved, bot is merging ⏳

#690 [14.0][FIX] mass_editing ambigous sql column
  mass_editing/migrations/14.0.1.0.0/pre-migrate.py
Labels: bot is merging ⏳

#688 [15.0][IMP] announcement: Add Announcement Tags
  announcement/__manifest__.py
  announcement/demo/announcement_tag_demo.xml
  announcement/i18n/announcement.pot
  announcement/i18n/es.po
  announcement/models/__init__.py
  announcement/models/announcement.py
  announcement/models/announcement_tag.py
  announcement/security/announcement_security.xml
  announcement/security/ir.model.access.csv
  announcement/views/announcement_tag_views.xml
  announcement/views/announcement_views.xml
Labels: approved, bot is merging ⏳

#628 [16.0][MIG] base_search_custom_field_filter: Migration to 16.0
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/i18n/base_search_custom_field_filter.pot
  base_search_custom_field_filter/i18n/es.po
  base_search_custom_field_filter/i18n/it.po
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/readme/CONFIGURE.rst
  base_search_custom_field_filter/readme/CONTRIBUTORS.rst
  base_search_custom_field_filter/readme/DESCRIPTION.rst
  base_search_custom_field_filter/readme/USAGE.rst
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/icon.png
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
  setup/base_search_custom_field_filter/odoo/addons/base_search_custom_field_filter
  setup/base_search_custom_field_filter/setup.py
Labels: approved, bot is merging ⏳

#695 [15.0][IMP] announcement: Prevent False specific_user_ids from when not appropriate
  announcement/models/announcement.py
Labels: approved, bot is merging ⏳

#672 [16.0][IMP] base_revision: create method in batch
  base_revision/models/base_revision.py
  base_revision/tests/test_base_revision.py
Labels: approved, bot is merging ⏳

#696 [15.0][IMP] announcement: add attachments field
  announcement/models/announcement.py
  announcement/models/res_users.py
  announcement/views/announcement_views.xml
Labels: approved, bot is merging ⏳
