Repository OCA/server-ux, pull requests merged in 2023-08, with the labels that each got.

#701 [15.0][MIG] base_recurrence: Migration to 15.0
  base_recurrence/README.rst
  base_recurrence/__init__.py
  base_recurrence/__manifest__.py
  base_recurrence/i18n/base_recurrence.pot
  base_recurrence/models/__init__.py
  base_recurrence/models/recurrence_mixin.py
  base_recurrence/readme/CONTRIBUTORS.rst
  base_recurrence/readme/DESCRIPTION.rst
  base_recurrence/readme/USAGE.rst
  base_recurrence/static/description/icon.png
  base_recurrence/static/description/index.html
  base_recurrence/tests/__init__.py
  base_recurrence/tests/fake_model.py
  base_recurrence/tests/test_recurrence.py
  setup/base_recurrence/odoo/addons/base_recurrence
  setup/base_recurrence/setup.py
Labels: approved, bot is merging ⏳

#699 [14.0][FIX] base_tier_validation: multiple comment with approve_sequence_bypass
  base_tier_validation/models/tier_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#704 [15.0][FIX] base_export_manager: Avoid access error when using export profile
  base_export_manager/models/ir_exports.py
  base_export_manager/models/ir_exports_line.py
Labels: approved, bot is merging ⏳

#705 [14.0][MIG] base_recurrence
  base_recurrence/README.rst
  base_recurrence/__init__.py
  base_recurrence/__manifest__.py
  base_recurrence/i18n/base_recurrence.pot
  base_recurrence/i18n/it.po
  base_recurrence/models/__init__.py
  base_recurrence/models/recurrence_mixin.py
  base_recurrence/readme/CONTRIBUTORS.rst
  base_recurrence/readme/DESCRIPTION.rst
  base_recurrence/readme/USAGE.rst
  base_recurrence/static/description/icon.png
  base_recurrence/static/description/index.html
  base_recurrence/tests/__init__.py
  base_recurrence/tests/fake_model.py
  base_recurrence/tests/test_recurrence.py
  setup/base_recurrence/odoo/addons/base_recurrence
  setup/base_recurrence/setup.py
Labels: approved, bot is merging ⏳

#682 [14.0][IMP] base_tier_validation : add write possibility for reviewers
  base_tier_validation/i18n/fr.po
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#616 [FIX][14.0] base_export_manager: manage
  base_export_manager/models/ir_exports_line.py
  base_export_manager/tests/test_ir_exports.py
Labels: bot is merging ⏳, stale

#683 [14.0][MIG]base_archive_date
  base_archive_date/README.rst
  base_archive_date/__init__.py
  base_archive_date/__manifest__.py
  base_archive_date/i18n/base_archive_date.pot
  base_archive_date/models/__init__.py
  base_archive_date/models/base.py
  base_archive_date/readme/CONTRIBUTORS.rst
  base_archive_date/readme/DESCRIPTION.rst
  base_archive_date/readme/USAGE.rst
  base_archive_date/static/description/icon.png
  base_archive_date/static/description/index.html
  base_archive_date/tests/__init__.py
  base_archive_date/tests/test_base_archive_date.py
  setup/base_archive_date/odoo/addons/base_archive_date
  setup/base_archive_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#686 [15.0][MIG] web_archive_date
  setup/web_archive_date/odoo/addons/web_archive_date
  setup/web_archive_date/setup.py
  web_archive_date/README.rst
  web_archive_date/__init__.py
  web_archive_date/__manifest__.py
  web_archive_date/i18n/web_archive_date.pot
  web_archive_date/models/__init__.py
  web_archive_date/models/base.py
  web_archive_date/readme/CONTRIBUTORS.rst
  web_archive_date/readme/DESCRIPTION.rst
  web_archive_date/readme/ROADMAP.rst
  web_archive_date/readme/USAGE.rst
  web_archive_date/static/description/icon.png
  web_archive_date/static/description/index.html
  web_archive_date/static/src/js/debug_manager.esm.js
  web_archive_date/static/src/xml/debug.xml
  web_archive_date/tests/__init__.py
  web_archive_date/tests/test_web_archive_date.py
Labels: approved, ready to merge, bot is merging ⏳

#684 [14.0][MIG]web_archive_date
  setup/web_archive_date/odoo/addons/web_archive_date
  setup/web_archive_date/setup.py
  web_archive_date/README.rst
  web_archive_date/__init__.py
  web_archive_date/__manifest__.py
  web_archive_date/i18n/web_archive_date.pot
  web_archive_date/models/__init__.py
  web_archive_date/models/base.py
  web_archive_date/readme/CONTRIBUTORS.rst
  web_archive_date/readme/DESCRIPTION.rst
  web_archive_date/readme/ROADMAP.rst
  web_archive_date/readme/USAGE.rst
  web_archive_date/static/description/icon.png
  web_archive_date/static/description/index.html
  web_archive_date/static/src/xml/debug.xml
  web_archive_date/tests/__init__.py
  web_archive_date/tests/test_web_archive_date.py
Labels: bot is merging ⏳
