Repository OCA/server-ux, pull requests merged in 2023-03, with the labels that each got.

#608 [15.0][MIG] base_duplicate_security_group: Migration to 15.0
  base_duplicate_security_group/README.rst
  base_duplicate_security_group/__init__.py
  base_duplicate_security_group/__manifest__.py
  base_duplicate_security_group/i18n/base_duplicate_security_group.pot
  base_duplicate_security_group/readme/CONFIGURE.rst
  base_duplicate_security_group/readme/CONTRIBUTORS.rst
  base_duplicate_security_group/readme/DESCRIPTION.rst
  base_duplicate_security_group/security/base_duplicate_security_group_security.xml
  base_duplicate_security_group/static/description/icon.png
  base_duplicate_security_group/static/description/index.html
  base_duplicate_security_group/static/src/js/duplicate.esm.js
  base_duplicate_security_group/static/src/js/tour_duplicate.esm.js
  base_duplicate_security_group/tests/__init__.py
  base_duplicate_security_group/tests/test_base_duplicate_security_group.py
  setup/base_duplicate_security_group/odoo/addons/base_duplicate_security_group
  setup/base_duplicate_security_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#594 [14.0][FIX] base_tier_validation_correction: xmlids
  base_tier_validation_correction/models/tier_correction.py
Labels: approved, ready to merge, merged 🎉

#599 [16.0][MIG] base_revision
  base_revision/README.rst
  base_revision/__init__.py
  base_revision/__manifest__.py
  base_revision/i18n/base_revision.pot
  base_revision/i18n/es.po
  base_revision/models/__init__.py
  base_revision/models/base_revision.py
  base_revision/readme/CONTRIBUTORS.rst
  base_revision/readme/DESCRIPTION.rst
  base_revision/static/description/icon.png
  base_revision/static/description/index.html
  base_revision/tests/__init__.py
  base_revision/tests/base_revision_tester.py
  base_revision/tests/test_base_revision.py
  setup/base_revision/odoo/addons/base_revision
  setup/base_revision/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#615 [14.0][FIX] barcode_action: context was not passed
  barcode_action/static/src/js/action_barcode_form.js
Labels: approved, bot is merging ⏳

#617 [16.0][FIX] date_range: Remove a test requirement from install dependencies
  date_range/__manifest__.py
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#613 [14.0][MIG] base_rule_visibility_restriction
  base_rule_visibility_restriction/README.rst
  base_rule_visibility_restriction/__init__.py
  base_rule_visibility_restriction/__manifest__.py
  base_rule_visibility_restriction/i18n/base_rule_visibility_restriction.pot
  base_rule_visibility_restriction/models/__init__.py
  base_rule_visibility_restriction/models/ir_rule.py
  base_rule_visibility_restriction/readme/CONTRIBUTORS.rst
  base_rule_visibility_restriction/readme/DESCRIPTION.rst
  base_rule_visibility_restriction/readme/USAGE.rst
  base_rule_visibility_restriction/static/description/icon.png
  base_rule_visibility_restriction/static/description/index.html
  base_rule_visibility_restriction/views/ir_rule_views.xml
  setup/base_rule_visibility_restriction/odoo/addons/base_rule_visibility_restriction
  setup/base_rule_visibility_restriction/setup.py
Labels: approved, bot is merging ⏳
