Repository OCA/server-ux, pull requests merged in 2023-12, with the labels that each got.

#620 [14.0][FIX] base_user_locale: user can change own locale
  base_user_locale/models/res_users.py
  base_user_locale/tests/test_base_user_locale.py
Labels: approved, ready to merge, bot is merging ⏳

#664 [16.0][mig] barcode_action: Migration to 16.0
  barcode_action/README.rst
  barcode_action/__init__.py
  barcode_action/__manifest__.py
  barcode_action/demo/barcode_action_demo.xml
  barcode_action/i18n/barcode_action.pot
  barcode_action/i18n/es.po
  barcode_action/i18n/hr.po
  barcode_action/i18n/pt.po
  barcode_action/i18n/zh_CN.po
  barcode_action/models/__init__.py
  barcode_action/models/res_partner.py
  barcode_action/readme/CONTRIBUTORS.rst
  barcode_action/readme/DESCRIPTION.rst
  barcode_action/readme/USAGE.rst
  barcode_action/security/ir.model.access.csv
  barcode_action/static/description/icon.png
  barcode_action/static/description/index.html
  barcode_action/static/src/js/action_barcode_widget.esm.js
  barcode_action/tests/__init__.py
  barcode_action/tests/test_partner_find.py
  barcode_action/wizard/__init__.py
  barcode_action/wizard/barcode_action.py
  barcode_action/wizard/barcode_action_view.xml
  setup/barcode_action/odoo/addons/barcode_action
  setup/barcode_action/setup.py
Labels: approved, bot is merging ⏳

#777 [16.0][IMP] base_tier_validation_formula: test performance improvement
  base_tier_validation_formula/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#767 [16.0][PORT] base_tier_validation: 732 from 15.0
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#666 [16.0][IMP] base_custom_filter: add search feature
  base_custom_filter/README.rst
  base_custom_filter/models/base.py
  base_custom_filter/models/ir_filters.py
  base_custom_filter/readme/CONFIGURE.rst
  base_custom_filter/readme/CONTRIBUTORS.rst
  base_custom_filter/readme/DESCRIPTION.rst
  base_custom_filter/static/description/index.html
  base_custom_filter/tests/test_filters.py
  base_custom_filter/views/ir_filters_group_views.xml
  base_custom_filter/views/ir_filters_views.xml
Labels: approved, bot is merging ⏳

#471 [15.0][MIG] base_user_locale
  base_user_locale/README.rst
  base_user_locale/__init__.py
  base_user_locale/__manifest__.py
  base_user_locale/controllers/__init__.py
  base_user_locale/controllers/web_client.py
  base_user_locale/i18n/base_user_locale.pot
  base_user_locale/models/__init__.py
  base_user_locale/models/calendar_event.py
  base_user_locale/models/res_company.py
  base_user_locale/models/res_config_settings.py
  base_user_locale/models/res_users.py
  base_user_locale/readme/CONTRIBUTORS.rst
  base_user_locale/readme/DESCRIPTION.rst
  base_user_locale/readme/USAGE.rst
  base_user_locale/static/description/icon.png
  base_user_locale/static/description/index.html
  base_user_locale/tests/__init__.py
  base_user_locale/tests/test_base_user_locale.py
  base_user_locale/views/res_config_settings.xml
  base_user_locale/views/res_users.xml
  setup/base_user_locale/odoo/addons/base_user_locale
  setup/base_user_locale/setup.py
Labels: approved, bot is merging ⏳, no stale

#780 [16.0][MIG] base_user_locale
  base_user_locale/README.rst
  base_user_locale/__init__.py
  base_user_locale/__manifest__.py
  base_user_locale/controllers/__init__.py
  base_user_locale/controllers/web_client.py
  base_user_locale/i18n/base_user_locale.pot
  base_user_locale/models/__init__.py
  base_user_locale/models/calendar_event.py
  base_user_locale/models/res_company.py
  base_user_locale/models/res_config_settings.py
  base_user_locale/models/res_users.py
  base_user_locale/readme/CONTRIBUTORS.rst
  base_user_locale/readme/DESCRIPTION.rst
  base_user_locale/readme/USAGE.rst
  base_user_locale/static/description/icon.png
  base_user_locale/static/description/index.html
  base_user_locale/tests/__init__.py
  base_user_locale/tests/test_base_user_locale.py
  base_user_locale/views/res_config_settings.xml
  base_user_locale/views/res_users.xml
  setup/base_user_locale/odoo/addons/base_user_locale
  setup/base_user_locale/setup.py
Labels: approved, bot is merging ⏳

#784 [15.0][IMP] announcement: add calendar view
  announcement/models/announcement.py
  announcement/views/announcement_views.xml
Labels: approved, bot is merging ⏳

#783 [16.0][ADD] base_tier_validation_definition_server_action
  base_tier_validation_definition_server_action/README.rst
  base_tier_validation_definition_server_action/__init__.py
  base_tier_validation_definition_server_action/__manifest__.py
  base_tier_validation_definition_server_action/models/__init__.py
  base_tier_validation_definition_server_action/models/tier_definition.py
  base_tier_validation_definition_server_action/models/tier_validation.py
  base_tier_validation_definition_server_action/readme/CONFIGURE.rst
  base_tier_validation_definition_server_action/readme/CONTRIBUTORS.rst
  base_tier_validation_definition_server_action/readme/DESCRIPTION.rst
  base_tier_validation_definition_server_action/static/description/index.html
  base_tier_validation_definition_server_action/tests/__init__.py
  base_tier_validation_definition_server_action/tests/test_tier_validation.py
  base_tier_validation_definition_server_action/views/tier_definition_view.xml
  setup/base_tier_validation_definition_server_action/odoo/addons/base_tier_validation_definition_server_action
  setup/base_tier_validation_definition_server_action/setup.py
Labels: approved, bot is merging ⏳

#786 [15.0][FIX] announcement: allow multicompany tags
  announcement/models/announcement_tag.py
Labels: approved, bot is merging ⏳

#785 [16.0] [ADD] base_archive_security
  base_archive_security/README.rst
  base_archive_security/__init__.py
  base_archive_security/__manifest__.py
  base_archive_security/hooks.py
  base_archive_security/i18n/base_archive_security.pot
  base_archive_security/i18n/fr.po
  base_archive_security/models/__init__.py
  base_archive_security/models/base.py
  base_archive_security/readme/CONTRIBUTORS.rst
  base_archive_security/readme/DESCRIPTION.rst
  base_archive_security/readme/USAGE.rst
  base_archive_security/security/res_groups.xml
  base_archive_security/static/description/index.html
  base_archive_security/static/src/js/form_controller.esm.js
  base_archive_security/static/src/js/list_controller.esm.js
  base_archive_security/tests/__init__.py
  base_archive_security/tests/test_archive_security.py
  setup/base_archive_security/odoo/addons/base_archive_security
  setup/base_archive_security/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#748 [16.0][MIG] base_tier_validation_waiting
  base_tier_validation_waiting/README.rst
  base_tier_validation_waiting/__init__.py
  base_tier_validation_waiting/__manifest__.py
  base_tier_validation_waiting/i18n/base_tier_validation_waiting.pot
  base_tier_validation_waiting/models/__init__.py
  base_tier_validation_waiting/models/tier_definition.py
  base_tier_validation_waiting/models/tier_review.py
  base_tier_validation_waiting/models/tier_validation.py
  base_tier_validation_waiting/readme/CONFIGURE.rst
  base_tier_validation_waiting/readme/CONTRIBUTORS.rst
  base_tier_validation_waiting/readme/DESCRIPTION.rst
  base_tier_validation_waiting/readme/DEVELOP.rst
  base_tier_validation_waiting/readme/ROADMAP.rst
  base_tier_validation_waiting/readme/USAGE.rst
  base_tier_validation_waiting/security/ir.model.access.csv
  base_tier_validation_waiting/static/description/icon.png
  base_tier_validation_waiting/static/description/index.html
  base_tier_validation_waiting/static/src/xml/tier_review_template.xml
  base_tier_validation_waiting/tests/__init__.py
  base_tier_validation_waiting/tests/test_tier_validation.py
  base_tier_validation_waiting/views/tier_definition_views.xml
  setup/base_tier_validation_waiting/odoo/addons/base_tier_validation_waiting
  setup/base_tier_validation_waiting/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳
