Repository OCA/server-ux, pull requests merged in 2023-06, with the labels that each got.

#569 [16.0][MIG] base_substate
  base_substate/README.rst
  base_substate/__init__.py
  base_substate/__manifest__.py
  base_substate/i18n/base_substate.pot
  base_substate/models/__init__.py
  base_substate/models/base_substate.py
  base_substate/models/base_substate_mixin.py
  base_substate/readme/CONTRIBUTORS.rst
  base_substate/readme/DESCRIPTION.rst
  base_substate/readme/USAGE.rst
  base_substate/security/base_substate_security.xml
  base_substate/security/ir.model.access.csv
  base_substate/static/description/icon.png
  base_substate/static/description/index.html
  base_substate/tests/__init__.py
  base_substate/tests/models_mixin.py
  base_substate/tests/sale_test.py
  base_substate/tests/test_base_substate.py
  base_substate/views/base_substate_type_views.xml
  base_substate/views/base_substate_value_views.xml
  base_substate/views/base_substate_views.xml
  setup/base_substate/odoo/addons/base_substate
  setup/base_substate/setup.py
Labels: approved, bot is merging ⏳

#665 [15.0][FIX] base_import_security_group: fix test test_error
  base_import_security_group/static/src/js/tour_import.js
Labels: approved, bot is merging ⏳

#667 [16.0] date_range: AGPL -> LGPL
  date_range/__init__.py
  date_range/__manifest__.py
  date_range/models/__init__.py
  date_range/models/date_range.py
  date_range/models/date_range_search_mixin.py
  date_range/models/date_range_type.py
  date_range/static/src/xml/date_range.xml
  date_range/tests/__init__.py
  date_range/tests/test_date_range.py
  date_range/tests/test_date_range_generator.py
  date_range/tests/test_date_range_search_mixin.py
  date_range/tests/test_date_range_type.py
  date_range/wizard/__init__.py
  date_range/wizard/date_range_generator.py
Labels: approved, bot is merging ⏳

#669 [13.0][ADD] base_recurrence
  base_recurrence/README.rst
  base_recurrence/__init__.py
  base_recurrence/__manifest__.py
  base_recurrence/models/__init__.py
  base_recurrence/models/recurrence_mixin.py
  base_recurrence/readme/CONTRIBUTORS.rst
  base_recurrence/readme/DESCRIPTION.rst
  base_recurrence/readme/USAGE.rst
  base_recurrence/static/description/icon.png
  base_recurrence/static/description/index.html
  base_recurrence/tests/__init__.py
  base_recurrence/tests/fake_model.py
  base_recurrence/tests/test_recurrence.py
  setup/base_recurrence/odoo/addons/base_recurrence
  setup/base_recurrence/setup.py
  test-requirements.txt
Labels: bot is merging ⏳

#668 [14.0] date_range: AGPL -> LGPL
  date_range/__init__.py
  date_range/__manifest__.py
  date_range/models/__init__.py
  date_range/models/date_range.py
  date_range/models/date_range_search_mixin.py
  date_range/models/date_range_type.py
  date_range/static/src/js/date_range.js
  date_range/static/src/xml/date_range.xml
  date_range/tests/__init__.py
  date_range/tests/test_date_range.py
  date_range/tests/test_date_range_generator.py
  date_range/tests/test_date_range_search_mixin.py
  date_range/tests/test_date_range_type.py
  date_range/wizard/__init__.py
  date_range/wizard/date_range_generator.py
Labels: approved, bot is merging ⏳

#621 [16.0][MIG] base_tier_validation_forward
  base_tier_validation_forward/README.rst
  base_tier_validation_forward/__init__.py
  base_tier_validation_forward/__manifest__.py
  base_tier_validation_forward/data/mail_data.xml
  base_tier_validation_forward/hooks.py
  base_tier_validation_forward/i18n/base_tier_validation_forward.pot
  base_tier_validation_forward/i18n/es.po
  base_tier_validation_forward/models/__init__.py
  base_tier_validation_forward/models/tier_definition.py
  base_tier_validation_forward/models/tier_review.py
  base_tier_validation_forward/models/tier_validation.py
  base_tier_validation_forward/readme/CONFIGURE.rst
  base_tier_validation_forward/readme/CONTRIBUTORS.rst
  base_tier_validation_forward/readme/DESCRIPTION.rst
  base_tier_validation_forward/security/ir.model.access.csv
  base_tier_validation_forward/static/description/icon.png
  base_tier_validation_forward/static/description/index.html
  base_tier_validation_forward/static/src/xml/tier_review_template.xml
  base_tier_validation_forward/templates/tier_validation_templates.xml
  base_tier_validation_forward/tests/__init__.py
  base_tier_validation_forward/tests/test_tier_validation.py
  base_tier_validation_forward/views/tier_definition_view.xml
  base_tier_validation_forward/wizard/__init__.py
  base_tier_validation_forward/wizard/comment_wizard.py
  base_tier_validation_forward/wizard/forward_wizard.py
  base_tier_validation_forward/wizard/forward_wizard_view.xml
  setup/base_tier_validation_forward/odoo/addons/base_tier_validation_forward
  setup/base_tier_validation_forward/setup.py
Labels: approved, bot is merging ⏳

#622 [16.0][mig] base_menu_visibility_restriction: Migration to 16.0
  base_menu_visibility_restriction/README.rst
  base_menu_visibility_restriction/__init__.py
  base_menu_visibility_restriction/__manifest__.py
  base_menu_visibility_restriction/demo/ir_ui_menu.xml
  base_menu_visibility_restriction/demo/res_group.xml
  base_menu_visibility_restriction/i18n/base_menu_visibility_restriction.pot
  base_menu_visibility_restriction/models/__init__.py
  base_menu_visibility_restriction/models/ir_ui_menu.py
  base_menu_visibility_restriction/readme/CONTRIBUTORS.rst
  base_menu_visibility_restriction/readme/DESCRIPTION.rst
  base_menu_visibility_restriction/readme/USAGE.rst
  base_menu_visibility_restriction/static/description/icon.png
  base_menu_visibility_restriction/static/description/index.html
  base_menu_visibility_restriction/tests/__init__.py
  base_menu_visibility_restriction/tests/test_ir_ui_menu.py
  base_menu_visibility_restriction/views/ir_ui_menu.xml
  setup/base_menu_visibility_restriction/odoo/addons/base_menu_visibility_restriction
  setup/base_menu_visibility_restriction/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#659 [14.0][IMP] base_tier_validation: Misc changes
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/templates/tier_validation_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#661 [16.0][MIG] base_cancel_confirm
  base_cancel_confirm/README.rst
  base_cancel_confirm/__init__.py
  base_cancel_confirm/__manifest__.py
  base_cancel_confirm/i18n/base_cancel_confirm.pot
  base_cancel_confirm/i18n/nl.po
  base_cancel_confirm/model/__init__.py
  base_cancel_confirm/model/base_cancel_confirm.py
  base_cancel_confirm/readme/CONFIGURE.rst
  base_cancel_confirm/readme/CONTRIBUTORS.rst
  base_cancel_confirm/readme/DESCRIPTION.rst
  base_cancel_confirm/security/ir.model.access.csv
  base_cancel_confirm/static/description/icon.png
  base_cancel_confirm/static/description/index.html
  base_cancel_confirm/tests/__init__.py
  base_cancel_confirm/tests/cancel_confirm_tester.py
  base_cancel_confirm/tests/test_cancel_confirm.py
  base_cancel_confirm/views/cancel_confirm_template.xml
  base_cancel_confirm/wizard/__init__.py
  base_cancel_confirm/wizard/cancel_confirm.py
  base_cancel_confirm/wizard/cancel_confirm.xml
  setup/base_cancel_confirm/odoo/addons/base_cancel_confirm
  setup/base_cancel_confirm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#676 [13.0][ADD]base_archive_date & web_archive_date
  base_archive_date/__init__.py
  base_archive_date/__manifest__.py
  base_archive_date/models/__init__.py
  base_archive_date/models/base.py
  base_archive_date/readme/CONTRIBUTORS.rst
  base_archive_date/readme/DESCRIPTION.rst
  base_archive_date/readme/USAGE.rst
  base_archive_date/tests/__init__.py
  base_archive_date/tests/test_base_archive_date.py
  setup/base_archive_date/odoo/addons/base_archive_date
  setup/base_archive_date/setup.py
  setup/web_archive_date/odoo/addons/web_archive_date
  setup/web_archive_date/setup.py
  web_archive_date/__init__.py
  web_archive_date/__manifest__.py
  web_archive_date/models/__init__.py
  web_archive_date/models/base.py
  web_archive_date/readme/CONTRIBUTORS.rst
  web_archive_date/readme/DESCRIPTION.rst
  web_archive_date/readme/ROADMAP.rst
  web_archive_date/readme/USAGE.rst
  web_archive_date/static/src/xml/debug.xml
  web_archive_date/tests/__init__.py
  web_archive_date/tests/test_web_archive_date.py
Labels: approved, bot is merging ⏳

#680 [15.0][IMP] base_tier_validation: Misc changes
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/templates/tier_validation_templates.xml
Labels: approved, bot is merging ⏳

#681 [16.0][IMP] base_tier_validation: Misc changes
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/templates/tier_validation_templates.xml
Labels: approved, bot is merging ⏳

#679 [15.0][IMP] announcement: add general_anouncement option to announcement
  announcement/models/announcement.py
  announcement/views/announcement_views.xml
Labels: approved, bot is merging ⏳
