Repository OCA/server-ux, pull requests merged in 2023-10, with the labels that each got.

#729 [FIX] base_tier_validation: Exclude cancel records from pending count
  base_tier_validation/models/res_users.py
Labels: bot is merging ⏳

#730 [14.0][IMP] base_tier_validation: Add validation_status field to tier.validation
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#737 [15.0][IMP] base_tier_validation: Add validation_status field to tier.validation
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation_forward/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#738 [16.0][IMP] base_tier_validation: Add validation_status field to tier.validation
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation_forward/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#739 [15.0][IMP] server-ux : test performance improvement
  base_tier_validation/tests/common.py
  base_tier_validation_formula/tests/test_tier_validation.py
  chained_swapper/tests/test_chained_swapper.py
Labels: approved, bot is merging ⏳

#742 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  chained_swapper/demo/chained_swapper_demo.xml
Labels: help wanted, needs review, bot is merging ⏳

#740 [PERF] base_tier_validation: filter records with reviews before compute fields
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳
