Repository OCA/server-ux, pull requests merged in 2023-04, with the labels that each got.

#541 [15.0][MIG] base_cancel_confirm: Migration to 15.0
  base_cancel_confirm/README.rst
  base_cancel_confirm/__init__.py
  base_cancel_confirm/__manifest__.py
  base_cancel_confirm/i18n/base_cancel_confirm.pot
  base_cancel_confirm/i18n/nl.po
  base_cancel_confirm/model/__init__.py
  base_cancel_confirm/model/base_cancel_confirm.py
  base_cancel_confirm/readme/CONFIGURE.rst
  base_cancel_confirm/readme/CONTRIBUTORS.rst
  base_cancel_confirm/readme/DESCRIPTION.rst
  base_cancel_confirm/security/ir.model.access.csv
  base_cancel_confirm/static/description/icon.png
  base_cancel_confirm/static/description/index.html
  base_cancel_confirm/templates/cancel_confirm_template.xml
  base_cancel_confirm/tests/__init__.py
  base_cancel_confirm/tests/cancel_confirm_tester.py
  base_cancel_confirm/tests/test_cancel_confirm.py
  base_cancel_confirm/wizard/__init__.py
  base_cancel_confirm/wizard/cancel_confirm.py
  base_cancel_confirm/wizard/cancel_confirm.xml
  setup/base_cancel_confirm/odoo/addons/base_cancel_confirm
  setup/base_cancel_confirm/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#609 [16.0][MIG] date_range_account
  date_range_account/README.rst
  date_range_account/__init__.py
  date_range_account/__manifest__.py
  date_range_account/i18n/date_range_account.pot
  date_range_account/i18n/es.po
  date_range_account/i18n/fr.po
  date_range_account/readme/CONTRIBUTORS.rst
  date_range_account/readme/DESCRIPTION.rst
  date_range_account/security/ir.model.access.csv
  date_range_account/static/description/icon.png
  date_range_account/static/description/index.html
  date_range_account/views/date_range.xml
  setup/date_range_account/odoo/addons/date_range_account
  setup/date_range_account/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#626 [14.0][MIG] base_action_visibility_restriction
  base_action_visibility_restriction/README.rst
  base_action_visibility_restriction/__init__.py
  base_action_visibility_restriction/__manifest__.py
  base_action_visibility_restriction/i18n/base_action_visibility_restriction.pot
  base_action_visibility_restriction/models/__init__.py
  base_action_visibility_restriction/models/ir_actions.py
  base_action_visibility_restriction/readme/CONTRIBUTORS.rst
  base_action_visibility_restriction/readme/DESCRIPTION.rst
  base_action_visibility_restriction/readme/USAGE.rst
  base_action_visibility_restriction/static/description/icon.png
  base_action_visibility_restriction/static/description/index.html
  base_action_visibility_restriction/tests/__init__.py
  base_action_visibility_restriction/tests/test_base_action_visibility_restriction.py
  base_action_visibility_restriction/views/ir_actions_views.xml
  setup/base_action_visibility_restriction/odoo/addons/base_action_visibility_restriction
  setup/base_action_visibility_restriction/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#566 [15.0][IMP] date_range: Add babel.dates.format_date to safe_eval of name_expr
  date_range/models/date_range.py
  date_range/models/date_range_type.py
  date_range/readme/CONTRIBUTORS.rst
  date_range/tests/test_date_range_generator.py
  date_range/wizard/date_range_generator.py
Labels: approved, bot is merging ⏳

#630 [FIX] base_tier_validation: Use domain for filtering values
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
Labels: approved, bot is merging ⏳

#634 [15.0][FIX] base_tier_validation: Use domain for filtering values
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
Labels: approved, bot is merging ⏳

#637 [16.0][PORT] 630 from 14.0
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/review_group_view.esm.js
Labels: approved, bot is merging ⏳

#635 [15.0][PORT] 612 from 14.0
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#636 [16.0][PORT] 612 from 14.0
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#642 [FIX] base_tier_validation: Detect if model has active field
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
  base_tier_validation/static/src/xml/systray.xml
Labels: approved, bot is merging ⏳

#590 [16.0][MIG] sequence_reset_period: Migration to 16.0.
  sequence_reset_period/README.rst
  sequence_reset_period/__init__.py
  sequence_reset_period/__manifest__.py
  sequence_reset_period/i18n/es.po
  sequence_reset_period/i18n/fr_FR.po
  sequence_reset_period/i18n/hr.po
  sequence_reset_period/i18n/sequence_reset_period.pot
  sequence_reset_period/i18n/zh_CN.po
  sequence_reset_period/models/__init__.py
  sequence_reset_period/models/ir_sequence.py
  sequence_reset_period/readme/CONTRIBUTORS.rst
  sequence_reset_period/readme/DESCRIPTION.rst
  sequence_reset_period/readme/USAGE.rst
  sequence_reset_period/static/description/icon.png
  sequence_reset_period/static/description/index.html
  sequence_reset_period/tests/__init__.py
  sequence_reset_period/tests/test_period.py
  sequence_reset_period/views/sequence_views.xml
  setup/sequence_reset_period/odoo/addons/sequence_reset_period
  setup/sequence_reset_period/setup.py
Labels: approved, bot is merging ⏳
