Repository OCA/server-ux, pull requests merged in 2023-11, with the labels that each got.

#670 [15.0][ADD] base_multi_branch_company
  base_multi_branch_company/README.rst
  base_multi_branch_company/__init__.py
  base_multi_branch_company/__manifest__.py
  base_multi_branch_company/models/__init__.py
  base_multi_branch_company/models/res_branch.py
  base_multi_branch_company/models/res_company.py
  base_multi_branch_company/readme/CONTRIBUTORS.rst
  base_multi_branch_company/readme/DESCRIPTION.rst
  base_multi_branch_company/readme/USAGE.rst
  base_multi_branch_company/security/ir.model.access.csv
  base_multi_branch_company/static/description/index.html
  base_multi_branch_company/views/res_branch_view.xml
  base_multi_branch_company/views/res_company.xml
  setup/base_multi_branch_company/odoo/addons/base_multi_branch_company
  setup/base_multi_branch_company/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#743 [PERF] base_tier_validation: filter records with reviews before compu…
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#731 [FIX] date_range: prevent filters to be added multiple times
  date_range/static/src/js/date_range.esm.js
Labels: approved, bot is merging ⏳

#746 [16.0] date_range: fix string, add search views and use _check_company_auto
  date_range/models/date_range.py
  date_range/models/date_range_type.py
  date_range/tests/test_date_range.py
  date_range/tests/test_date_range_type.py
  date_range/views/date_range_view.xml
  date_range/wizard/date_range_generator.xml
  date_range_account/views/date_range.xml
Labels: approved, bot is merging ⏳

#745 [16.0][PERF] base_tier_validation: filter records with reviews before compu…
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#751 [15.0][FIX] base_search_custom_field_filter: Force name on custom filters
  base_search_custom_field_filter/models/base.py
Labels: approved, bot is merging ⏳

#677 [16.0][MIG] - base_import_security_group
  base_import_security_group/README.rst
  base_import_security_group/__init__.py
  base_import_security_group/__manifest__.py
  base_import_security_group/i18n/base_import_security_group.pot
  base_import_security_group/i18n/ca.po
  base_import_security_group/i18n/de.po
  base_import_security_group/i18n/es.po
  base_import_security_group/i18n/fr.po
  base_import_security_group/i18n/gl.po
  base_import_security_group/i18n/hr.po
  base_import_security_group/i18n/it.po
  base_import_security_group/i18n/pt.po
  base_import_security_group/i18n/sk.po
  base_import_security_group/models/__init__.py
  base_import_security_group/models/base.py
  base_import_security_group/models/ir_http.py
  base_import_security_group/readme/CONTRIBUTORS.rst
  base_import_security_group/readme/DESCRIPTION.rst
  base_import_security_group/security/base_import_security_group_security.xml
  base_import_security_group/static/description/icon.png
  base_import_security_group/static/description/icon.svg
  base_import_security_group/static/description/index.html
  base_import_security_group/static/src/js/import.esm.js
  base_import_security_group/static/src/js/tour_import.js
  base_import_security_group/tests/__init__.py
  base_import_security_group/tests/test_base_import_security_group.py
  setup/base_import_security_group/odoo/addons/base_import_security_group
  setup/base_import_security_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#754 [13.0][IMP] base_tier_validation: filter tier definition for the current company
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#759 [16.0][IMP] base_tier_validation: filter tier definition for the current co…
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#757 [14.0][IMP] base_tier_validation: filter tier definition for the current co…
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#758 [15.0][IMP] base_tier_validation: filter tier definition for the current co…
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#756 [14.0][IMP] base_tier_validation: Add `_prepare_tier_review_vals()` methot to allow inheritance.
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
  setup/test_base_tier_validation/odoo/addons/test_base_tier_validation
  setup/test_base_tier_validation/setup.py
  test_base_tier_validation/README.rst
  test_base_tier_validation/__init__.py
  test_base_tier_validation/__manifest__.py
  test_base_tier_validation/demo/tier_definition.xml
  test_base_tier_validation/i18n/test_base_tier_validation.pot
  test_base_tier_validation/models/__init__.py
  test_base_tier_validation/models/res_partner.py
  test_base_tier_validation/models/tier_definition.py
  test_base_tier_validation/readme/CONTRIBUTORS.rst
  test_base_tier_validation/readme/DESCRIPTION.rst
  test_base_tier_validation/static/description/icon.png
  test_base_tier_validation/static/description/index.html
  test_base_tier_validation/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#749 [16.0][PORT] 656 from 15.0
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: bot is merging ⏳

#750 [IMP][16.0] date_range: refactor calls to deprecated functions
  date_range/tests/test_date_range_search_mixin.py
  date_range/tests/test_date_range_type.py
  date_range/views/date_range_view.xml
Labels: bot is merging ⏳

#747 [16.0][IMP] base_tier_validation*: update test mechanism to support testing of messages
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation_forward/tests/test_tier_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#765 [16.0][IMP] date_range: refactor calls to deprecated functions
  date_range/tests/test_date_range_type.py
Labels: approved, bot is merging ⏳

#761 [17.0][MIG] base_technical_features: Migration to 17.0
  base_technical_features/README.rst
  base_technical_features/__init__.py
  base_technical_features/__manifest__.py
  base_technical_features/data/res_users.xml
  base_technical_features/i18n/am.po
  base_technical_features/i18n/ar.po
  base_technical_features/i18n/base_technical_features.pot
  base_technical_features/i18n/ca.po
  base_technical_features/i18n/da.po
  base_technical_features/i18n/de.po
  base_technical_features/i18n/el_GR.po
  base_technical_features/i18n/es.po
  base_technical_features/i18n/es_ES.po
  base_technical_features/i18n/es_MX.po
  base_technical_features/i18n/fi.po
  base_technical_features/i18n/fr.po
  base_technical_features/i18n/fr_CA.po
  base_technical_features/i18n/fr_CH.po
  base_technical_features/i18n/fr_FR.po
  base_technical_features/i18n/gl.po
  base_technical_features/i18n/hr.po
  base_technical_features/i18n/hr_HR.po
  base_technical_features/i18n/it.po
  base_technical_features/i18n/ja.po
  base_technical_features/i18n/nl.po
  base_technical_features/i18n/nl_NL.po
  base_technical_features/i18n/pt.po
  base_technical_features/i18n/pt_BR.po
  base_technical_features/i18n/pt_PT.po
  base_technical_features/i18n/ro.po
  base_technical_features/i18n/sl.po
  base_technical_features/i18n/tr.po
  base_technical_features/i18n/tr_TR.po
  base_technical_features/i18n/zh_CN.po
  base_technical_features/models/__init__.py
  base_technical_features/models/base.py
  base_technical_features/models/ir_ui_menu.py
  base_technical_features/models/res_users.py
  base_technical_features/pyproject.toml
  base_technical_features/readme/CONTRIBUTORS.md
  base_technical_features/readme/DESCRIPTION.md
  base_technical_features/readme/USAGE.md
  base_technical_features/security/res_groups.xml
  base_technical_features/static/description/icon.png
  base_technical_features/static/description/index.html
  base_technical_features/static/description/user_preferences.png
  base_technical_features/tests/__init__.py
  base_technical_features/tests/test_base_technical_features.py
  base_technical_features/views/res_users.xml
Labels: approved, ready to merge, bot is merging ⏳

#773 [15.0][FIX] mass_editing: fix error test
  mass_editing/tests/test_mass_editing.py
Labels: approved, bot is merging ⏳

#697 [15.0][MIG] sequence_check_digit: Migration to 15.0
  sequence_check_digit/README.rst
  sequence_check_digit/__init__.py
  sequence_check_digit/__manifest__.py
  sequence_check_digit/i18n/es.po
  sequence_check_digit/i18n/sequence_check_digit.pot
  sequence_check_digit/models/__init__.py
  sequence_check_digit/models/ir_sequence.py
  sequence_check_digit/readme/CONTRIBUTORS.rst
  sequence_check_digit/readme/DESCRIPTION.rst
  sequence_check_digit/readme/USAGE.rst
  sequence_check_digit/static/description/icon.png
  sequence_check_digit/static/description/index.html
  sequence_check_digit/tests/__init__.py
  sequence_check_digit/tests/test_check_digit.py
  sequence_check_digit/views/sequence_views.xml
  setup/sequence_check_digit/odoo/addons/sequence_check_digit
  setup/sequence_check_digit/setup.py
Labels: bot is merging ⏳, stale

#614 [16.0][mig] filter_multi_user: Migration to 16.0
  filter_multi_user/README.rst
  filter_multi_user/__init__.py
  filter_multi_user/__manifest__.py
  filter_multi_user/i18n/es.po
  filter_multi_user/i18n/filter_multi_user.pot
  filter_multi_user/models/__init__.py
  filter_multi_user/models/ir_filters.py
  filter_multi_user/readme/CONFIGURE.rst
  filter_multi_user/readme/CONTRIBUTORS.rst
  filter_multi_user/readme/DESCRIPTION.rst
  filter_multi_user/security/ir_filters_security.xml
  filter_multi_user/static/description/icon.png
  filter_multi_user/static/description/index.html
  filter_multi_user/tests/__init__.py
  filter_multi_user/tests/test_filter_multi_user.py
  filter_multi_user/views/ir_filters_view.xml
  setup/filter_multi_user/odoo/addons/filter_multi_user
  setup/filter_multi_user/setup.py
Labels: bot is merging ⏳, stale

#762 [15.0][IMP] base_tier_validation: Add _prepare_tier_review_vals() methot to allow inheritance
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
Labels: approved, ready to merge, bot is merging ⏳

#766 [16.0][IMP] base_tier_validation_forward: refactor calls to deprecated func…
  base_tier_validation_forward/tests/test_tier_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#770 [16.0][IMP] base_tier_validation_formula: update tests to support messages
  base_tier_validation_formula/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#769 [16.0][FIX]test_base_binary_url_import: unittests
  requirements.txt
  test_base_binary_url_import/README.rst
  test_base_binary_url_import/__manifest__.py
  test_base_binary_url_import/static/description/index.html
Labels: approved, bot is merging ⏳

#778 [16.0][IMP] base_tier_validation: test performance improvement
  base_tier_validation/tests/common.py
Labels: approved, bot is merging ⏳

#779 [16.0][IMP] filter_multi_user: refactor calls to deprecated functions
  filter_multi_user/tests/test_filter_multi_user.py
Labels: approved, bot is merging ⏳

#776 [16.0][IMP] base_tier_validation: Add _prepare_tier_review_vals() methot to allow inheritance
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
Labels: bot is merging ⏳
