Repository OCA/server-ux, pull requests merged in 2023-05, with the labels that each got.

#646 [15.0][FIX] base_tier_validation: Detect if model has active field
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/js/systray.js
  base_tier_validation/static/src/xml/systray.xml
Labels: approved, bot is merging ⏳

#433 [13.0] add base_binary_url_import
  base_binary_url_import/README.rst
  base_binary_url_import/__init__.py
  base_binary_url_import/__manifest__.py
  base_binary_url_import/data/ir_config_parameter.xml
  base_binary_url_import/readme/CONFIGURE.rst
  base_binary_url_import/readme/CONTRIBUTORS.rst
  base_binary_url_import/readme/DESCRIPTION.rst
  base_binary_url_import/readme/ROADMAP.rst
  base_binary_url_import/readme/USAGE.rst
  base_binary_url_import/wizard/__init__.py
  base_binary_url_import/wizard/base_binary_url_import.py
  base_binary_url_import/wizard/base_binary_url_import_view.xml
  requirements.txt
  setup/base_binary_url_import/odoo/addons/base_binary_url_import
  setup/base_binary_url_import/setup.py
  setup/test_base_binary_url_import/odoo/addons/test_base_binary_url_import
  setup/test_base_binary_url_import/setup.py
  test-requirements.txt
  test_base_binary_url_import/README.rst
  test_base_binary_url_import/__init__.py
  test_base_binary_url_import/__manifest__.py
  test_base_binary_url_import/demo/demo_test_binary.xml
  test_base_binary_url_import/models/__init__.py
  test_base_binary_url_import/models/test_binary.py
  test_base_binary_url_import/readme/CONTRIBUTORS.rst
  test_base_binary_url_import/readme/DESCRIPTION.rst
  test_base_binary_url_import/security/ir.model.access.csv
  test_base_binary_url_import/tests/__init__.py
  test_base_binary_url_import/tests/files/test.pdf
  test_base_binary_url_import/tests/files/test.txt
  test_base_binary_url_import/tests/test_binary_import.py
  test_base_binary_url_import/views/test_binary.xml
Labels: approved, ready to merge, bot is merging ⏳, no stale

#657 [14.0][FIX] base_custom_filter: Prevent all records from being displayed in favorites
  base_custom_filter/models/ir_filters.py
  base_custom_filter/tests/test_filters.py
Labels: approved, bot is merging ⏳

#652 [16.0][MIG] base_custom_filter: Migration to 16.0
  base_custom_filter/README.rst
  base_custom_filter/__init__.py
  base_custom_filter/__manifest__.py
  base_custom_filter/i18n/base_custom_filter.pot
  base_custom_filter/i18n/fr.po
  base_custom_filter/i18n/it.po
  base_custom_filter/models/__init__.py
  base_custom_filter/models/base.py
  base_custom_filter/models/ir_filters.py
  base_custom_filter/models/ir_filters_group.py
  base_custom_filter/readme/CONFIGURE.rst
  base_custom_filter/readme/CONTRIBUTORS.rst
  base_custom_filter/readme/DESCRIPTION.rst
  base_custom_filter/readme/USAGE.rst
  base_custom_filter/security/ir.model.access.csv
  base_custom_filter/static/description/icon.png
  base_custom_filter/static/description/index.html
  base_custom_filter/tests/__init__.py
  base_custom_filter/tests/test_filters.py
  base_custom_filter/views/ir_filters_group_views.xml
  base_custom_filter/views/ir_filters_views.xml
  setup/base_custom_filter/odoo/addons/base_custom_filter
  setup/base_custom_filter/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#654 [FIX] date_range : change license from AGPL-3 to LGPL-3, because l10n-france/l10n_fr_fec_oca/12.0 (LGPL) depends on date_range
  .github/workflows/test.yml
  date_range/__manifest__.py
Labels: approved, bot is merging ⏳
