Repository OCA/server-ux, pull requests merged in 2024-04, with the labels that each got.

#852 [16.0][MIG] announcement: Migration to 16.0
  announcement/README.rst
  announcement/__init__.py
  announcement/__manifest__.py
  announcement/demo/announcement_tag_demo.xml
  announcement/i18n/announcement.pot
  announcement/i18n/es.po
  announcement/models/__init__.py
  announcement/models/announcement.py
  announcement/models/announcement_tag.py
  announcement/models/ir_http.py
  announcement/models/res_users.py
  announcement/readme/CONFIGURE.rst
  announcement/readme/CONTRIBUTORS.rst
  announcement/readme/DESCRIPTION.rst
  announcement/readme/ROADMAP.rst
  announcement/readme/USAGE.rst
  announcement/security/announcement_security.xml
  announcement/security/ir.model.access.csv
  announcement/static/description/icon.png
  announcement/static/description/index.html
  announcement/static/src/js/announcement_dialog/announcement_dialog.esm.js
  announcement/static/src/js/announcement_menu/announcement_menu.esm.js
  announcement/static/src/js/announcement_menu/announcement_menu.xml
  announcement/static/src/js/announcement_service/announcement_service.esm.js
  announcement/views/announcement_tag_views.xml
  announcement/views/announcement_views.xml
  announcement/wizards/__init__.py
  announcement/wizards/read_announcement_wizard.py
  announcement/wizards/read_announcement_wizard.xml
  setup/announcement/odoo/addons/announcement
  setup/announcement/setup.py
Labels: approved, bot is merging ⏳

#856 [16.0][ADD] announcement_dialog_size: New module to be able to set announcement_dialog fullsized
  announcement_dialog_size/README.rst
  announcement_dialog_size/__init__.py
  announcement_dialog_size/__manifest__.py
  announcement_dialog_size/models/__init__.py
  announcement_dialog_size/models/announcement.py
  announcement_dialog_size/readme/CONFIGURE.rst
  announcement_dialog_size/readme/CONTRIBUTORS.rst
  announcement_dialog_size/readme/DESCRIPTION.rst
  announcement_dialog_size/static/description/index.html
  announcement_dialog_size/static/src/js/announcement_dialog/announcement_dialog.esm.js
  announcement_dialog_size/static/src/js/announcement_dialog/announcement_dialog.xml
  announcement_dialog_size/static/src/js/announcement_menu/announcement_menu.esm.js
  setup/announcement_dialog_size/odoo/addons/announcement_dialog_size
  setup/announcement_dialog_size/setup.py
Labels: approved, bot is merging ⏳

#853 [ADD] [15.0] base_warn_option
  base_warn_option/README.rst
  base_warn_option/__init__.py
  base_warn_option/__manifest__.py
  base_warn_option/i18n/base_warn_option.pot
  base_warn_option/i18n/es.po
  base_warn_option/models/__init__.py
  base_warn_option/models/warn_option.py
  base_warn_option/readme/CONTEXT.md
  base_warn_option/readme/CONTRIBUTORS.md
  base_warn_option/readme/DESCRIPTION.md
  base_warn_option/security/ir.model.access.csv
  base_warn_option/static/description/icon.png
  base_warn_option/static/description/index.html
  base_warn_option/views/res_config_settings_views.xml
  base_warn_option/views/warn_option_views.xml
  setup/base_warn_option/odoo/addons/base_warn_option
  setup/base_warn_option/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#782 [ADD] base_action_visibility_restriction_domain
  base_action_visibility_restriction_domain/README.rst
  base_action_visibility_restriction_domain/__init__.py
  base_action_visibility_restriction_domain/__manifest__.py
  base_action_visibility_restriction_domain/hooks.py
  base_action_visibility_restriction_domain/models/__init__.py
  base_action_visibility_restriction_domain/models/ir_actions.py
  base_action_visibility_restriction_domain/readme/CONTRIBUTORS.rst
  base_action_visibility_restriction_domain/readme/DESCRIPTION.rst
  base_action_visibility_restriction_domain/readme/USAGE.rst
  base_action_visibility_restriction_domain/security/ir.model.access.csv
  base_action_visibility_restriction_domain/tests/__init__.py
  base_action_visibility_restriction_domain/tests/test_base_action_visibility_restriction_domain.py
  base_action_visibility_restriction_domain/views/ir_actions_views.xml
  setup/base_action_visibility_restriction_domain/odoo/addons/base_action_visibility_restriction_domain
  setup/base_action_visibility_restriction_domain/setup.py
Labels: approved, bot is merging ⏳

#864 [17.0][FIX] base_tier_validation: prevent useless loop
  base_tier_validation/models/res_users.py
Labels: bot is merging ⏳

#851 [17.0][MIG] base_search_custom_field_filter: Migration to 17.0
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/i18n/base_search_custom_field_filter.pot
  base_search_custom_field_filter/i18n/es.po
  base_search_custom_field_filter/i18n/it.po
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/pyproject.toml
  base_search_custom_field_filter/readme/CONFIGURE.md
  base_search_custom_field_filter/readme/CONTRIBUTORS.md
  base_search_custom_field_filter/readme/DESCRIPTION.md
  base_search_custom_field_filter/readme/USAGE.md
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/icon.png
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/tests/__init__.py
  base_search_custom_field_filter/tests/test_filter.py
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
Labels: approved, ready to merge, bot is merging ⏳
