Repository OCA/server-ux, pull requests merged in 2024-10, with the labels that each got.

#952 [17.0][IMP] base_technical_features: Remove DeprecationWarning: XML declarations in HTML module descriptions
  base_technical_features/static/description/index.html
Labels: bot is merging ⏳

#950 [18.0][MIG] developer_menu: Migration to 18.0
  checklog-odoo.cfg
  developer_menu/README.rst
  developer_menu/__init__.py
  developer_menu/__manifest__.py
  developer_menu/i18n/developer_menu.pot
  developer_menu/i18n/it.po
  developer_menu/pyproject.toml
  developer_menu/readme/CONTRIBUTORS.md
  developer_menu/readme/DESCRIPTION.md
  developer_menu/readme/USAGE.md
  developer_menu/static/description/icon.png
  developer_menu/static/description/index.html
  developer_menu/static/description/menu.png
  developer_menu/views/menu_view.xml
Labels: approved, bot is merging ⏳

#949 [17.0][FIX] date_range: fix for cases when domain is not initialized
  date_range/static/src/js/tree_editor.esm.js
Labels: approved, bot is merging ⏳

#954 [17.0][FW] base_technical_features: port from 14.0
  .oca/oca-port/blacklist/base_technical_features.json
Labels: approved, ready to merge

#953 [18.0][MIG] base_technical_features: Migration to 18.0
  .oca/oca-port/blacklist/base_technical_features.json
  base_technical_features/README.rst
  base_technical_features/__init__.py
  base_technical_features/__manifest__.py
  base_technical_features/data/res_users.xml
  base_technical_features/i18n/am.po
  base_technical_features/i18n/ar.po
  base_technical_features/i18n/base_technical_features.pot
  base_technical_features/i18n/ca.po
  base_technical_features/i18n/da.po
  base_technical_features/i18n/de.po
  base_technical_features/i18n/el_GR.po
  base_technical_features/i18n/es.po
  base_technical_features/i18n/es_ES.po
  base_technical_features/i18n/es_MX.po
  base_technical_features/i18n/fi.po
  base_technical_features/i18n/fr.po
  base_technical_features/i18n/fr_CA.po
  base_technical_features/i18n/fr_CH.po
  base_technical_features/i18n/fr_FR.po
  base_technical_features/i18n/gl.po
  base_technical_features/i18n/hr.po
  base_technical_features/i18n/hr_HR.po
  base_technical_features/i18n/it.po
  base_technical_features/i18n/ja.po
  base_technical_features/i18n/nl.po
  base_technical_features/i18n/nl_NL.po
  base_technical_features/i18n/pt.po
  base_technical_features/i18n/pt_BR.po
  base_technical_features/i18n/pt_PT.po
  base_technical_features/i18n/ro.po
  base_technical_features/i18n/sl.po
  base_technical_features/i18n/tr.po
  base_technical_features/i18n/tr_TR.po
  base_technical_features/i18n/zh_CN.po
  base_technical_features/models/__init__.py
  base_technical_features/models/base.py
  base_technical_features/models/ir_ui_menu.py
  base_technical_features/models/res_users.py
  base_technical_features/pyproject.toml
  base_technical_features/readme/CONTRIBUTORS.md
  base_technical_features/readme/CREDITS.md
  base_technical_features/readme/DESCRIPTION.md
  base_technical_features/readme/USAGE.md
  base_technical_features/security/res_groups.xml
  base_technical_features/static/description/icon.png
  base_technical_features/static/description/index.html
  base_technical_features/static/description/user_preferences.png
  base_technical_features/tests/__init__.py
  base_technical_features/tests/test_base_technical_features.py
  base_technical_features/views/res_users.xml
Labels: approved, ready to merge, bot is merging ⏳

#939 [17.0][IMP] base_tier_validation: support computed state field
  base_tier_validation/README.rst
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONTRIBUTORS.md
  base_tier_validation/readme/DESCRIPTION.md
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
Labels: approved, ready to merge, bot is merging ⏳

#959 [17.0][FIX] base_tier_validation: amend authors
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/static/description/index.html
Labels: bot is merging ⏳

#960 [14.0][FIX] base_tier_validation reminder option
  base_tier_validation/models/tier_review.py
Labels: approved, bot is merging ⏳, Pending to fw/back port
