Repository OCA/server-ux, pull requests merged in 2024-07, with the labels that each got.

#903 [IMP] document_quick_access_folder_auto_classification: Remove edi_storage_oca unnecessary dependancy
  document_quick_access_folder_auto_classification/README.rst
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/data/edi_data.xml
  document_quick_access_folder_auto_classification/readme/CONFIGURE.rst
  document_quick_access_folder_auto_classification/static/description/index.html
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
Labels: bot is merging ⏳

#910 [17.0][FIX] date_range: fix web ribbon
  date_range/views/date_range_view.xml
Labels: approved, bot is merging ⏳

#873 [14.0][IMP] Add reminder to base_tier_validation
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/data/cron_data.xml
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/__init__.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation_reminder.py
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#898 [16.0][FIX] base_cancel_confirm: correct get_view method
  base_cancel_confirm/model/base_cancel_confirm.py
  base_cancel_confirm/tests/test_cancel_confirm.py
Labels: approved, bot is merging ⏳

#921 [16.0][FIX] base_tier_validation, base_export_manager, add sudo call to models without explicit access
  base_export_manager/models/ir_exports_line.py
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_validation_exception.py
Labels: approved, bot is merging ⏳, Pending to fw/back port

#905 [FWP] [17.0] OCA-PORT PRs 802 860 888 902 921
  .oca/oca-port/blacklist/base_tier_validation.json
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/models/__init__.py
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/models/tier_validation_exception.py
  base_tier_validation/readme/CONTRIBUTORS.md
  base_tier_validation/security/ir.model.access.csv
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation/views/tier_definition_view.xml
  base_tier_validation/views/tier_validation_exception_view.xml
Labels: bot is merging ⏳

#899 [16.0][FIX] base_tier_validation, search only active definitions
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳, Pending to fw/back port

#915 [FIX] [16.0] base_tier_validation: Tier Validation Exception Groups
  base_tier_validation/README.rst
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/models/tier_validation.py
  base_tier_validation/models/tier_validation_exception.py
  base_tier_validation/readme/CONFIGURE.rst
  base_tier_validation/static/description/index.html
  base_tier_validation/templates/tier_validation_templates.xml
  base_tier_validation/views/tier_validation_exception_view.xml
Labels: approved, ready to merge, bot is merging ⏳, Pending to fw/back port

#797 [MIG][17.0] multi_step_wizard: Migration to 17.0
  multi_step_wizard/README.rst
  multi_step_wizard/__init__.py
  multi_step_wizard/__manifest__.py
  multi_step_wizard/i18n/ca.po
  multi_step_wizard/i18n/de.po
  multi_step_wizard/i18n/es.po
  multi_step_wizard/i18n/hr.po
  multi_step_wizard/i18n/it.po
  multi_step_wizard/i18n/multi_step_wizard.pot
  multi_step_wizard/i18n/nl.po
  multi_step_wizard/i18n/zh_CN.po
  multi_step_wizard/models/__init__.py
  multi_step_wizard/models/multi_step_wizard.py
  multi_step_wizard/pyproject.toml
  multi_step_wizard/readme/CONTRIBUTORS.md
  multi_step_wizard/readme/DESCRIPTION.md
  multi_step_wizard/readme/USAGE.md
  multi_step_wizard/static/description/icon.png
  multi_step_wizard/static/description/index.html
  multi_step_wizard/tests/__init__.py
  multi_step_wizard/tests/common.py
  multi_step_wizard/tests/multi_step_wizard_test.py
  multi_step_wizard/tests/test_multi_step_wizard.py
  multi_step_wizard/views/multi_step_wizard_views.xml
Labels: approved, bot is merging ⏳

#919 [FWP][15.0] base_tier_validation: Add reminder option
  base_tier_validation/__manifest__.py
  base_tier_validation/data/cron_data.xml
  base_tier_validation/data/mail_data.xml
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/__init__.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation_reminder.py
  base_tier_validation/views/tier_definition_view.xml
Labels: bot is merging ⏳

#925 [17.0][FIX] base_tier_validation, search only active definitions
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#846 [16.0][FIX] base_tier_validation: Field merge in view
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONTRIBUTORS.rst
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#926 [17.0][FIX] base_tier_validation: Tier Validation Exception Groups
  base_tier_validation/README.rst
  base_tier_validation/models/tier_validation.py
  base_tier_validation/models/tier_validation_exception.py
  base_tier_validation/readme/CONFIGURE.md
  base_tier_validation/static/description/index.html
  base_tier_validation/views/tier_validation_exception_view.xml
Labels: bot is merging ⏳

#927 [17.0][IMP] base_tier_validation: Fix same label warning
  base_tier_validation/models/tier_validation_exception.py
Labels: bot is merging ⏳

#932 [17.0][FIX] base_tier_validation: Field merge in view
  base_tier_validation/README.rst
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONTRIBUTORS.md
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳
