Repository OCA/server-ux, pull requests merged in 2024-01, with the labels that each got.

#792 [FIX] base_archive_security: skip check on empty recordset Also, allow to bypass through a special context key
  base_archive_security/models/base.py
Labels: bot is merging ⏳

#788 [16.0][MIG] base_tier_validation_server_action
  base_tier_validation_server_action/README.rst
  base_tier_validation_server_action/__init__.py
  base_tier_validation_server_action/__manifest__.py
  base_tier_validation_server_action/data/cron_data.xml
  base_tier_validation_server_action/i18n/base_tier_validation_server_action.pot
  base_tier_validation_server_action/i18n/es.po
  base_tier_validation_server_action/models/__init__.py
  base_tier_validation_server_action/models/tier_definition.py
  base_tier_validation_server_action/models/tier_validation.py
  base_tier_validation_server_action/readme/CONFIGURE.rst
  base_tier_validation_server_action/readme/CONTRIBUTORS.rst
  base_tier_validation_server_action/readme/DESCRIPTION.rst
  base_tier_validation_server_action/static/description/icon.png
  base_tier_validation_server_action/static/description/index.html
  base_tier_validation_server_action/tests/__init__.py
  base_tier_validation_server_action/tests/test_tier_validation.py
  base_tier_validation_server_action/tests/tier_validation_tester.py
  base_tier_validation_server_action/views/tier_definition_view.xml
  setup/base_tier_validation_server_action/odoo/addons/base_tier_validation_server_action
  setup/base_tier_validation_server_action/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#724 [FIX] base_tier_validation: field is edtitable
  base_tier_validation/templates/tier_validation_templates.xml
Labels: approved, bot is merging ⏳

#798 [17.0] server-ux: copier repo update
  .copier-answers.yml
  .pre-commit-config.yaml
  .ruff.toml
  base_tier_validation/models/tier_definition.py
Labels: bot is merging ⏳

#801 [15.0][PORT] 699 from 14.0: base_tier_validation multiple comment with approve_sequence_bypass
  base_tier_validation/models/tier_validation.py
Labels: bot is merging ⏳

#802 [16.0][PORT] 699 from 14.0: base_tier_validation multiple comment with approve_sequence_bypass
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#799 [MIG] base_tier_validation_formula: Migrate to version 17.0
  base_tier_validation/models/res_config_settings.py
  base_tier_validation/views/res_config_settings_views.xml
  base_tier_validation_formula/README.rst
  base_tier_validation_formula/__init__.py
  base_tier_validation_formula/__manifest__.py
  base_tier_validation_formula/i18n/base_tier_validation_formula.pot
  base_tier_validation_formula/i18n/es.po
  base_tier_validation_formula/i18n/it.po
  base_tier_validation_formula/i18n/zh_CN.po
  base_tier_validation_formula/models/__init__.py
  base_tier_validation_formula/models/tier_definition.py
  base_tier_validation_formula/models/tier_review.py
  base_tier_validation_formula/models/tier_validation.py
  base_tier_validation_formula/pyproject.toml
  base_tier_validation_formula/readme/CONTRIBUTORS.md
  base_tier_validation_formula/readme/CREDITS.md
  base_tier_validation_formula/readme/DESCRIPTION.md
  base_tier_validation_formula/readme/USAGE.md
  base_tier_validation_formula/static/description/icon.png
  base_tier_validation_formula/static/description/index.html
  base_tier_validation_formula/tests/__init__.py
  base_tier_validation_formula/tests/test_tier_validation.py
  base_tier_validation_formula/views/tier_definition_view.xml
Labels: bot is merging ⏳

#711 [16.0][ADD] server_action_mass_edit: add support for o2m fields
  server_action_mass_edit/demo/mass_editing.xml
  server_action_mass_edit/tests/test_mass_editing.py
  server_action_mass_edit/wizard/mass_editing_wizard.py
Labels: bot is merging ⏳, stale

#794 [14.0][IMP] base_tier_validation/server_action: Improve flow for validation conditions
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/migrations/14.0.3.0.0/pre-migrate.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/description/index.html
  base_tier_validation_server_action/models/tier_review.py
  base_tier_validation_server_action/models/tier_validation.py
Labels: approved, bot is merging ⏳

#812 [15.0][FIX] base_tier_validation: Change web_ribbon text to title to make it translatable
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#813 [16.0][FIX] base_tier_validation: Change web_ribbon text to title to make it translatable
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#815 [17.0][FIX] base_tier_validation: Change web_ribbon text to title to make it translatable
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳
