Repository OCA/server-ux, pull requests merged in 2024-02, with the labels that each got.

#800 [17.0][IMP] base_tier_validation: Merge module with base_tier_validation_waiting
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONFIGURE.md
  base_tier_validation/readme/CONTRIBUTORS.md
  base_tier_validation/readme/HISTORY.md
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#823 [17.0] repo update repo descirption
  .copier-answers.yml
  README.md
Labels: bot is merging ⏳

#804 [17.0] base_tier_validation Improve UI
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/src/components/tier_review_menu/tier_review_menu.esm.js
  base_tier_validation/static/src/components/tier_review_menu/tier_review_menu.xml
  base_tier_validation/static/src/components/tier_review_widget/tier_review_widget.xml
  base_tier_validation/templates/tier_validation_templates.xml
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#810 [16.0][FIX][base_tier_validation] fix validation date timezone
  base_tier_validation/models/tier_review.py
  base_tier_validation/readme/CONTRIBUTORS.rst
Labels: needs review, approved, bot is merging ⏳

#827 [17.0] 810 port base_tier_validation: fix validation date timezone
  base_tier_validation/models/tier_review.py
  base_tier_validation/readme/CONTRIBUTORS.md
Labels: approved, bot is merging ⏳

#828 [16.0][FIX] server_action_mass_edit: 'Add' readded to many2many
  server_action_mass_edit/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳

#833 [16.0][ADD] template_content_swapper
  setup/template_content_swapper/odoo/addons/template_content_swapper
  setup/template_content_swapper/setup.py
  template_content_swapper/README.rst
  template_content_swapper/__init__.py
  template_content_swapper/__manifest__.py
  template_content_swapper/models/__init__.py
  template_content_swapper/models/ir_ui_view.py
  template_content_swapper/models/template_content_mapping.py
  template_content_swapper/readme/CONFIGURE.rst
  template_content_swapper/readme/CONTRIBUTORS.rst
  template_content_swapper/readme/DESCRIPTION.rst
  template_content_swapper/readme/USAGE.rst
  template_content_swapper/security/ir.model.access.csv
  template_content_swapper/static/description/index.html
  template_content_swapper/static/img/login_after.png
  template_content_swapper/static/img/login_before.png
  template_content_swapper/static/img/mapping.png
  template_content_swapper/tests/__init__.py
  template_content_swapper/tests/test_template_content_swapper.py
  template_content_swapper/views/template_content_mapping_views.xml
Labels: bot is merging ⏳

#629 [IMP] document_quick_access_folder_auto_classification: Add Python-OpenCV as backup check
  document_quick_access_folder_auto_classification/components/document_quick_access_process.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
  test-requirements.txt
Labels: approved, bot is merging ⏳
