Repository OCA/server-ux, pull requests merged in 2024-08, with the labels that each got.

#930 [16.0][FIX] base_tier_validation_forward: Tier review sequence should be an integer
  base_tier_validation_forward/models/tier_review.py
Labels: approved, ready to merge, bot is merging ⏳

#912 [MIG] base_tier_validation_forward: Migration to 17.0
  base_tier_validation_forward/README.rst
  base_tier_validation_forward/__init__.py
  base_tier_validation_forward/__manifest__.py
  base_tier_validation_forward/data/mail_data.xml
  base_tier_validation_forward/hooks.py
  base_tier_validation_forward/i18n/base_tier_validation_forward.pot
  base_tier_validation_forward/i18n/es.po
  base_tier_validation_forward/i18n/it.po
  base_tier_validation_forward/models/__init__.py
  base_tier_validation_forward/models/tier_definition.py
  base_tier_validation_forward/models/tier_review.py
  base_tier_validation_forward/models/tier_validation.py
  base_tier_validation_forward/pyproject.toml
  base_tier_validation_forward/readme/CONFIGURE.md
  base_tier_validation_forward/readme/CONTRIBUTORS.md
  base_tier_validation_forward/readme/DESCRIPTION.md
  base_tier_validation_forward/security/ir.model.access.csv
  base_tier_validation_forward/static/description/icon.png
  base_tier_validation_forward/static/description/index.html
  base_tier_validation_forward/static/src/xml/tier_review_template.xml
  base_tier_validation_forward/templates/tier_validation_templates.xml
  base_tier_validation_forward/tests/__init__.py
  base_tier_validation_forward/tests/test_tier_validation.py
  base_tier_validation_forward/views/tier_definition_view.xml
  base_tier_validation_forward/wizard/__init__.py
  base_tier_validation_forward/wizard/comment_wizard.py
  base_tier_validation_forward/wizard/forward_wizard.py
  base_tier_validation_forward/wizard/forward_wizard_view.xml
Labels: approved, bot is merging ⏳

#933 [16.0][IMP] announcement: Also show archived users.
  announcement/models/announcement.py
Labels: approved, bot is merging ⏳

#938 [FIX] base_tier_validation: warning on install
  base_tier_validation/models/tier_validation_exception.py
Labels: bot is merging ⏳

#824 [17.0][RFC] base_tier_validation: remove unused code
  base_tier_validation/models/res_users.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳
