Repository OCA/server-ux, pull requests merged in 2024-06, with the labels that each got.

#880 [17.0] [FIX] date_range: fix Translated stored related field warning
  date_range/models/date_range.py
  date_range/models/date_range_type.py
Labels: approved, ready to merge, bot is merging ⏳

#890 ADD module misc_settings
  misc_settings/README.rst
  misc_settings/__init__.py
  misc_settings/__manifest__.py
  misc_settings/i18n/fr.po
  misc_settings/i18n/misc_settings.pot
  misc_settings/readme/CONFIGURE.rst
  misc_settings/readme/CONTRIBUTORS.rst
  misc_settings/readme/DESCRIPTION.rst
  misc_settings/static/description/index.html
  misc_settings/static/description/screen.png
  misc_settings/views/res_config_settings.xml
  setup/misc_settings/odoo/addons/misc_settings
  setup/misc_settings/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#888 [16.0][IMP] configurable domain for readonly fields in validation
  base_tier_validation/models/tier_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#892 [FIX] date_range: fix README image urls
  date_range/README.rst
Labels: approved, ready to merge, bot is merging ⏳

#901 [15.0][FIX] default_multi_user: incorrectly keeping cache after company switch
  default_multi_user/hooks.py
  default_multi_user/tests/test_default_multi_user.py
Labels: approved, bot is merging ⏳

#817 [16.0][ADD] base_tier_validation_board
  base_tier_validation_board/README.rst
  base_tier_validation_board/__init__.py
  base_tier_validation_board/__manifest__.py
  base_tier_validation_board/models/__init__.py
  base_tier_validation_board/models/tier_review.py
  base_tier_validation_board/readme/CONTRIBUTORS.rst
  base_tier_validation_board/readme/DESCRIPTION.rst
  base_tier_validation_board/readme/USAGE.rst
  base_tier_validation_board/security/groups.xml
  base_tier_validation_board/static/description/index.html
  base_tier_validation_board/views/tier_review_view.xml
  setup/base_tier_validation_board/odoo/addons/base_tier_validation_board
  setup/base_tier_validation_board/setup.py
Labels: approved, bot is merging ⏳, stale

#902 [FIX] [16.0] base_tier_validation: Tier Validation Exceptions
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/i18n/base_tier_validation.pot
  base_tier_validation/i18n/es.po
  base_tier_validation/models/__init__.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/models/tier_validation_exception.py
  base_tier_validation/readme/CONFIGURE.rst
  base_tier_validation/readme/CONTRIBUTORS.rst
  base_tier_validation/security/ir.model.access.csv
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
  base_tier_validation/views/tier_definition_view.xml
  base_tier_validation/views/tier_validation_exception_view.xml
Labels: approved, bot is merging ⏳

#904 [ADD] [16.0] mail_message_destiny_link_template
  mail_message_destiny_link_template/README.rst
  mail_message_destiny_link_template/__init__.py
  mail_message_destiny_link_template/__manifest__.py
  mail_message_destiny_link_template/data/mail_templates_chatter.xml
  mail_message_destiny_link_template/i18n/es.po
  mail_message_destiny_link_template/i18n/mail_message_destiny_link_template.pot
  mail_message_destiny_link_template/readme/CONTEXT.md
  mail_message_destiny_link_template/readme/CONTRIBUTORS.md
  mail_message_destiny_link_template/readme/DESCRIPTION.md
  mail_message_destiny_link_template/readme/USAGE.md
  mail_message_destiny_link_template/static/description/icon.png
  mail_message_destiny_link_template/static/description/index.html
  setup/mail_message_destiny_link_template/odoo/addons/mail_message_destiny_link_template
  setup/mail_message_destiny_link_template/setup.py
Labels: approved, bot is merging ⏳

#774 [16.0][MIG] document_quick_access: Migration to 16.0
  document_quick_access/README.rst
  document_quick_access/__init__.py
  document_quick_access/__manifest__.py
  document_quick_access/i18n/document_quick_access.pot
  document_quick_access/i18n/es.po
  document_quick_access/models/__init__.py
  document_quick_access/models/base.py
  document_quick_access/models/document_quick_access_rule.py
  document_quick_access/readme/CONFIGURE.rst
  document_quick_access/readme/CONTRIBUTORS.rst
  document_quick_access/readme/DESCRIPTION.rst
  document_quick_access/readme/ROADMAP.rst
  document_quick_access/readme/USAGE.rst
  document_quick_access/security/ir.model.access.csv
  document_quick_access/static/description/icon.png
  document_quick_access/static/description/index.html
  document_quick_access/static/src/js/document_quick_access_launcher.js
  document_quick_access/static/src/xml/document_quick_access_launcher.xml
  document_quick_access/tests/__init__.py
  document_quick_access/tests/test_document_quick_access.py
  document_quick_access/views/document_quick_access_rule.xml
  requirements.txt
  setup/document_quick_access/odoo/addons/document_quick_access
  setup/document_quick_access/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#835 [FIX] mass_editing : Prevent to crash if the module is installed, but if there are no data
  mass_editing/migrations/13.0.1.0.0/post-migration.py
Labels: bot is merging ⏳, stale
