Repository OCA/server-ux, pull requests merged in 2024-03, with the labels that each got.

#834 [16.0] [IMP] base_tier_validation: Block notifications
  base_tier_validation/README.rst
  base_tier_validation/models/tier_definition.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/readme/CONTRIBUTORS.rst
  base_tier_validation/static/description/index.html
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#830 [FIX]base_tier_validation: Selection Field translated
  base_tier_validation/models/tier_review.py
  base_tier_validation/static/src/xml/tier_review_template.xml
  base_tier_validation/templates/tier_validation_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#839 [FIX][17.0]base_tier_validation: Selection Field translated
  base_tier_validation/models/tier_review.py
  base_tier_validation/static/src/components/tier_review_widget/tier_review_widget.xml
  base_tier_validation/templates/tier_validation_templates.xml
Labels: bot is merging ⏳

#841 [DOC] date_range: Update broken image links
  date_range/readme/CONFIGURE.rst
  date_range/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#844 [16.0][DOC] date_range: Update broken image links.
  date_range/readme/CONFIGURE.rst
  date_range/readme/USAGE.rst
Labels: bot is merging ⏳

#837 [17.0][MIG] sequence_reset_period: Migration to 17.0
  sequence_reset_period/README.rst
  sequence_reset_period/__init__.py
  sequence_reset_period/__manifest__.py
  sequence_reset_period/i18n/es.po
  sequence_reset_period/i18n/fr_FR.po
  sequence_reset_period/i18n/hr.po
  sequence_reset_period/i18n/it.po
  sequence_reset_period/i18n/sequence_reset_period.pot
  sequence_reset_period/i18n/zh_CN.po
  sequence_reset_period/models/__init__.py
  sequence_reset_period/models/ir_sequence.py
  sequence_reset_period/pyproject.toml
  sequence_reset_period/readme/CONTRIBUTORS.md
  sequence_reset_period/readme/DESCRIPTION.md
  sequence_reset_period/readme/USAGE.md
  sequence_reset_period/static/description/icon.png
  sequence_reset_period/static/description/index.html
  sequence_reset_period/tests/__init__.py
  sequence_reset_period/tests/test_period.py
  sequence_reset_period/views/sequence_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#848 [16.0] [FIX] base_tier_validation: Wrong var name replacement
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳
