Repository OCA/server-ux, pull requests merged in 2024-09, with the labels that each got.

#935 [17.0][MIG] announcement: Migration to 17.0
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  .pre-commit-config.yaml
  announcement/README.rst
  announcement/__init__.py
  announcement/__manifest__.py
  announcement/demo/announcement_tag_demo.xml
  announcement/i18n/announcement.pot
  announcement/i18n/es.po
  announcement/i18n/it.po
  announcement/models/__init__.py
  announcement/models/announcement.py
  announcement/models/announcement_tag.py
  announcement/models/ir_http.py
  announcement/models/res_users.py
  announcement/pyproject.toml
  announcement/readme/CONFIGURE.md
  announcement/readme/CONTRIBUTORS.md
  announcement/readme/DESCRIPTION.md
  announcement/readme/ROADMAP.md
  announcement/readme/USAGE.md
  announcement/security/announcement_security.xml
  announcement/security/ir.model.access.csv
  announcement/static/description/icon.png
  announcement/static/description/index.html
  announcement/static/src/js/announcement_dialog/announcement_dialog.esm.js
  announcement/static/src/js/announcement_menu/announcement_menu.esm.js
  announcement/static/src/js/announcement_menu/announcement_menu.xml
  announcement/static/src/js/announcement_service/announcement_service.esm.js
  announcement/views/announcement_tag_views.xml
  announcement/views/announcement_views.xml
  announcement/wizards/__init__.py
  announcement/wizards/read_announcement_wizard.py
  announcement/wizards/read_announcement_wizard.xml
Labels: approved, bot is merging ⏳

#943 [17.0][FIX] server_action_mess_edit: Application error when discard a x2many field
  server_action_mass_edit/static/src/js/static_list.esm.js
Labels: approved, ready to merge, bot is merging ⏳

#866 [17.0][MIG] barcode_action: Migration to 17.0
  barcode_action/README.rst
  barcode_action/__init__.py
  barcode_action/__manifest__.py
  barcode_action/demo/barcode_action_demo.xml
  barcode_action/i18n/barcode_action.pot
  barcode_action/i18n/es.po
  barcode_action/i18n/hr.po
  barcode_action/i18n/it.po
  barcode_action/i18n/pt.po
  barcode_action/i18n/zh_CN.po
  barcode_action/models/__init__.py
  barcode_action/models/res_partner.py
  barcode_action/pyproject.toml
  barcode_action/readme/CONTRIBUTORS.md
  barcode_action/readme/DESCRIPTION.md
  barcode_action/readme/USAGE.md
  barcode_action/security/ir.model.access.csv
  barcode_action/static/description/icon.png
  barcode_action/static/description/index.html
  barcode_action/static/src/js/action_barcode_widget.esm.js
  barcode_action/tests/__init__.py
  barcode_action/tests/test_partner_find.py
  barcode_action/wizard/__init__.py
  barcode_action/wizard/barcode_action.py
  barcode_action/wizard/barcode_action_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#940 [17.0][MIG] base_substate: Migration to 17.0
  base_substate/README.rst
  base_substate/__init__.py
  base_substate/__manifest__.py
  base_substate/i18n/base_substate.pot
  base_substate/i18n/es.po
  base_substate/i18n/it.po
  base_substate/models/__init__.py
  base_substate/models/base_substate.py
  base_substate/models/base_substate_mixin.py
  base_substate/pyproject.toml
  base_substate/readme/CONTRIBUTORS.md
  base_substate/readme/DESCRIPTION.md
  base_substate/readme/USAGE.md
  base_substate/security/base_substate_security.xml
  base_substate/security/ir.model.access.csv
  base_substate/static/description/icon.png
  base_substate/static/description/index.html
  base_substate/tests/__init__.py
  base_substate/tests/models_mixin.py
  base_substate/tests/sale_test.py
  base_substate/tests/test_base_substate.py
  base_substate/views/base_substate_type_views.xml
  base_substate/views/base_substate_value_views.xml
  base_substate/views/base_substate_views.xml
Labels: approved, bot is merging ⏳

#879 [MIG] base_menu_visibility_restriction: Migration to 17.0
  base_menu_visibility_restriction/README.rst
  base_menu_visibility_restriction/__init__.py
  base_menu_visibility_restriction/__manifest__.py
  base_menu_visibility_restriction/i18n/base_menu_visibility_restriction.pot
  base_menu_visibility_restriction/i18n/es.po
  base_menu_visibility_restriction/i18n/it.po
  base_menu_visibility_restriction/models/__init__.py
  base_menu_visibility_restriction/models/ir_ui_menu.py
  base_menu_visibility_restriction/pyproject.toml
  base_menu_visibility_restriction/readme/CONTRIBUTORS.md
  base_menu_visibility_restriction/readme/DESCRIPTION.md
  base_menu_visibility_restriction/readme/USAGE.md
  base_menu_visibility_restriction/static/description/icon.png
  base_menu_visibility_restriction/static/description/index.html
  base_menu_visibility_restriction/tests/__init__.py
  base_menu_visibility_restriction/tests/test_ir_ui_menu.py
  base_menu_visibility_restriction/views/ir_ui_menu.xml
Labels: approved, ready to merge, bot is merging ⏳

#946 [17.0][IMP] server_action_mass_editing : Improve documentation during OCA Days 2024 Workshop thanks to @…
  server_action_mass_edit/readme/CONFIGURE.md
  server_action_mass_edit/readme/DESCRIPTION.md
Labels: needs review, approved, bot is merging ⏳
