Repository OCA/server-ux, pull requests merged in 2025-05, with the labels that each got.

#1069 [16.0][IMP] base_tier_validation: Add message_main_attachment_id field to BASE_EXCEPTION_FIELDS
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#1053 [15.0][FIX] base_tier_validation: request tier with multi-company
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
Labels: bot is merging ⏳

#1065 [18.0][MIG] base_tier_validation_forward
  base_tier_validation_forward/README.rst
  base_tier_validation_forward/__init__.py
  base_tier_validation_forward/__manifest__.py
  base_tier_validation_forward/data/mail_data.xml
  base_tier_validation_forward/hooks.py
  base_tier_validation_forward/i18n/base_tier_validation_forward.pot
  base_tier_validation_forward/i18n/es.po
  base_tier_validation_forward/i18n/it.po
  base_tier_validation_forward/models/__init__.py
  base_tier_validation_forward/models/tier_definition.py
  base_tier_validation_forward/models/tier_review.py
  base_tier_validation_forward/models/tier_validation.py
  base_tier_validation_forward/pyproject.toml
  base_tier_validation_forward/readme/CONFIGURE.md
  base_tier_validation_forward/readme/CONTRIBUTORS.md
  base_tier_validation_forward/readme/DESCRIPTION.md
  base_tier_validation_forward/security/ir.model.access.csv
  base_tier_validation_forward/static/description/icon.png
  base_tier_validation_forward/static/description/index.html
  base_tier_validation_forward/static/src/xml/tier_review_template.xml
  base_tier_validation_forward/templates/tier_validation_templates.xml
  base_tier_validation_forward/tests/__init__.py
  base_tier_validation_forward/tests/test_tier_validation.py
  base_tier_validation_forward/views/tier_definition_view.xml
  base_tier_validation_forward/wizard/__init__.py
  base_tier_validation_forward/wizard/comment_wizard.py
  base_tier_validation_forward/wizard/forward_wizard.py
  base_tier_validation_forward/wizard/forward_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1044 [18.0][FIX] base_tier_validation: Ensure valid recordset assignment in _compute_domain_reviewer_field
  base_tier_validation/models/tier_definition.py
Labels: approved, bot is merging ⏳

#1017 [18.0][MIG] base_search_custom_field_filter: Migration to 18.0
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__init__.py
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/demo/demo_ir_ui_custom_field_filter.xml
  base_search_custom_field_filter/i18n/base_search_custom_field_filter.pot
  base_search_custom_field_filter/i18n/es.po
  base_search_custom_field_filter/i18n/it.po
  base_search_custom_field_filter/models/__init__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/models/ir_ui_custom_field_filter.py
  base_search_custom_field_filter/pyproject.toml
  base_search_custom_field_filter/readme/CONFIGURE.md
  base_search_custom_field_filter/readme/CONTRIBUTORS.md
  base_search_custom_field_filter/readme/DESCRIPTION.md
  base_search_custom_field_filter/readme/USAGE.md
  base_search_custom_field_filter/security/ir.model.access.csv
  base_search_custom_field_filter/static/description/icon.png
  base_search_custom_field_filter/static/description/index.html
  base_search_custom_field_filter/static/src/img/contact_search.png
  base_search_custom_field_filter/static/src/img/ir_ui_custom_field_filter.png
  base_search_custom_field_filter/tests/__init__.py
  base_search_custom_field_filter/tests/test_filter.py
  base_search_custom_field_filter/views/ir_ui_custom_field_filter_views.xml
Labels: approved, bot is merging ⏳

#1076 [18.0][IMP] base_tier_validation: Allow attachment generation after validation
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#989 [18.0][MIG] base_optional_quick_create: Migration to 18.0
  base_optional_quick_create/README.rst
  base_optional_quick_create/__init__.py
  base_optional_quick_create/__manifest__.py
  base_optional_quick_create/i18n/base_optional_quick_create.pot
  base_optional_quick_create/i18n/de.po
  base_optional_quick_create/i18n/es.po
  base_optional_quick_create/i18n/fi.po
  base_optional_quick_create/i18n/fr.po
  base_optional_quick_create/i18n/hr.po
  base_optional_quick_create/i18n/hr_HR.po
  base_optional_quick_create/i18n/it.po
  base_optional_quick_create/i18n/ja.po
  base_optional_quick_create/i18n/nb_NO.po
  base_optional_quick_create/i18n/pt_BR.po
  base_optional_quick_create/i18n/sl.po
  base_optional_quick_create/i18n/tr.po
  base_optional_quick_create/i18n/tr_TR.po
  base_optional_quick_create/i18n/zh_CN.po
  base_optional_quick_create/models/__init__.py
  base_optional_quick_create/models/ir_model.py
  base_optional_quick_create/pyproject.toml
  base_optional_quick_create/readme/CONTRIBUTORS.md
  base_optional_quick_create/readme/CREDITS.md
  base_optional_quick_create/readme/DESCRIPTION.md
  base_optional_quick_create/readme/USAGE.md
  base_optional_quick_create/static/description/icon.png
  base_optional_quick_create/static/description/index.html
  base_optional_quick_create/tests/__init__.py
  base_optional_quick_create/tests/test_quick_create.py
  base_optional_quick_create/views/model_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1010 [17.0][MIG] base_import_security_group
  base_import_security_group/README.rst
  base_import_security_group/__init__.py
  base_import_security_group/__manifest__.py
  base_import_security_group/i18n/base_import_security_group.pot
  base_import_security_group/i18n/ca.po
  base_import_security_group/i18n/de.po
  base_import_security_group/i18n/es.po
  base_import_security_group/i18n/fr.po
  base_import_security_group/i18n/gl.po
  base_import_security_group/i18n/hr.po
  base_import_security_group/i18n/it.po
  base_import_security_group/i18n/pt.po
  base_import_security_group/i18n/sk.po
  base_import_security_group/models/__init__.py
  base_import_security_group/models/base.py
  base_import_security_group/models/ir_http.py
  base_import_security_group/pyproject.toml
  base_import_security_group/readme/CONTRIBUTORS.md
  base_import_security_group/readme/DESCRIPTION.md
  base_import_security_group/security/base_import_security_group_security.xml
  base_import_security_group/static/description/icon.png
  base_import_security_group/static/description/icon.svg
  base_import_security_group/static/description/index.html
  base_import_security_group/static/src/js/import.esm.js
  base_import_security_group/static/src/js/tour_import.esm.js
  base_import_security_group/tests/__init__.py
  base_import_security_group/tests/test_base_import_security_group.py
Labels: approved, bot is merging ⏳

#1011 [18.0][MIG] base_import_security_group
  base_import_security_group/README.rst
  base_import_security_group/__init__.py
  base_import_security_group/__manifest__.py
  base_import_security_group/i18n/base_import_security_group.pot
  base_import_security_group/i18n/ca.po
  base_import_security_group/i18n/de.po
  base_import_security_group/i18n/es.po
  base_import_security_group/i18n/fr.po
  base_import_security_group/i18n/gl.po
  base_import_security_group/i18n/hr.po
  base_import_security_group/i18n/it.po
  base_import_security_group/i18n/pt.po
  base_import_security_group/i18n/sk.po
  base_import_security_group/models/__init__.py
  base_import_security_group/models/base.py
  base_import_security_group/models/ir_http.py
  base_import_security_group/pyproject.toml
  base_import_security_group/readme/CONTRIBUTORS.md
  base_import_security_group/readme/DESCRIPTION.md
  base_import_security_group/security/base_import_security_group_security.xml
  base_import_security_group/static/description/icon.png
  base_import_security_group/static/description/icon.svg
  base_import_security_group/static/description/index.html
  base_import_security_group/static/src/js/import.esm.js
  base_import_security_group/static/src/js/tour_import.esm.js
  base_import_security_group/tests/__init__.py
  base_import_security_group/tests/test_base_import_security_group.py
Labels: approved, bot is merging ⏳

#1061 [16.0][FIX] template_content_swapper: use _render()
  template_content_swapper/README.rst
  template_content_swapper/__manifest__.py
  template_content_swapper/models/__init__.py
  template_content_swapper/models/ir_qweb.py
  template_content_swapper/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#965 [16.0][ADD] base_user_chatter
  base_user_chatter/README.rst
  base_user_chatter/__init__.py
  base_user_chatter/__manifest__.py
  base_user_chatter/models/__init__.py
  base_user_chatter/models/res_users.py
  base_user_chatter/readme/DESCRIPTION.md
  base_user_chatter/static/description/index.html
  base_user_chatter/views/res_users_views.xml
  setup/base_user_chatter/odoo/addons/base_user_chatter
  setup/base_user_chatter/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#981 [18.0] [MIG] date_range_account: Migration to 18.0
  date_range_account/README.rst
  date_range_account/__init__.py
  date_range_account/__manifest__.py
  date_range_account/i18n/date_range_account.pot
  date_range_account/i18n/es.po
  date_range_account/i18n/fr.po
  date_range_account/i18n/it.po
  date_range_account/i18n/nl.po
  date_range_account/pyproject.toml
  date_range_account/readme/CONTRIBUTORS.md
  date_range_account/readme/DESCRIPTION.md
  date_range_account/security/ir.model.access.csv
  date_range_account/static/description/icon.png
  date_range_account/static/description/index.html
  date_range_account/views/date_range.xml
Labels: approved, bot is merging ⏳

#924 [17.0] [MIG] base_tier_validation_server_action: Migration to 17.0
  base_tier_validation_server_action/README.rst
  base_tier_validation_server_action/__init__.py
  base_tier_validation_server_action/__manifest__.py
  base_tier_validation_server_action/data/cron_data.xml
  base_tier_validation_server_action/i18n/base_tier_validation_server_action.pot
  base_tier_validation_server_action/i18n/es.po
  base_tier_validation_server_action/i18n/it.po
  base_tier_validation_server_action/models/__init__.py
  base_tier_validation_server_action/models/tier_definition.py
  base_tier_validation_server_action/models/tier_validation.py
  base_tier_validation_server_action/pyproject.toml
  base_tier_validation_server_action/readme/CONFIGURE.md
  base_tier_validation_server_action/readme/CONTRIBUTORS.md
  base_tier_validation_server_action/readme/DESCRIPTION.md
  base_tier_validation_server_action/static/description/icon.png
  base_tier_validation_server_action/static/description/index.html
  base_tier_validation_server_action/tests/__init__.py
  base_tier_validation_server_action/tests/test_tier_validation.py
  base_tier_validation_server_action/tests/tier_validation_tester.py
  base_tier_validation_server_action/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#1078 [17.0] base_tier_validation: port 1076 from 18.0 to 17.0
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#1077 [18.0][FIX] base_tier_valiation: readonly attribute
  base_tier_validation/models/tier_validation.py
Labels: approved, bot is merging ⏳

#1088 [16.0][FIX] base_search_custom_field_filter: Avoid hiding model fields in other parts of the UI
  base_search_custom_field_filter/README.rst
  base_search_custom_field_filter/__manifest__.py
  base_search_custom_field_filter/models/base.py
  base_search_custom_field_filter/static/description/index.html
Labels: approved, bot is merging ⏳
