Repository OCA/server-ux, pull requests merged in 2025-06, with the labels that each got.

#882 [15.0][MIG] template_content_swapper: backport from 16.0 to 15.0
  setup/template_content_swapper/odoo/addons/template_content_swapper
  setup/template_content_swapper/setup.py
  template_content_swapper/README.rst
  template_content_swapper/__init__.py
  template_content_swapper/__manifest__.py
  template_content_swapper/i18n/it.po
  template_content_swapper/i18n/template_content_swapper.pot
  template_content_swapper/models/__init__.py
  template_content_swapper/models/ir_ui_view.py
  template_content_swapper/models/template_content_mapping.py
  template_content_swapper/readme/CONFIGURE.rst
  template_content_swapper/readme/CONTRIBUTORS.rst
  template_content_swapper/readme/DESCRIPTION.rst
  template_content_swapper/readme/USAGE.rst
  template_content_swapper/security/ir.model.access.csv
  template_content_swapper/static/description/icon.png
  template_content_swapper/static/description/index.html
  template_content_swapper/static/img/login_after.png
  template_content_swapper/static/img/login_before.png
  template_content_swapper/static/img/mapping.png
  template_content_swapper/tests/__init__.py
  template_content_swapper/tests/test_template_content_swapper.py
  template_content_swapper/views/template_content_mapping_views.xml
Labels: approved, bot is merging ⏳

#974 [MIG] multi_step_wizard: Migration to 18.0
  multi_step_wizard/README.rst
  multi_step_wizard/__init__.py
  multi_step_wizard/__manifest__.py
  multi_step_wizard/i18n/ca.po
  multi_step_wizard/i18n/de.po
  multi_step_wizard/i18n/es.po
  multi_step_wizard/i18n/hr.po
  multi_step_wizard/i18n/it.po
  multi_step_wizard/i18n/multi_step_wizard.pot
  multi_step_wizard/i18n/nl.po
  multi_step_wizard/i18n/zh_CN.po
  multi_step_wizard/models/__init__.py
  multi_step_wizard/models/multi_step_wizard.py
  multi_step_wizard/pyproject.toml
  multi_step_wizard/readme/CONTRIBUTORS.md
  multi_step_wizard/readme/DESCRIPTION.md
  multi_step_wizard/readme/USAGE.md
  multi_step_wizard/static/description/icon.png
  multi_step_wizard/static/description/index.html
  multi_step_wizard/tests/__init__.py
  multi_step_wizard/tests/common.py
  multi_step_wizard/tests/multi_step_wizard_test.py
  multi_step_wizard/tests/test_multi_step_wizard.py
  multi_step_wizard/views/multi_step_wizard_views.xml
Labels: question, approved, bot is merging ⏳

#985 [18.0][ADD] server_action_mass_edit_onchange: extension to support playing onchange
  server_action_mass_edit/wizard/mass_editing_wizard.py
  server_action_mass_edit_onchange/README.rst
  server_action_mass_edit_onchange/__init__.py
  server_action_mass_edit_onchange/__manifest__.py
  server_action_mass_edit_onchange/models/__init__.py
  server_action_mass_edit_onchange/models/ir_actions_server.py
  server_action_mass_edit_onchange/models/ir_actions_server_mass_edit_line.py
  server_action_mass_edit_onchange/pyproject.toml
  server_action_mass_edit_onchange/readme/CONTRIBUTORS.md
  server_action_mass_edit_onchange/readme/DESCRIPTION.md
  server_action_mass_edit_onchange/static/description/index.html
  server_action_mass_edit_onchange/tests/__init__.py
  server_action_mass_edit_onchange/tests/test_mass_editing.py
  server_action_mass_edit_onchange/views/ir_actions_server.xml
  server_action_mass_edit_onchange/wizard/__init__.py
  server_action_mass_edit_onchange/wizard/mass_editing_wizard.py
Labels: approved, bot is merging ⏳, stale

#1099 [18.0][MIG] announcement: Migration to version 18.0
  .copier-answers.yml
  .pre-commit-config.yaml
  announcement/README.rst
  announcement/__init__.py
  announcement/__manifest__.py
  announcement/demo/announcement_tag_demo.xml
  announcement/i18n/announcement.pot
  announcement/i18n/es.po
  announcement/i18n/it.po
  announcement/models/__init__.py
  announcement/models/announcement.py
  announcement/models/announcement_tag.py
  announcement/models/ir_http.py
  announcement/models/res_users.py
  announcement/pyproject.toml
  announcement/readme/CONFIGURE.md
  announcement/readme/CONTRIBUTORS.md
  announcement/readme/DESCRIPTION.md
  announcement/readme/ROADMAP.md
  announcement/readme/USAGE.md
  announcement/security/announcement_security.xml
  announcement/security/ir.model.access.csv
  announcement/static/description/icon.png
  announcement/static/description/icon.svg
  announcement/static/description/index.html
  announcement/static/src/js/announcement_dialog/announcement_dialog.esm.js
  announcement/static/src/js/announcement_menu/announcement_menu.esm.js
  announcement/static/src/js/announcement_menu/announcement_menu.xml
  announcement/static/src/js/announcement_service/announcement_service.esm.js
  announcement/tests/__init__.py
  announcement/tests/test_announcement.py
  announcement/views/announcement_tag_views.xml
  announcement/views/announcement_views.xml
  announcement/wizards/__init__.py
  announcement/wizards/read_announcement_wizard.py
  announcement/wizards/read_announcement_wizard.xml
  eslint.config.cjs
Labels: approved, bot is merging ⏳

#1092 [18.0][MIG] template_content_swapper: Migration to 18.0
  template_content_swapper/README.rst
  template_content_swapper/__init__.py
  template_content_swapper/__manifest__.py
  template_content_swapper/i18n/it.po
  template_content_swapper/i18n/template_content_swapper.pot
  template_content_swapper/models/__init__.py
  template_content_swapper/models/ir_qweb.py
  template_content_swapper/models/template_content_mapping.py
  template_content_swapper/pyproject.toml
  template_content_swapper/readme/CONFIGURE.md
  template_content_swapper/readme/CONTRIBUTORS.md
  template_content_swapper/readme/DESCRIPTION.md
  template_content_swapper/readme/USAGE.md
  template_content_swapper/security/ir.model.access.csv
  template_content_swapper/static/description/icon.png
  template_content_swapper/static/description/index.html
  template_content_swapper/static/img/login_after.png
  template_content_swapper/static/img/login_before.png
  template_content_swapper/static/img/mapping.png
  template_content_swapper/tests/__init__.py
  template_content_swapper/tests/test_template_content_swapper.py
  template_content_swapper/views/template_content_mapping_views.xml
Labels: approved, bot is merging ⏳

#1105 [17.0][FIX] base_tier_validation: add field attrs references
  base_tier_validation/templates/tier_validation_templates.xml
Labels: bot is merging ⏳

#1098 [18.0][MIG] mail_suggested_recipient_unchecked: Migration to 18.0
  mail_suggested_recipient_unchecked/README.rst
  mail_suggested_recipient_unchecked/__init__.py
  mail_suggested_recipient_unchecked/__manifest__.py
  mail_suggested_recipient_unchecked/i18n/it.po
  mail_suggested_recipient_unchecked/i18n/mail_suggested_recipient_unchecked.pot
  mail_suggested_recipient_unchecked/models/__init__.py
  mail_suggested_recipient_unchecked/models/mail_thread.py
  mail_suggested_recipient_unchecked/pyproject.toml
  mail_suggested_recipient_unchecked/readme/CONTRIBUTORS.md
  mail_suggested_recipient_unchecked/readme/DESCRIPTION.md
  mail_suggested_recipient_unchecked/readme/USAGE.md
  mail_suggested_recipient_unchecked/static/description/icon.png
  mail_suggested_recipient_unchecked/static/description/index.html
  mail_suggested_recipient_unchecked/tests/__init__.py
  mail_suggested_recipient_unchecked/tests/test_mail_suggested_recipient_unchecked.py
Labels: approved, bot is merging ⏳
