Repository OCA/server-ux, pull requests merged in 2025-03, with the labels that each got.

#1035 [16.0][IMP] base_tier_validation: UI Improvements
  base_tier_validation/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#1028 [18.0][MIG] base_tier_validation_formula: Migration to 18.0
  base_tier_validation_formula/README.rst
  base_tier_validation_formula/__init__.py
  base_tier_validation_formula/__manifest__.py
  base_tier_validation_formula/i18n/base_tier_validation_formula.pot
  base_tier_validation_formula/i18n/es.po
  base_tier_validation_formula/i18n/it.po
  base_tier_validation_formula/i18n/zh_CN.po
  base_tier_validation_formula/models/__init__.py
  base_tier_validation_formula/models/tier_definition.py
  base_tier_validation_formula/models/tier_review.py
  base_tier_validation_formula/models/tier_validation.py
  base_tier_validation_formula/pyproject.toml
  base_tier_validation_formula/readme/CONTRIBUTORS.md
  base_tier_validation_formula/readme/CREDITS.md
  base_tier_validation_formula/readme/DESCRIPTION.md
  base_tier_validation_formula/readme/USAGE.md
  base_tier_validation_formula/static/description/icon.png
  base_tier_validation_formula/static/description/index.html
  base_tier_validation_formula/tests/__init__.py
  base_tier_validation_formula/tests/test_tier_validation.py
  base_tier_validation_formula/views/tier_definition_view.xml
Labels: approved, bot is merging ⏳

#1037 [17.0][MIG] base_cancel_confirm
  base_cancel_confirm/README.rst
  base_cancel_confirm/__init__.py
  base_cancel_confirm/__manifest__.py
  base_cancel_confirm/i18n/base_cancel_confirm.pot
  base_cancel_confirm/i18n/es.po
  base_cancel_confirm/i18n/it.po
  base_cancel_confirm/i18n/nl.po
  base_cancel_confirm/model/__init__.py
  base_cancel_confirm/model/base_cancel_confirm.py
  base_cancel_confirm/pyproject.toml
  base_cancel_confirm/readme/CONFIGURE.md
  base_cancel_confirm/readme/CONTRIBUTORS.md
  base_cancel_confirm/readme/DESCRIPTION.md
  base_cancel_confirm/security/ir.model.access.csv
  base_cancel_confirm/static/description/icon.png
  base_cancel_confirm/static/description/index.html
  base_cancel_confirm/tests/__init__.py
  base_cancel_confirm/tests/cancel_confirm_tester.py
  base_cancel_confirm/tests/test_cancel_confirm.py
  base_cancel_confirm/views/cancel_confirm_template.xml
  base_cancel_confirm/wizard/__init__.py
  base_cancel_confirm/wizard/cancel_confirm.py
  base_cancel_confirm/wizard/cancel_confirm.xml
Labels: approved, bot is merging ⏳

#1036 [16.0][IMP] document_quick_access_folder_auto_classification: warning refresh
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
Labels: bot is merging ⏳

#1038 [16.0][FIX] base_tier_validation: Do not update the counter if it is not possible to review it.
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#1041 [17.0][FIX] base_tier_validation: Do not update the counter if it is not possible to review it
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#1042 [18.0][FIX] base_tier_validation: Do not update the counter if it is not possible to review it
  base_tier_validation/models/tier_review.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#1000 [MIG][18.0] Migration of mail_message_destiny_link_template (from 16.0)
  mail_message_destiny_link_template/README.rst
  mail_message_destiny_link_template/__init__.py
  mail_message_destiny_link_template/__manifest__.py
  mail_message_destiny_link_template/data/mail_templates_chatter.xml
  mail_message_destiny_link_template/i18n/es.po
  mail_message_destiny_link_template/i18n/it.po
  mail_message_destiny_link_template/i18n/mail_message_destiny_link_template.pot
  mail_message_destiny_link_template/pyproject.toml
  mail_message_destiny_link_template/readme/CONTEXT.md
  mail_message_destiny_link_template/readme/CONTRIBUTORS.md
  mail_message_destiny_link_template/readme/DESCRIPTION.md
  mail_message_destiny_link_template/readme/USAGE.md
  mail_message_destiny_link_template/static/description/icon.png
  mail_message_destiny_link_template/static/description/index.html
Labels: approved, bot is merging ⏳

#936 [FIX] base_revision: UX, open Form if only one revision record
  base_revision/models/base_revision.py
Labels: approved, bot is merging ⏳

#735 [15.0][FIX] base_substate: track template on substate
  base_substate/models/base_substate_mixin.py
  base_substate/tests/sale_test.py
  base_substate/tests/test_base_substate.py
Labels: approved, bot is merging ⏳

#736 [16.0][FIX] base_substate: track template on substate
  base_substate/README.rst
  base_substate/__manifest__.py
  base_substate/models/base_substate_mixin.py
  base_substate/static/description/index.html
  base_substate/tests/sale_test.py
  base_substate/tests/test_base_substate.py
Labels: approved, bot is merging ⏳, stale

#982 [17.0][FIX] base_substate: migrate track_template function
  base_substate/models/base_substate_mixin.py
Labels: approved, bot is merging ⏳

#1045 [18.0][FIX] base_tier_validation: request tier with multi-company
  base_tier_validation/models/tier_validation.py
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation/tests/tier_validation_tester.py
Labels: approved, ready to merge, bot is merging ⏳
