Repository OCA/server-ux, pull requests merged in 2025-08, with the labels that each got.

#1133 [18.0][MIG] document_quick_access: Migration to 18.0
  document_quick_access/README.rst
  document_quick_access/__init__.py
  document_quick_access/__manifest__.py
  document_quick_access/i18n/document_quick_access.pot
  document_quick_access/i18n/es.po
  document_quick_access/i18n/it.po
  document_quick_access/models/__init__.py
  document_quick_access/models/base.py
  document_quick_access/models/document_quick_access_rule.py
  document_quick_access/pyproject.toml
  document_quick_access/readme/CONFIGURE.md
  document_quick_access/readme/CONTRIBUTORS.md
  document_quick_access/readme/DESCRIPTION.md
  document_quick_access/readme/ROADMAP.md
  document_quick_access/readme/USAGE.md
  document_quick_access/security/ir.model.access.csv
  document_quick_access/static/description/icon.png
  document_quick_access/static/description/index.html
  document_quick_access/static/src/js/document_quick_access_launcher.esm.js
  document_quick_access/static/src/xml/document_quick_access_launcher.xml
  document_quick_access/tests/__init__.py
  document_quick_access/tests/test_document_quick_access.py
  document_quick_access/views/document_quick_access_rule.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1137 [16.0][FIX+IMP] base_tier_validation: base_tier_validation_waiting compatibiity
  base_tier_validation/migrations/16.0.3.1.0/pre-migration.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation_waiting/models/tier_validation.py
Labels: approved, bot is merging ⏳

#1130 [18.0][MIG] default_multi_user: Migration to 18.0
  default_multi_user/README.rst
  default_multi_user/__init__.py
  default_multi_user/__manifest__.py
  default_multi_user/hooks.py
  default_multi_user/i18n/default_multi_user.pot
  default_multi_user/i18n/es.po
  default_multi_user/i18n/pt.po
  default_multi_user/models/__init__.py
  default_multi_user/models/ir_default.py
  default_multi_user/pyproject.toml
  default_multi_user/readme/CONFIGURE.md
  default_multi_user/readme/CONTRIBUTORS.md
  default_multi_user/readme/DESCRIPTION.md
  default_multi_user/static/description/icon.png
  default_multi_user/static/description/index.html
  default_multi_user/tests/__init__.py
  default_multi_user/tests/test_default_multi_user.py
  default_multi_user/views/ir_default_view.xml
Labels: approved, bot is merging ⏳

#1136 [17.0][IMP] base_tier_validation: Make the validation_status field store so that it can be used in searchs
  base_tier_validation/README.rst
  base_tier_validation/__manifest__.py
  base_tier_validation/migrations/17.0.3.1.0/pre-migration.py
  base_tier_validation/models/res_users.py
  base_tier_validation/models/tier_validation.py
  base_tier_validation/static/description/index.html
  base_tier_validation/templates/tier_validation_templates.xml
  base_tier_validation/tests/common.py
  base_tier_validation/tests/test_tier_validation.py
  base_tier_validation_forward/models/tier_validation.py
  base_tier_validation_forward/tests/test_tier_validation.py
Labels: approved, bot is merging ⏳

#1139 [18.0][FIX] base_tier_validation: Prevent errors in migration script
  base_tier_validation/migrations/18.0.2.1.0/pre-migration.py
Labels: approved

#1068 [18.0][IMP] sequence_check_digit: support ean
  sequence_check_digit/i18n/es.po
  sequence_check_digit/i18n/it.po
  sequence_check_digit/i18n/sequence_check_digit.pot
  sequence_check_digit/models/ir_sequence.py
  sequence_check_digit/tests/test_check_digit.py
Labels: approved, bot is merging ⏳

#1143 [18.0][MIG] filter_multi_user: Migration to 18.0
  filter_multi_user/README.rst
  filter_multi_user/__init__.py
  filter_multi_user/__manifest__.py
  filter_multi_user/i18n/es.po
  filter_multi_user/i18n/filter_multi_user.pot
  filter_multi_user/i18n/it.po
  filter_multi_user/i18n/tr.po
  filter_multi_user/models/__init__.py
  filter_multi_user/models/ir_filters.py
  filter_multi_user/pyproject.toml
  filter_multi_user/readme/CONFIGURE.md
  filter_multi_user/readme/CONTRIBUTORS.md
  filter_multi_user/readme/DESCRIPTION.md
  filter_multi_user/security/ir_filters_security.xml
  filter_multi_user/static/description/icon.png
  filter_multi_user/static/description/index.html
  filter_multi_user/tests/__init__.py
  filter_multi_user/tests/test_filter_multi_user.py
  filter_multi_user/views/ir_filters_view.xml
Labels: approved, bot is merging ⏳
