Repository OCA/server-ux, pull requests merged in 2025-01, with the labels that each got.

#987 [16.0][MIG] sequence_check_digit: Migration to 16.0
  sequence_check_digit/README.rst
  sequence_check_digit/__init__.py
  sequence_check_digit/__manifest__.py
  sequence_check_digit/i18n/es.po
  sequence_check_digit/i18n/it.po
  sequence_check_digit/i18n/sequence_check_digit.pot
  sequence_check_digit/models/__init__.py
  sequence_check_digit/models/ir_sequence.py
  sequence_check_digit/readme/CONTRIBUTORS.rst
  sequence_check_digit/readme/DESCRIPTION.rst
  sequence_check_digit/readme/USAGE.rst
  sequence_check_digit/static/description/icon.png
  sequence_check_digit/static/description/index.html
  sequence_check_digit/tests/__init__.py
  sequence_check_digit/tests/test_check_digit.py
  sequence_check_digit/views/sequence_views.xml
  setup/sequence_check_digit/odoo/addons/sequence_check_digit
  setup/sequence_check_digit/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#906 [16.0] [MIG] document_quick_access_folder_auto_classification: Migration to 16.0
  document_quick_access_folder_auto_classification/README.rst
  document_quick_access_folder_auto_classification/__init__.py
  document_quick_access_folder_auto_classification/__manifest__.py
  document_quick_access_folder_auto_classification/components/__init__.py
  document_quick_access_folder_auto_classification/components/document_quick_access_process.py
  document_quick_access_folder_auto_classification/data/edi_data.xml
  document_quick_access_folder_auto_classification/i18n/document_quick_access_folder_auto_classification.pot
  document_quick_access_folder_auto_classification/models/__init__.py
  document_quick_access_folder_auto_classification/models/document_quick_access_rule.py
  document_quick_access_folder_auto_classification/readme/CONFIGURE.rst
  document_quick_access_folder_auto_classification/readme/CONTRIBUTORS.rst
  document_quick_access_folder_auto_classification/readme/DESCRIPTION.rst
  document_quick_access_folder_auto_classification/readme/USAGE.rst
  document_quick_access_folder_auto_classification/security/ir.model.access.csv
  document_quick_access_folder_auto_classification/security/security.xml
  document_quick_access_folder_auto_classification/static/description/icon.png
  document_quick_access_folder_auto_classification/static/description/icon.svg
  document_quick_access_folder_auto_classification/static/description/index.html
  document_quick_access_folder_auto_classification/tests/__init__.py
  document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py
  document_quick_access_folder_auto_classification/tests/test_file.pdf
  document_quick_access_folder_auto_classification/views/edi_exchange_record.xml
  document_quick_access_folder_auto_classification/wizards/__init__.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.py
  document_quick_access_folder_auto_classification/wizards/document_quick_access_missing_assign.xml
  setup/document_quick_access_folder_auto_classification/odoo/addons/document_quick_access_folder_auto_classification
  setup/document_quick_access_folder_auto_classification/setup.py
Labels: approved, bot is merging ⏳

#996 [16.0][FIX] base_technical_features: Add depends key in __manifest__.py
  base_technical_features/__manifest__.py
Labels: approved, bot is merging ⏳

#998 [17.0][FIX] base_technical_features: Add depends key in __manifest__.py
  base_technical_features/__manifest__.py
Labels: bot is merging ⏳

#995 [17.0][FIX] base_tier_validation: rule tier.validation.exceptions has no group
  base_tier_validation/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, Pending to fw/back port

#1004 [FIX] sequence_check_digit: Constrain should work with multiple records
  sequence_check_digit/models/ir_sequence.py
Labels: bot is merging ⏳

#988 [18.0][MIG] sequence_check_digit: Migration to 18.0
  sequence_check_digit/README.rst
  sequence_check_digit/__init__.py
  sequence_check_digit/__manifest__.py
  sequence_check_digit/i18n/es.po
  sequence_check_digit/i18n/it.po
  sequence_check_digit/i18n/sequence_check_digit.pot
  sequence_check_digit/models/__init__.py
  sequence_check_digit/models/ir_sequence.py
  sequence_check_digit/pyproject.toml
  sequence_check_digit/readme/CONTRIBUTORS.md
  sequence_check_digit/readme/DESCRIPTION.md
  sequence_check_digit/readme/USAGE.md
  sequence_check_digit/static/description/icon.png
  sequence_check_digit/static/description/index.html
  sequence_check_digit/tests/__init__.py
  sequence_check_digit/tests/test_check_digit.py
  sequence_check_digit/views/sequence_views.xml
Labels: approved, bot is merging ⏳

#1007 [FIX] barcode_action: Context is not passed
  barcode_action/static/src/js/action_barcode_widget.esm.js
Labels: approved, bot is merging ⏳

#1008 [FIX] barcode_action: Context is not passed
  barcode_action/static/src/js/action_barcode_widget.esm.js
Labels: bot is merging ⏳
